Escape image filenames
sphinx-doc/sphinx pull request #10268
Opened 2022-03-16 13:51 UTC by eric-wieser

Without this change, local images with `#` in their name result in incorrect URLs

There is already a similar call to `urllib.parse.quote` for file downloads, suggesting this is a sensible approach.

Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix
- Refactoring

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2022-03-16 15:51 UTC, tk0miya requested changes
Looks good. Could you add a testcase for this, please? Then I'll merge this soon.

2022-03-16 18:28 UTC, eric-wieser commented
#9670 didn't have a test-case, so I was hoping I could get away without one here too...

I might have time for a test-case in a week or so, we'll see.

2022-03-20 16:38 UTC, tk0miya commented
It seems #9670 contains a test-case :-)

2022-03-26 17:15 UTC, tk0miya commented
Hmm... epubcheck and LaTeX build are failed when we use `#` for the filename. So escaping is not a good way to handle such files. We need to rename them on copying to the generated document.

2022-03-26 17:48 UTC, eric-wieser commented
It sounds like the latex code needs escaping too

2022-03-26 17:48 UTC, eric-wieser commented
Thanks for fixing the broken tests!

2022-03-26 17:52 UTC, eric-wieser commented
Is there any way to see the latex error message from CI?

2022-03-26 22:59 UTC, eric-wieser commented
I think the CI failure is actually a bug in `epubcheck`

2022-10-05 12:46 UTC, AA-Turner commented on sphinx/builders/_epub_base.py
> +from urllib.parse import quote
```suggestion
from urllib.parse import quote
from zipfile import ZIP_DEFLATED, ZIP_STORED, ZipFile
```

2022-10-05 16:46 UTC, AA-Turner commented
@eric-wieser it looks like the test failures are pretty simple to solve--are you up for having a look, it would be nice to get this in to 5.3.

A

2022-10-13 16:16 UTC, AA-Turner commented on CHANGES
> +# 10268: Correctly URI-escape image filenames.
```suggestion
* #10268: Correctly URI-escape image filenames.
```

2022-10-13 16:37 UTC, merged

2022-10-13 16:37 UTC, AA-Turner commented
Thanks @eric-wieser!

A