Add comments on ImageMagick requirement
sphinx-doc/sphinx pull request #10386
Opened 2022-04-24 12:54 UTC by mxd4

Subject: Add comments  to clarify the cause of issue #10384 

### Purpose
Allow newcomers to quickly understand the requirement to ImageMagick if `test_ext_imgconverter.py` fails.

2022-05-02 09:23 UTC, AA-Turner requested changes

2022-05-02 09:23 UTC, AA-Turner commented on tests/test_ext_imgconverter.py
> +Requires ImageMagick to be installed, otherwise the conversion will be skipped and this test will fail.
```suggestion

Unix only. Fails if ImageMagick_ is not installed.

.. _ImageMagick: https://imagemagick.org
```

2022-05-02 09:23 UTC, AA-Turner commented on doc/usage/extensions/imgconverter.rst
>  .. _Imagemagick: https://www.imagemagick.org/script/index.php
```suggestion
.. _ImageMagick: https://www.imagemagick.org
```

2022-05-02 09:23 UTC, AA-Turner commented on doc/usage/extensions/imgconverter.rst
> +you'll have to install it on your machine.
```suggestion
The extension uses ImageMagick_ to perform conversions, 
and will fail if ImageMagick is not installed.
```

2022-05-02 09:23 UTC, mxd4 commented
CI [failed](https://github.com/sphinx-doc/sphinx/actions/runs/2215634837) on mypy and docslint steps.
I fixed the docslint error and rebased `5.x` to get the mypy fix.
@tk0miya could you run it again? 🙏🏻

2022-05-02 09:31 UTC, mxd4 commented
Thanks a lot for the suggestions @AA-Turner
All done :)

2022-05-02 09:36 UTC, AA-Turner commented
I think more usefully you should also change the warning

https://github.com/sphinx-doc/sphinx/blob/8c7a472d58f832b9e2bd05d9d0fd5dbe0fcf077f/sphinx/ext/imgconverter.py#L32-L36

Something like the following may be more useful:

```diff
-            logger.warning(__('convert command %r cannot be run, '
-                              'check the image_converter setting: %s'),
-                           self.config.image_converter, exc)
+            logger.warning(__(
+                'Unable to run the image conversion command {self.config.image_converter!r}! '
+                'sphinx.ext.imgconverter' requires ImageMagick by defult. '
+                'Ensure it is installed, or set the configuration option '
+                "'image_converter' to a custom conversion command.\n\n"
+                'Traceback: {exc}'
+            ))
```

A

2022-05-02 09:37 UTC, AA-Turner commented
I'm somewhat conflicted on the change of the documentation -- as noted in the extension, ImageMagick is just a default, and can be changed. Perhaps add "by default" or similar?

https://github.com/sphinx-doc/sphinx/blob/8c7a472d58f832b9e2bd05d9d0fd5dbe0fcf077f/sphinx/ext/imgconverter.py#L69-L79

A

2022-05-02 10:26 UTC, mxd4 commented
@AA-Turner I agree. 
I've just added the suggested warning, as well as changes to the doc to make it clearer.
It's now explicit that the provided command is `convert` by default and uses ImageMagick, but can be overridden.

2022-05-02 10:41 UTC, AA-Turner approved these changes
Grammar suggestions, otherwise seems alright!

A

2022-05-02 10:41 UTC, AA-Turner commented on doc/usage/extensions/imgconverter.rst
> +   On Unix platform, :command:`convert` command is used by default.
```suggestion
   On Unix platforms, the command :command:`convert` is used by default.
```

2022-05-02 10:41 UTC, AA-Turner commented on doc/usage/extensions/imgconverter.rst
> +   On Windows platform, :command:`magick` command is used by default.
```suggestion
   On Windows, the command :command:`magick` is used by default.
```

2022-05-02 10:41 UTC, AA-Turner commented on doc/usage/extensions/imgconverter.rst
> +   On Windows platform, it defaults to ``["convert"]``.
```suggestion
   On Windows, it defaults to ``["convert"]``.
```

2022-05-02 15:51 UTC, tk0miya commented
Thank you for your work, and sorry for the incovinience. I think it's better to skip the test if ImageMagick not found. So I just posted https://github.com/sphinx-doc/sphinx/pull/10411 to do that.

2022-05-02 15:55 UTC, tk0miya requested changes
LGTM with nits.

2022-05-02 15:55 UTC, tk0miya commented on sphinx/ext/imgconverter.py
> +                "\n'sphinx.ext.imgconverter' requires ImageMagick by default. "
Is there any reason to put "\n" on the top of the line?

2022-05-02 15:55 UTC, tk0miya commented on sphinx/ext/imgconverter.py
> +                f"Unable to run the image conversion command {self.config.image_converter!r}!"
Usually, we don't use exclamation marks for warning. Could you replace it with a period?

2022-05-02 15:55 UTC, tk0miya commented on tests/test_ext_imgconverter.py
> +Unix only. Fails if ImageMagick_ is not installed.
I believe https://github.com/sphinx-doc/sphinx/pull/10411 will be able to remove this comment.

2022-05-02 16:01 UTC, mxd4 commented on sphinx/ext/imgconverter.py
> +                "\n'sphinx.ext.imgconverter' requires ImageMagick by default. "
I wanted a bit more readability, first I added it at the end of line 34 but it made the line too long for flake8.
However if it's bad practice to put `\n` in the middle of warning messages I can remove it.

2022-05-22 10:21 UTC, tk0miya approved these changes

2022-05-22 10:22 UTC, tk0miya commented
Sorry for my late response. Merging now. Thank you for your contribution!

2022-05-22 10:22 UTC, merged