Epub: Add WebP mime type
sphinx-doc/sphinx pull request #10443
Opened 2022-05-10 21:35 UTC by Blendify

When building docs with WebP images using the EPUB builder results in this warning:

`WARNING: unknown mimetype for _images/<image_name>.webp, ignoring`

This commit fixes this by adding the mapping for webp-files to the correct mime type.

2022-05-11 01:10 UTC, AA-Turner commented
This would need a test case, ideally.

A

2022-05-14 06:28 UTC, tk0miya requested changes
LGTM. To ship this as v5.0.0, could you rebase this into the 5.0.x branch, please? Then I'll merge this soon.

2022-05-14 06:28 UTC, tk0miya commented
I think this is a data mapping. So testing is not needed.

2022-05-14 13:41 UTC, AA-Turner commented
I was more thinking a simple regression test that WebP is accepted, rather than anything fancier.

A

2022-05-15 11:53 UTC, tk0miya commented
+0 for adding a test.

2022-05-22 05:48 UTC, tk0miya commented
It seems 5.0.x branch is already broken (it contains a commit for 5.1). So I'll fix it after merging this.
Thank you for your contribution.

2022-05-22 05:48 UTC, merged