Close #10444: html theme: Allow to specify multiple CSS files via "stylesheet" setting
sphinx-doc/sphinx pull request #10465
Opened 2022-05-22 14:25 UTC by tk0miya

### Feature or Bugfix
- Feature

### Purpose
- refs: #10444

2022-05-22 14:49 UTC, mgeier commented
Thanks @tk0miya, this works great!

Since [html_style](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=html_style#confval-html_style) can be used to overwrite this, wouldn't it make sense to extend `html_style` as well to accept a list of themes (in addition to a single string)?

2022-05-27 21:07 UTC, AA-Turner requested changes
We should also remove the private `_get_style_filename` method if it is no longer used.

A

2022-05-27 21:07 UTC, AA-Turner commented on sphinx/builders/html/__init__.py
> +            return ['default.css']
```suggestion
    def _get_style_filenames(self) -> Iterator[str]:
        if isinstance(self.config.html_style, str):
            yield self.config.html_style
        elif self.config.html_style is not None:
            yield from self.config.html_style
        elif self.theme:
            stylesheet = self.theme.get_config('theme', 'stylesheet')
            yield from (s.strip() for s in stylesheet.split(', '))
        else:
            yield 'default.css'
```

2022-05-27 21:07 UTC, AA-Turner commented on sphinx/builders/html/__init__.py
> +        for filename in self.get_style_filenames():
```suggestion
        for filename in self._get_style_filenames():
```

2022-05-27 21:07 UTC, AA-Turner commented on CHANGES
> +  setting on ``theme.conf``
```suggestion
* #10444: html theme: Allow specifying multiple CSS files through the ``stylesheet``
  setting in ``theme.conf`` or by setting ``html_style`` to an iterable of strings.
```

2022-07-17 11:27 UTC, merged