Fix Python docstring type handling bug
sphinx-doc/sphinx pull request #10738
Opened 2022-07-31 17:10 UTC by ProGamerGov

This PR ensures that Google style docstrings using  '`of`' are properly handled.

For example:

```
def func(t, x, y):
    """
    Args:

        t (int or float): Variable description.
        x (list of list of int, optional): Variable description.
        y (tensor or tuple of tensors): Variable description.
    """ 
```

According to the regex used here: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/python.py#L381, only some of the variables in the above function's docstring will be properly handled. Anything with '`of`' in it will not be properly separated by the regex code. This PR fixes this issue. 

If this PR is on the wrong branch, let me know!

### Feature or Bugfix
- Bugfix

### Purpose
- Fixes docstring format bug.

### Detail

Below are some examples of failures made visible by using Intersphinx. Notably types using '`of`' are not properly hyperlinked.

![](https://user-images.githubusercontent.com/10626398/181404869-269e4c9a-1617-4a3f-9168-3f312fa99b2d.jpg)

![](https://user-images.githubusercontent.com/10626398/180608553-03ebafe7-4543-4560-97cf-5e6bfab603dd.JPG)

### Relates
- N/A

2022-07-31 18:33 UTC, AA-Turner commented
Is the `of` delimiter endorsed by the google style guide?

A

2022-07-31 18:45 UTC, ProGamerGov commented
@AA-Turner Yeah, you can see an example here: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html


```
        Args:
            param1 (str): Description of `param1`.
            param2 (:obj:`int`, optional): Description of `param2`. Multiple
                lines are supported.
            param3 (:obj:`list` of :obj:`str`): Description of `param3`.
```


I've noticed the issue in projects like [pytorch/captum](https://github.com/pytorch/captum).

2022-07-31 18:50 UTC, AA-Turner commented
The link you provided is from the now-archived `sphinxcontrib.napolean` project. Is there an example from the official google style guide rather than something third-party?

A

2022-07-31 18:57 UTC, AA-Turner commented
https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html seems to be the up-to-date copy.

2022-07-31 18:58 UTC, AA-Turner commented on sphinx/domains/python.py
> +        delims = r'(\s*[\[\]\(\),](?:\s*or|of\s)?\s*|\s+or|of\s+|\s*\|\s*|\.\.\.)'
```suggestion
        delims = r'(\s*[\[\]\(\),](?:\s*or|of\s)?\s*|\s+or|of\s+|\s*\|\s*|\.\.\.)'  # NoQA: E275
```

2022-07-31 18:58 UTC, ProGamerGov commented
@AA-Turner So, actually I may have confused Google's style guide with NumPy's style guide. NumPy's official style guidelines show `list of int` being used here: https://numpydoc.readthedocs.io/en/latest/format.html#parameters

Google's style guide though doesn't seem to explicitly mention it: https://google.github.io/styleguide/pyguide.html

2022-07-31 19:02 UTC, AA-Turner commented
`NumpyDocstring` is a superclass of `GoogleDocstring`. Please may you update the PR to override the regular expression only in `NumpyDocstring`, and add a link back to the style guide with an explanation as to why we are overriding the regular expression.

A

2022-07-31 19:07 UTC, ProGamerGov commented
@AA-Turner Yeah, we can do that. Though I'm not 100% sure of the regex works as intended. My usage of the or operator slightly removed the spaces around `or` in the output.

2022-07-31 19:08 UTC, AA-Turner commented on sphinx/domains/python.py
> +        delims = r'(\s*[\[\]\(\),](?:\s*or|of\s)?\s*|\s+or|of\s+|\s*\|\s*|\.\.\.)'  # NoQA: E275, E501
```suggestion
        delims = r'(\s*[\[\]\(\),](?:\s*or|of\s)?\s*|\s+or|of\s+|\s*\|\s*|\.\.\.)'
```

2022-07-31 19:10 UTC, AA-Turner commented on sphinx/domains/python.py
> +        delims = r'(\s*[\[\]\(\),](?:\s*or|of\s)?\s*|\s+or|of\s+|\s*\|\s*|\.\.\.)'
Does this fix the whitespace problems?
```suggestion
        delims = r'(\s*[\[\]\(\),](?:\s*o[rf]\s)?\s*|\s+o[rf]\s+|\s*\|\s*|\.\.\.)'
```

2022-07-31 19:11 UTC, ProGamerGov commented on sphinx/domains/python.py
> +        delims = r'(\s*[\[\]\(\),](?:\s*or|of\s)?\s*|\s+or|of\s+|\s*\|\s*|\.\.\.)'
Yeah that appears to solve the issue!

2022-07-31 20:05 UTC, ProGamerGov commented
Here's an example of image showing that cases using `type1 of type2` are now being hyperlinked correctly after the changes in this PR:

![sphinx_bug_fixed](https://user-images.githubusercontent.com/10626398/182042797-fc87c849-3205-44e0-b4df-77614d4d18f0.jpg)

2022-07-31 21:26 UTC, ProGamerGov commented
@AA-Turner We can merge the PR now in its current form as it resolves the issue!

Example:

![sphinx_bug_fixed](https://user-images.githubusercontent.com/10626398/182042797-fc87c849-3205-44e0-b4df-77614d4d18f0.jpg)


The `sphinx.ext.napolean` extension doesn't seem to require any changes to fully support this change.

2022-07-31 21:27 UTC, AA-Turner commented
Please add tests ensuring the behaviour doesn't regress in the future.

A

2022-07-31 21:34 UTC, AA-Turner commented
I have a slight concern over this change in that it encourages non-standard descriptions of typing -- for example if I had an object that was a `list[tuple[date, ...]]`, I think using that format in the docstring is much better than `list of tuple of int`.

I don't know if napoleon supports the type-annotation format though, and cannot test at the moment (on mobile).

A

2022-07-31 21:48 UTC, ProGamerGov commented
@AA-Turner Do you happen to know which testing file I should add the tests to?

Also, as far as I'm aware, napoleon handles `list[tuple[date, ...]]` and a quick test verifies this:

![sphinx_example_1](https://user-images.githubusercontent.com/10626398/182046654-e5c12074-5a79-4c60-a372-bfb768100fae.JPG)

2022-07-31 22:22 UTC, AA-Turner commented
See tests/test_ext_napoleon_docstring.py, around line 160 for an exemplar.

Thanks for confirming the 'proper' style works. Please also add a CHANGES entry and add yourself to AUTHORS.

A

2022-08-01 01:12 UTC, ProGamerGov commented
@AA-Turner Thanks! I've added myself to the AUTHORS file and added a new test for the changes. For the CHANGES file, I wasn't 100% sure what to say for the change, so let me know if I need to change it

2022-08-01 14:55 UTC, ProGamerGov commented
So, the tests don't currently seem to fail if the changing in this PR haven't been introduced. I think that part of the existing code may have already been capable of handing cases with '`of`', and thus the tests will always pass.

2022-08-02 19:28 UTC, ProGamerGov commented
@AA-Turner Testing now verifies that functionality introduced in this PR remains present. As the changes in this PR were on a single line in `sphinx/domains/python.py`, I added tests to `tests/test_domain_py.py`. These tests actually do fail if someone breaks the regex code changes introduced in this PR. I also added another test for the `or` deliminator as I couldn't find any examples of it being tested.

I think that this PR is finally ready for merging!

2022-08-02 21:53 UTC, AA-Turner requested changes

2022-08-02 21:53 UTC, AA-Turner commented on CHANGES
> +   python domain, like ``type or type``. Previously this functionality wasn't
This second entry isn't needed.

A

2022-08-02 21:56 UTC, AA-Turner commented
Looks good otherwise, please could you also look at the flake8 failure and then ping me.

A

2022-08-02 22:30 UTC, ProGamerGov commented on CHANGES
> +   python domain, like ``type or type``. Previously this functionality wasn't
Okay, I've removed it

2022-08-02 22:31 UTC, ProGamerGov commented
@AA-Turner I've fixed the formatting for flake8

2022-08-02 22:43 UTC, merged

2022-08-02 22:43 UTC, AA-Turner commented
Thanks Ben!

A