Fix small typo in extension hello world tutorial
sphinx-doc/sphinx pull request #10752
Opened 2022-08-04 15:48 UTC by dstansby

Subject: minor typo fix

### Feature or Bugfix

- Bugfix

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2022-08-04 16:41 UTC, jfbu reviewed
Alas, I don't know (not native) is one should write "is to call" in place of "is call"...

else I would merge this rightaway ;-) and avoid reaching  a disproportionate ratio "length+time of review divided by length+time of PR"...

2022-08-06 14:43 UTC, ProGamerGov commented
@jfbu Google docs' autocorrect feature is saying that their change is correct:

![it_call](https://user-images.githubusercontent.com/10626398/183253752-10c0cdd0-f635-4696-a83f-5cbf5710d21a.jpg)

2022-08-06 19:05 UTC, fluesvamp commented
> is to call

use the above infinitive form

2022-08-07 09:16 UTC, AA-Turner requested changes

2022-08-07 09:16 UTC, AA-Turner commented on doc/development/tutorials/helloworld.rst
> +The simplest thing you can do is call the :meth:`~Sphinx.add_directive` method,
```suggestion
The simplest thing you can do is to call the :meth:`~Sphinx.add_directive` method,
```

2022-08-07 13:13 UTC, jfbu commented
@AA-Turner I have observed transient errors with linkcheck recently, here it happened on Windows
```
FAILED tests/test_build_linkcheck.py::test_defaults - assert 7 == 6
FAILED tests/test_build_linkcheck.py::test_anchors_ignored - assert not "link...
= 2 failed, 1777 passed, 39 skipped, 5 xfailed, 28 xpassed, 10 warnings in 305.94s (0:05:05) =
ERROR: InvocationError for command 'D:\a\sphinx\sphinx\.tox\py\Scripts\python.EXE' -X dev -X warn_default_encoding -m pytest --durations 25 -vv (exited with code 1)
```
but I have seen it either on py37 or py310 Linux testing too.  Do you know the cause?

Anyway I will merge this because there is good chance testing will pass after merge (based on earlier experiences).

2022-08-07 13:14 UTC, jfbu approved these changes

2022-08-07 13:15 UTC, jfbu commented
Thanks @dstansby for contribution, merging!

2022-08-07 13:15 UTC, merged