add flake8-simplify SIM105 lint
sphinx-doc/sphinx pull request #10821
Opened 2022-09-13 10:57 UTC by danieleades

2022-09-29 18:08 UTC, AA-Turner commented on sphinx/events.py
> +            # not every object likes to be repr()'d (think
These two lines are in the wrong order?

A

2022-09-29 18:09 UTC, AA-Turner commented on sphinx/ext/autodoc/__init__.py
> +            with suppress(TypeError):  # avoid chaining exceptions, by putting nothing here
```suggestion
            with suppress(TypeError):  # avoid chaining exceptions
```

2022-09-29 18:12 UTC, AA-Turner commented on sphinx/ext/inheritance_diagram.py
>                          tooltip = '"%s"' % doc.replace('"', '\\"')
```suggestion
            doc = getattr(cls, '__doc__', '').strip().split("\n")[0].replace('"', '\\"')
            if doc:
                tooltip = f'"{doc}"'
```

2022-09-29 18:13 UTC, AA-Turner requested changes
Looks OK barring some notes:

2022-09-30 14:47 UTC, AA-Turner commented
@danieleades please avoid force pushing after review comments, limitations of GitHub's UI make it challenging to check what has changed compared to previous reviews. I always squash merge anyway so no issues on linear commit history.

A

2022-09-30 14:50 UTC, AA-Turner commented on sphinx/ext/inheritance_diagram.py
>                          tooltip = '"%s"' % doc.replace('"', '\\"')
This was marked as resolved but it stil seems to be the old version.

2022-10-18 06:10 UTC, danieleades commented on sphinx/ext/inheritance_diagram.py
>                          tooltip = '"%s"' % doc.replace('"', '\\"')
whoops! should be resolved now

2022-10-18 11:15 UTC, danieleades commented
rebased on master

2022-10-18 12:06 UTC, danieleades commented on sphinx/ext/inheritance_diagram.py
>                          tooltip = '"%s"' % doc.replace('"', '\\"')
doesn't appear to work-

```
    def recurse(cls: Any) -> None:
        if not show_builtins and cls in py_builtins:
            return
        if not private_bases and cls.__name__.startswith('_'):
            return
    
        nodename = self.class_name(cls, parts, aliases)
        fullname = self.class_name(cls, 0, aliases)
    
        # Use first line of docstring as tooltip, if available
        tooltip = None
>       doc = getattr(cls, '__doc__', '').strip().split("\n")[0].replace('"', '\\"')
E       AttributeError: 'NoneType' object has no attribute 'strip'
```

2023-07-28 00:16 UTC, AA-Turner commented
Closing out-of-date PR (feel free to update & re-open).

A

2023-07-28 00:16 UTC, closed without merging