option ref: support optional part with '[=value]'
sphinx-doc/sphinx pull request #10883
Opened 2022-09-29 09:05 UTC by marxin

This supports a commonly used format when it comes to optional argument: `-fauto-profile[=path]`, where `path` is optional part.

Extends: #10840

2022-09-30 11:08 UTC, marxin commented
What do you think @AA-Turner?

2022-10-02 11:37 UTC, AA-Turner requested changes
+1

2022-10-02 11:37 UTC, AA-Turner commented on sphinx/domains/std.py
> +            for needle in ('=', '[=', ' '):
```suggestion
            for needle in {'=', '[=', ' '}:
```

2022-10-02 11:37 UTC, AA-Turner commented on sphinx/domains/std.py
> +                    docname, labelid = self.progoptions.get((progname, target[:idx]), ('', ''))
More readable / 'pythonic', I think:
```suggestion
                if needle in target:
                    stem, _, _ = target.partition(needle)
                    docname, labelid = self.progoptions.get((progname, stem), ('', ''))
```

2022-10-02 11:37 UTC, AA-Turner commented on tests/roots/test-root/objects.txt
> +Reference the first option :option:`-mapi=secret` or :option:`-mapi[=xxx]`.
Can you test for the single space case too?

2022-10-02 12:23 UTC, AA-Turner commented
@marxin please don't force push, it makes review much more difficult after leaving comments.

A

2022-10-02 12:28 UTC, marxin commented
All right, so you prefer leaving there the "Suggested change" commits, right?

2022-10-02 14:46 UTC, AA-Turner commented
Yes, I squash merge on commit.

A

2022-10-02 14:47 UTC, AA-Turner approved these changes

2022-10-02 14:50 UTC, merged

2022-10-02 14:51 UTC, AA-Turner commented
Thanks!

A

2022-10-02 15:21 UTC, marxin commented
> Yes, I squash merge on commit.

Makes sense, will do that next time.

2022-10-02 15:21 UTC, marxin commented
> Thanks!

I thank you for a nice negotiation we made.