imgmath: Fix relative file path
sphinx-doc/sphinx pull request #10965
Opened 2022-11-10 10:29 UTC by jschueller

Closes #10944

2022-12-02 09:59 UTC, jschueller commented
@return42 and now ?

2022-12-02 10:05 UTC, return42 commented
Perfect .. works like a charm:

![grafik](https://user-images.githubusercontent.com/554536/205267586-5445391b-b9fb-4304-bb91-554bdd2ec610.png)

-----

IDK why the CI reports an [flake8 issue](https://github.com/sphinx-doc/sphinx/actions/runs/3600688863/jobs/6065620995#step:5:16) not related to this patch.

2022-12-02 10:08 UTC, jschueller commented
lets hope it can be merged soon

2022-12-02 10:20 UTC, jschueller commented
maybe @marxin or @jfbu ?

2023-01-04 11:33 UTC, jfbu commented
@jschueller I rebased your work on current master tip so that we have fresh linting.

@AA-Turner Should we consider fixing the #10944 as done here for 6.0.1 rather than 6.1.0?

2023-01-04 13:26 UTC, jfbu reviewed
In reviewing this I realized #10888 modified the returned path from ``render_math()`` to be absolute rather than relative.  But the docstring still says https://github.com/sphinx-doc/sphinx/blob/a9b0f2708b67a355c5f4969ccbbe9bd695518805/sphinx/ext/imgmath.py#L212
Could the #10888 have been achieved while keeping the behaviour of ``render_math()`` as formerly? And at same time avoid #10944? If not the docstring of ``render_math()`` should be updated.

2023-01-04 13:51 UTC, jfbu requested changes
Actually #10888 also modified the returned type of ``render_math()`` but did not update accordingly the docstring, which still says that it also returns the temporary filepath as well as the absolute path of destination image file. I see no mention of this change in CHANGES or in our document. I think it is important that it should be documented somewhere (I don't know to what extent or if at all ``render_math()`` is public API. Edit: surely not public API, but my point is that docstrings should be kept up-to-date with code...).

2023-01-04 14:03 UTC, jschueller commented
ok, I updated the docstring

2023-01-04 14:11 UTC, jfbu commented on sphinx/ext/imgmath.py
> +    Return the absolute filename to the built document and the "depth",
I think you meant to remove "to the built document" part as it referred not to the image file but to the html one.

2023-01-04 14:17 UTC, jschueller commented on sphinx/ext/imgmath.py
> +    Return the absolute filename to the built document and the "depth",
yes

2023-01-04 14:42 UTC, jfbu approved these changes
LGTM, thanks
ping @AA-Turner about perhaps adding some brief summary of overall architecture at start of module as the #10888 discussion was somewhat terse and it is hard to follow it a posteriori.  In  particular at 4cb857d5a65c07a49e1b8ece116d9880fae38152 the extension internal dynamics were somewhat refactored and it would be nice to have some brief overview in plain terms of what this all does.

2023-01-05 11:54 UTC, merged