Fix incompatible `entry_points` call
sphinx-doc/sphinx pull request #11270
Opened 2023-03-30 08:22 UTC by panhongtao07

Subject: Fix #10479 

### Feature or Bugfix
- Bugfix

### Purpose
- Fix the bug and import logic, `importlib` is considered before `importlib-metadata` in new python version
- Env: `importlib-metadata<3.6`, `importlib-metadata==1.7.0` in particular.

### Detail
- sphinx-build fails if `importlib-metadata<3.6` is installed, no matter what Python version is.
- it may also fail if Python version < 3.10.
- In these environment, the imported `entry_points` accepts no parameter, while `sphinx` calls it with `group`

2023-04-04 22:52 UTC, AA-Turner commented
Thank you for the PR @panhongtao07. From your description you mention `importlib-metadata` 1.7, but 
Sphinx requires `importlib-metadata>=4.8`, see:

https://github.com/sphinx-doc/sphinx/blob/609b2f2650dfea191e688ce6238ba567da551052/pyproject.toml#L73

Does the bug persist with version 4.8 or greater of `importlib-metadata`?

A

2023-04-05 12:37 UTC, panhongtao07 commented
It won't appear in `importlib-metadata` 3.6 or newer, which I noted before. However, `importlib-metadata>=4.8; python_version < '3.10'` means `importlib-metadata` dependency is only required in 3.9 or lower, but the code uses `importlib-metadata` before python's `importlib` module whatever.
Imagine in a environment with `importlib-metadata < 3.6; python_version >= '3.10'`, like `python3.10; importlib-metadata==1.7.0` , this pass the requirement, but fails in runtime. This is what I've faced. @AA-Turner 
https://github.com/sphinx-doc/sphinx/blob/4a3febb69a124300f1481fc33b44a5672f24e0fa/sphinx/theming.py#L13-L16

2023-04-05 23:05 UTC, AA-Turner requested changes
Does this combination work? In effect reversing the import order from current.

A

2023-04-05 23:05 UTC, AA-Turner commented on sphinx/theming.py
> +        from importlib.metadata import entry_points
```suggestion
    from importlib_metadata import entry_points
```

2023-04-05 23:05 UTC, AA-Turner commented on sphinx/theming.py
> +            theme_entry_points = {ep.name: ep for ep in _theme_entry_points}
```suggestion
        theme_entry_points = entry_points(group='sphinx.html_themes')
```

2023-04-06 06:40 UTC, panhongtao07 commented
Yes, it works. I agree to minimize the changes. I didn't notice the dependency when I first submitted the PR. I'll update it.

I've also found another issue, which is the same as #10479, but in a different place. I'll change it later. See:
https://github.com/sphinx-doc/sphinx/blob/4a3febb69a124300f1481fc33b44a5672f24e0fa/sphinx/registry.py#L18-L21

2023-04-06 06:44 UTC, panhongtao07 commented
There is a little question, `importlib_metadata` is only used in `sphinx/theming.py` and `sphinx/registry.py`. Should we change the dependency version?

2023-04-06 22:05 UTC, AA-Turner approved these changes

2023-04-06 22:06 UTC, merged

2023-04-06 22:06 UTC, AA-Turner commented
Thank you!

A