[linting] Add flake8 module-level-lint plugin.
sphinx-doc/sphinx pull request #12180
Opened 2024-03-22 18:28 UTC by jayaddison

### Feature or Bugfix
- Feature

### Purpose
- Add linting to check that module-level elements in our code adhere to PEP8 guidance.

### Detail
- Add the [`module-level-lint`](https://github.com/hanhwanglim/module-level-lint) `flake8` plugin to our `lint` extra-dependencies set.

### Relates
- Resolves #12179.

2024-03-22 18:31 UTC, picnixz commented
Personally, I think we should add it manually, incrementally. We don't want to keep flake8 or introduce new flake8 dependencies =/

2024-03-22 18:35 UTC, jayaddison commented
@picnixz that's reasonable, yep.  Perhaps this branch exists solely to find existing instances of this that we can fix.

2024-03-22 19:41 UTC, jayaddison commented
Hm.  Something isn't right here - commit a959887da00069ca1cd40db31506df61e6d18523 was supposed to fail.  I've moved the PR back into draft status.

2024-03-22 22:49 UTC, jayaddison commented
> Hm. Something isn't right here - commit [a959887](https://github.com/sphinx-doc/sphinx/commit/a959887da00069ca1cd40db31506df61e6d18523) was supposed to fail. I've moved the PR back into draft status.

That failed because, despite `module-level-lint` being [added](https://github.com/sphinx-doc/sphinx/commit/a959887da00069ca1cd40db31506df61e6d18523#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R85) to [the `[test]` extras in `pyproject.toml`](https://github.com/sphinx-doc/sphinx/blob/a959887da00069ca1cd40db31506df61e6d18523/pyproject.toml#L83-L92), our [GitHub Actions `lint.yml` workflow spec](https://github.com/sphinx-doc/sphinx/blob/b1548d0aa4f89cf7e808b34ba4203b32f0fc67d1/.github/workflows/lint.yml) _does not_ specify that those `[lint]` extras should be installed during the [`flake8` workflow job](https://github.com/sphinx-doc/sphinx/blob/b1548d0aa4f89cf7e808b34ba4203b32f0fc67d1/.github/workflows/lint.yml#L42-L56).  An install of [`flake8` is requested](https://github.com/sphinx-doc/sphinx/blob/b1548d0aa4f89cf7e808b34ba4203b32f0fc67d1/.github/workflows/lint.yml#L51-L54) (alongside/subsequent to an upgrade of `pip`), but `MLL004` is only reported by `flake8` when `module-level-lint` is installed and available as a plugin.

2024-03-23 00:12 UTC, picnixz commented on sphinx/theming.py
> +__all__ = 'Theme', 'HTMLThemeFactory'
```suggestion
__all__ = ('Theme', 'HTMLThemeFactory')
```

2024-03-23 00:12 UTC, picnixz commented on tests/test_extensions/ext_napoleon_pep526_data_google.py
> -module_level_var: int = 99
Keep it.

2024-03-23 00:13 UTC, picnixz requested changes

2024-03-23 00:13 UTC, picnixz commented on tests/test_extensions/ext_napoleon_pep526_data_numpy.py
> -module_level_var: int = 99
Keep it (remove this file from the lint)

2024-03-23 16:56 UTC, jayaddison commented
Hi @picnixz - I've removed the additional `flake8` plugin dependency here, so all of this is cleanup/refactor.  Please could you re-review?

2024-03-23 17:39 UTC, picnixz approved these changes

2024-03-23 17:55 UTC, jayaddison commented
Thank you!

2024-03-23 18:21 UTC, merged