Split `test` dependencies into `dev` and `test` dependencies.
sphinx-doc/sphinx pull request #12341
Opened 2024-05-01 07:39 UTC by picnixz

When (and if) [PEP 735](https://peps.python.org/pep-0735/) is accepted, we can probably simplify the deduplication of packages. It would at least be cleaner that way.

This does *not* resolve #12339 because we still need to change the `pyproject` and `tox.ini` of `sphinxcontrib-*` packages so that they use `sphinx[dev]` and not just `sphinx`.

2024-05-01 07:42 UTC, chrisjsewell requested changes

2024-05-01 07:42 UTC, chrisjsewell commented on pyproject.toml
> +dev = [
Maybe add a comment, that this extra is intended for use by users of sphinx.util.testing

2024-05-01 07:45 UTC, chrisjsewell commented
Thanks @picnixz, perhaps also there should be a try/except for the imports in sphinx.util.testing, that adds a message for users to use sphinx[dev]

2024-05-02 07:15 UTC, picnixz commented
> perhaps also there should be a try/except for the imports in sphinx.util.testing, that adds a message for users to use sphinx[dev]

I don't really like that. Instead, I should add some documentation for that. Otherwise, everytime a new dependency is added, a new import-guard should be added and it's an anti-pattern IMO. This also answers your first suggestion about adding a comment, and thus I'll improve the docs when I have more time.

2024-05-02 08:47 UTC, chrisjsewell commented
> I don't really like that. Instead, I should add some documentation for that. Otherwise, everytime a new dependency is added, a new import-guard should be added and it's an anti-pattern IMO. 

No, this is not an anti-pattern, and yes you should add it for every optional dependency; documentation will likely not help anyone that actually encounters this issue.

Literally the first package I looked for examples of handling extra dependencies, does exactly as I suggested: https://github.com/pandas-dev/pandas/blob/9110f7cdac46c69212512635a7fdc99963540c30/pandas/compat/_optional.py#L107

I you still believe it is an anti-pattern then please provide evidence to support this

2024-05-02 10:01 UTC, picnixz commented
> I you still believe it is an anti-pattern then please provide evidence to support this

Well, in your example, they are doing the other way around, namely they are updating their pyproject after updating the versions. But in our case, we are centralizing everything at the level of pyproject.toml. 

I would understand if we were to actually check dependencies at the code level but here we are leaving this task to package managers instead. As such I still believe it's not how we should do with our current dependency system.

In general, when you have dependencies like that, either the guard or the requirements files should be *automatically* generated from some specifications (it's like having a `configure` script which generates your Makefile accordingly). 

Now, it is more common to have `dev` dependencies for.. development and `test` dependencies for testing the package itself rather than testing whatever is dependent on. And I think people would first find out about the testing plugin from the docs rather than finding out inside the code (also, people are not meant to read the pyproject.toml file since the latter is not shipped). If our docs for the testing plugin were better, then they would know that they need to install dev dependencies (also `dev` dependencies are common for development in general: https://github.com/search?q=path%3Apyproject.toml+%22dev+%3D+%5B%22&type=code).

Finally, using `tox` would technically be sufficient if we had updated our other packages to actually use `dev` (before `test`) dependencies and they would likely never found out about that issue. I really don't want to duplicate checks at the code level when it's actually the purpose of the package manager. Otherwise, we should do it for the lint dependencies in TYPE_CHECKING blocks technically.

2024-05-07 03:39 UTC, chrisjsewell commented
> Finally, using `tox` would technically be sufficient if we had updated our other packages to actually use `dev`

I still feel this misses the point a little though 😅 
this is nothing to do with "our" packages, I don't care about anything within https://github.com/sphinx-doc, I'm talking about users who are using `sphinx.testing`
You updating `sphinxcontrib-*` doesn't fix all my packages in https://github.com/sphinx-extensions2 etc

> https://github.com/search?q=path%3Apyproject.toml+%22dev+%3D+%5B%22&type=code

But setting that aside...
the other thing to note here is that I would put good money, that all these `dev` extras are for **internal** development requirements, not **user-facing** ones (even though, as pep-0735 mentions, `extras` should really just be for user-facing dependencies).

So I feel `dev` is not a great name for this, especially when there is not even a comment to suggest this is for use by users.
Something like `sphinx[pytest]` would be better.

But look I won't hold this up, as there is not exactly practice (if only we had the wonderful features of rust 😉 https://doc.rust-lang.org/cargo/reference/features.html)

2024-05-07 09:42 UTC, chrisjsewell commented
> I'm always open to suggestions so I don't mind the debate!

😄 👍 

> because I really don't expect people to get into the pyproject.toml file

maybe just me, but I always read the `pyproject.toml`, and I actually added comments to the myst-parser one (well initially `setup.py`) specifically because people asked for it: https://github.com/executablebooks/MyST-Parser/issues/139#issuecomment-626181973

> it's another way to make plugins without having million of repositories outside your main source code

Well thats another discussion, the main way to do this in rust is: https://doc.rust-lang.org/cargo/reference/workspaces.html (see e.g. my use in https://github.com/markdown-it-rust/markdown-it-plugins.rs/tree/main/crates and https://github.com/sphinx-extensions2/sphinx-rust)

I would love to have this in Python, and feel it could be a really good fit for sphinx.

I've tried it out personally https://github.com/chrisjsewell/pymonorepo, but I think main stream adoption may hopefully come when rye matures: https://rye-up.com/guide/workspaces/

2024-05-07 19:52 UTC, chrisjsewell approved these changes
I would still suggest changing the name from dev, but won't block it for this

2024-10-05 21:15 UTC, closed without merging