Partial update for russian translation
sphinx-doc/sphinx pull request #12392
Opened 2024-05-24 13:12 UTC by dunmaksim

Subject: partial update for russian translation

2024-05-25 13:41 UTC, n-peugnet commented on sphinx/locale/ru/LC_MESSAGES/sphinx.po
> +msgstr "неправильная единица измерения. Пропускается."
Looks like a `%s` is missing there.

2024-05-26 20:38 UTC, dunmaksim commented on sphinx/locale/ru/LC_MESSAGES/sphinx.po
> +msgstr "неправильная единица измерения. Пропускается."
Thank you! Fixed.

2024-05-28 08:50 UTC, n-peugnet requested changes
I had some time to check on my computer and gettext discovered some more errors (sorry I should have started with this), could you please correct them?

```console
$ msgfmt --check -o ru/LC_MESSAGES/sphinx.mo ru/LC_MESSAGES/sphinx.po
ru/LC_MESSAGES/sphinx.po:226: 'msgid' and 'msgstr' entries do not both end with '\n'
ru/LC_MESSAGES/sphinx.po:951: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The string ends in the middle of a directive.
ru/LC_MESSAGES/sphinx.po:956: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The string ends in the middle of a directive.
ru/LC_MESSAGES/sphinx.po:966: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The string ends in the middle of a directive.
ru/LC_MESSAGES/sphinx.po:1135: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The string ends in the middle of a directive.
ru/LC_MESSAGES/sphinx.po:3393: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The string ends in the middle of a directive.
msgfmt: found 6 fatal errors
```

I added some hints in comments below.

You might also want to update the `Last-Translator` field of the header.

2024-05-28 08:50 UTC, n-peugnet commented on sphinx/locale/ru/LC_MESSAGES/sphinx.po
> +msgstr "Синтаксическая ошибка в файле конфигурации: %s\\n"
```suggestion
msgstr "Синтаксическая ошибка в файле конфигурации: %s\n"
```

2024-05-28 08:50 UTC, n-peugnet commented on sphinx/locale/ru/LC_MESSAGES/sphinx.po
> +msgstr "Файлы XML находятся в %(outdir)."
The final letter is important:

```suggestion
msgstr "Файлы XML находятся в %(outdir)s."
```

2024-05-30 12:07 UTC, dunmaksim commented on sphinx/locale/ru/LC_MESSAGES/sphinx.po
> +msgstr "Файлы XML находятся в %(outdir)."
Hello!

Thanks you for advices and additional checking! All (I hope) fixed :-)

2024-06-01 12:14 UTC, Reeseb1222 approved these changes

2024-06-01 12:14 UTC, Reeseb1222 commented on sphinx/locale/ru/LC_MESSAGES/sphinx.po
Rin

2024-06-01 22:15 UTC, Reeseb1222 commented
Run

2024-06-03 06:32 UTC, dunmaksim commented
Hello!
Me rebased branch for running checks. What I must do next?

2024-06-03 06:37 UTC, chrisjsewell commented
> Hello! Me rebased branch for running checks. What I must do next?

Heya, I believe we are just want to get in https://github.com/sphinx-doc/sphinx/pull/12392 first

2024-06-04 09:27 UTC, n-peugnet approved these changes
Looks good to me.

I just noticed that there is a list of translators in the topmost comment of the file, you might also want to add yourself there @dunmaksim.

2024-06-04 15:02 UTC, dunmaksim commented
> Looks good to me.
> 
> I just noticed that there is a list of translators in the topmost comment of the file, you might also want to add yourself there @dunmaksim.

Maybe later.

2024-06-15 17:22 UTC, rffontenelle commented
Meeging this won't be replaced by the Russian translations from a Transifex or create a async between what is translated in here and in there?

2024-06-16 18:25 UTC, n-peugnet commented
> Meeging this won't be replaced by the Russian translations from a Transifex or create a async between what is translated in here and in there?

I assumed that Transifex worked somewhat similarly to Weblate and always used to files from the git repo as the source, but it is not the case. Currently the only file pushed to Transifex is the source (the sphinx.pot template) and not the *.po files:

https://github.com/sphinx-doc/sphinx/blob/568e26c797b9152bb9b2443c926aec314f0652de/.github/workflows/transifex.yml#L35

But we could also push the translation files using the `-t/--translation` flag as explained in [transifex-cli docs](https://github.com/transifex/cli?tab=readme-ov-file#pushing-files-to-transifex):

> By default, the client will push the source file (the file that's being pointed to by the `source_file` configuration option from `tx add`). If you use the `-t/--translation` flag, `tx push` will push translation files. This may be desirable if, for example, you previously pulled translation files with the `--mode translator` option, translated using an offline translation tool and now you want to push your work to Transifex, or if you are migrating from
another localization management service to Transifex. If you use both the `-t` _and_ the `-s/--source` flags, then you will push both the source file and the translation files.

2024-06-16 18:38 UTC, rffontenelle commented
Indeed. If merging, I'd recommend immediately pushing it to Transifex to not lose it in the next transifex.yml workflow run after a Russian transltion update in the Transifex.

For what is worth, any translator member of the translation team can [upload the PO file](https://help.transifex.com/en/articles/6318456-uploading-translations) with changes to the Sphinx resource in Transifex.

2024-06-18 11:17 UTC, dunmaksim commented
Hello! I joined to Transifex project Sphinx and make changes in russian translation [here](https://app.transifex.com/sphinx-doc/sphinx-1/translate/#ru/sphinx-pot/112142459).

2024-06-18 11:17 UTC, closed without merging