Style suggestions for sphinx13
sphinx-doc/sphinx pull request #12546
Opened 2024-07-11 12:35 UTC by timhoffm

As a suggestion:

- increase paragraph line-height to 1.5 to give text a bit more room to breathe. 1.5 is a common choice in web page typography; e.g. rtd-sphinx-theme, furo and GitHub use this (pydata sphinx theme goes even to 1.65).
- Don't shrink the text in admonitions. They are equally important and thus should have the same size as regular paragraphs.
- Adapt the border color for all warning/error like admonitions. Warnings had a fixed color that did not fit well to the new admonition style.

2024-07-11 12:51 UTC, chrisjsewell commented
> Don't shrink the text in admonitions. They are equally important and thus should have the same size as regular paragraphs. For reference, e.g. pydata-sphinx-theme and rtd-sphinx-theme do this.

For counter-reference though 😅 : https://pradyunsg.me/furo/kitchen-sink/admonitions/, the text is smaller 

They are meant to be "asides" semantically, so I don't know if I agree that they are "equally important" (and I think in general furo is nicer looking and maybe better to follow)

If nothing else, the "feature" admonitions on the landing page should still be smaller.

The other changes I think are good 👍

2024-07-11 12:52 UTC, chrisjsewell requested changes
see comment

2024-07-11 13:10 UTC, timhoffm commented
Re: Font size of admonitions:

I believe we're all not experts on typography. I therefore checked what "big sites" do, assuming they have thought about these things.

> [!NOTE]  
> GitHub does not reduce the font size in admontions.

The same holds for [Microsoft Azure docs](https://learn.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops).

Based on that, I say same-size is likely better, but I don't have a strong opinion.

2024-07-11 13:21 UTC, timhoffm commented
> If nothing else, the "feature" admonitions on the landing page should still be smaller.

Ok, kept them in the smaller font.

2024-07-14 05:54 UTC, chrisjsewell commented on doc/_themes/sphinx13/static/sphinx13.css
> +    font-size: 0.9em;
```suggestion
```

2024-07-14 06:01 UTC, chrisjsewell approved these changes

2024-07-14 06:02 UTC, merged

2024-07-14 06:03 UTC, chrisjsewell commented
I removed the increase in admonition text size for now, since I really do feel it makes the pages with many admonitions less readable