singlehtml: deprecate 'fix_refuris' helper function
sphinx-doc/sphinx pull request #13037
Opened 2024-10-18 13:32 UTC by jayaddison

### Feature or Bugfix
- Refactoring

### Purpose
- Deprecates a `singlehtml` builder helper method that I believe should be unused since #11970 and #12551 are in place, but that might, perhaps, be re-used by other functionality (extensions / codebases).

### Detail
- Deprecates the `sphinx.builders.singlehtml.SingleFileHTMLBuilder.fix_refuris` method, and adds a warning noting that it's planned for removal in Sphinx 9 (the next major version).

### Relates
- Follow-up to #11970 and #12551.

2024-10-18 20:02 UTC, AA-Turner requested changes
Remember to add new deprecations to `doc/extdev/deprecated.rst`.

A

2024-10-25 18:21 UTC, jayaddison commented
Although I'm fairly keen to merge this, and think it should be safe -- maybe I'll take one more self-review pass (and/or try some builds of external `singlehtml` projects) on it next week before re-requesting approval/merge.

2024-11-13 22:24 UTC, AA-Turner reviewed
Our deprecation policy calls for two major releases. Any reason to expidite this one?

A

2024-11-13 22:24 UTC, AA-Turner commented on CHANGES.rst
> +  Patch by James Addison.
```suggestion

* #13037: Deprecate the ``SingleHTMLBuilder.fix_refuris`` method.
  Patch by James Addison.
```

2024-11-13 22:24 UTC, AA-Turner commented on doc/extdev/deprecated.rst
> +     - 9.0
```suggestion
     - 10.0
```

2024-11-13 22:24 UTC, AA-Turner commented on sphinx/builders/singlehtml.py
> +from sphinx.deprecation import RemovedInNextVersionWarning
```suggestion
from sphinx.deprecation import RemovedInSphinx10Warning
```

2024-11-13 22:24 UTC, AA-Turner commented on sphinx/builders/singlehtml.py
> +        warnings.warn(deprecation_msg, RemovedInNextVersionWarning, stacklevel=2)
```suggestion
        deprecation_msg = (
            "The 'SingleFileHTMLBuilder.fix_refuris' method is no longer used "
            'within the builder and is planned for removal in Sphinx 10. '
            'Please report malformed URIs generated by the Sphinx singlehtml '
            'builder as bugreports.'
        )
        warnings.warn(deprecation_msg, RemovedInSphinx10Warning, stacklevel=2)
```

2024-11-13 22:55 UTC, jayaddison commented
> Our deprecation policy calls for two major releases. Any reason to expidite this one?

Nope, this can wait until Sphinx 10 - oddly I think I configured that originally; I can't remember why I reset that to Sphinx 9.

2024-11-13 23:14 UTC, AA-Turner approved these changes

2024-11-13 23:15 UTC, merged