Add the default value of `napoleon_attr_annotations`
sphinx-doc/sphinx pull request #13094
Opened 2024-11-01 03:44 UTC by Snoopy1866

Subject: Add the default value of `napoleon_attr_annotations`

### Feature or Bugfix

- Feature

### Purpose
Add the default value of `napoleon_attr_annotations`

### Detail
None

### Relates
None

2024-11-01 12:35 UTC, AA-Turner requested changes
Please use the new type and default options to confval

2024-11-05 02:50 UTC, Snoopy1866 commented on doc/usage/extensions/napoleon.rst
> +   :type: `Optional[Sequence[str | Sequence[str, str]]]`
Is it necessary to use `Sequence` instead of `list` here? And should I use the `|`, or nested `Optional`?

2024-11-05 02:54 UTC, Snoopy1866 commented on doc/usage/extensions/napoleon.rst
> +   :type: `bool`
Using backticks can make text appear more stylized. Should we apply them in other contexts as well?

2024-11-05 03:15 UTC, Snoopy1866 commented on doc/usage/extensions/napoleon.rst
> +   :type: `bool`
Sad, github action tell me `"default role used (hint: for inline literals, use double backticks) (default-role)"`. But when I use double backticks, the inline literals looks not good as I want.

Though I see the early documentation used double backticks also.

2024-11-05 03:17 UTC, Snoopy1866 commented on doc/usage/extensions/napoleon.rst
> +   :type: `bool`
Already update to double backticks.

2024-11-05 03:24 UTC, Snoopy1866 commented
I have changed the PR title since I have update not only the docs of `napoleon_attr_annotations` option but also all options of `sphinx.ext.napoleon`, the former title is not suitable I think.

However, I have not modified the branch name, because it will close this PR.

2024-11-05 12:10 UTC, Snoopy1866 commented on doc/usage/extensions/napoleon.rst
> +   :type: `bool`
Inspired by the below code, I add the `code-py` interpreted text role.
https://github.com/sphinx-doc/sphinx/blob/230ccf2a44d750f5d6c5542f970f48ffe0cbce1e/doc/usage/configuration.rst?plain=1#L2917-L2919

2024-11-05 12:11 UTC, Snoopy1866 commented
Inspired by the below code, I add the `code-py` interpreted text role.
https://github.com/sphinx-doc/sphinx/blob/230ccf2a44d750f5d6c5542f970f48ffe0cbce1e/doc/usage/configuration.rst?plain=1#L2917-L2919

2024-11-05 12:15 UTC, Snoopy1866 commented
`readthedocs` build succeeded, while github action build failed. It looks confusing.

2025-01-05 11:04 UTC, AA-Turner approved these changes

2025-01-05 11:05 UTC, merged