Allow reserved pages in toctree
sphinx-doc/sphinx pull request #2849
Opened 2016-08-13 03:01 UTC by avylove

I was looking to add the general index to a toctree and it didn't seem like that was possible, so I created this patch to allow it.

Basically this allows the special document names (genindex, modindex, search) to be used as page names in a toctree either with their default titles or custom ones.

```reStructuredText
.. toctree::

   normalpage
   genindex
   Modules <modindex>
   search
```

It seems I'm not the only one who was looking for this:

http://stackoverflow.com/questions/36235578/how-can-i-include-the-genindex-in-a-sphinx-toc
http://stackoverflow.com/questions/25243482/how-to-add-sphinx-generated-index-to-the-sidebar-when-using-read-the-docs-theme

2022-02-22 00:02 UTC, Blendify commented on doc/markup/toctree.rst
> +   .. versionchanged:: 1.5
Should be 4.5

2022-02-25 16:41 UTC, avylove commented
Synced upstream changes and updated code as it was originally from 5.5 years ago. Also updated tests.

2022-02-26 04:44 UTC, Blendify approved these changes

2022-05-23 03:12 UTC, AA-Turner requested changes
Please could you rebase on `5.x` and re-target the PR to that branch?

A

2022-05-23 03:12 UTC, AA-Turner commented on doc/usage/restructuredtext/directives.rst
> +   .. versionchanged:: 4.5
```suggestion
   .. versionchanged:: 5.1
```

If you re-target the PR to `5.x`

2022-05-23 03:12 UTC, AA-Turner commented on sphinx/directives/other.py
> +                if url_re.match(ref) or ref in ('self', 'genindex', 'modindex', 'search'):
I'd prefer if this 4-tuple was factored out somewhere as it is used more than once, but there aren't any great locations that come to mind.

2022-05-23 03:12 UTC, AA-Turner commented on doc/usage/restructuredtext/directives.rst
> +   ``search`` can also be used.
Perhaps expand this, as the special names can also be used indirectly, as you illustrate in the test.

2022-10-05 17:10 UTC, AA-Turner commented
Closed by #10673

2022-10-05 17:10 UTC, closed without merging