Fix doc/Makefile that can't build man because of doc/man folder exists
sphinx-doc/sphinx pull request #2936
Opened 2016-09-02 06:26 UTC by shibukawa

2016-09-05 02:28 UTC, tk0miya commented
Hmm... this is also reproduced at new sphinx project.
```
$ sphinx-quickstart test
$ cd test
$ touch html
$ make html
make: `html' is up to date.
```
I believe this is a bug of new "make mode".

@shimizukawa We have to fix this until next release. Or I will change the default make mode to old one.

2016-09-05 04:02 UTC, tk0miya commented
The manual of GNU make says:

>The implicit rule search (see Implicit Rules) is skipped for .PHONY targets. This is why declaring a target as .PHONY is good for performance, even if you are not worried about the actual file existing.

https://www.gnu.org/software/make/manual/make.html#Phony-Targets

Because of that, anything pattern (`%`) could not work for phony targets. So `make` command could not invoke sphinx if there are files or directories having same name with builders (like `html`, `man` and so on).

2016-09-05 04:43 UTC, shimizukawa commented
@birkenfeld do you have any opinion? or any idea to fix the problem of make-mode?

2016-10-11 12:27 UTC, tk0miya commented
I posted #3029 for the default mode of quickstart.

About this issue, both merging or rejecting is ok for me.
I think sphinx/doc is not a manual. So nobody really needs this change.

2016-10-12 11:14 UTC, shimizukawa commented
+1 for merging

2016-10-12 11:39 UTC, tk0miya commented
Okay. @shibukawa could you rebase this please? Then I will merge right away.

2016-10-13 08:16 UTC, shibukawa commented
rebased

2016-10-13 08:29 UTC, tk0miya requested changes

2016-10-13 08:29 UTC, tk0miya commented on CHANGES
> +* #2936: Fix doc/Makefile that can't build man because doc/man exists
Thank you for rebasing. But this entry should move to 1.4.9

2016-10-14 02:55 UTC, tk0miya approved these changes

2016-10-14 02:55 UTC, merged

2016-10-14 02:56 UTC, tk0miya commented
Merged. Thank you always!

2016-10-14 16:50 UTC, jfbu commented
I am sure I do not understand exactly what is at stake but can't you just include one giant single

    .PHONY: help man clean html dirhtml epub <etc>...

into  the ``Makefile.new_t`` template with all builders known to Sphinx ?

2016-10-14 16:58 UTC, jfbu commented
sorry I get it now. silly question.

2016-10-14 17:18 UTC, jfbu commented
would something like this make senses

```
TARGETSWITHBUILDERNAMES = help clean man html latex

.PHONY: $(TARGETSWITHBUILDERNAMES)

$(TARGETSWITHBUILDERNAMES):
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).

%:
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

2016-10-15 10:41 UTC, tk0miya commented
The make-mode was introduced not to maintainance Makefile even if we added new builder to Sphinx.
But your example has a list like `TARGETSWITHBUILDERNAMES`.

I know it is much simple thank current one. but it could not replace make-mode.