Sphinx apidoc does not process PEP-0420 implicit namespaces
sphinx-doc/sphinx pull request #2951
Opened 2016-09-12 22:18 UTC by arcivanov

fixes #2949, connected to #2949

2016-09-14 04:59 UTC, arcivanov commented
@tk0miya could you also weigh-in here?

2016-09-14 07:49 UTC, tk0miya commented
I'll take a look later :-) Please wait a bit

2016-09-15 12:09 UTC, tk0miya commented on sphinx/apidoc.py
> +    parser.add_option('--pep-420', action='store_true',
I prefer to more explicit naming :-)
How about `--implicit-namespace`?

2016-09-15 12:09 UTC, tk0miya commented on sphinx/apidoc.py
> +    parser.add_option('--pep-420', action='store_true',
Could you update `doc/invocation.rst` about this option?

2016-09-15 12:09 UTC, tk0miya requested changes
LGTM with nits

2016-09-15 12:10 UTC, tk0miya commented
In addition, please add CHANGES entry.

2016-09-15 13:15 UTC, arcivanov commented on sphinx/apidoc.py
> +    parser.add_option('--pep-420', action='store_true',
Rgr that.

2016-09-15 15:42 UTC, arcivanov commented on sphinx/apidoc.py
> +    parser.add_option('--pep-420', action='store_true',
Done.

2016-09-15 15:42 UTC, arcivanov commented on sphinx/apidoc.py
> +    parser.add_option('--pep-420', action='store_true',
Done.

2016-09-15 15:42 UTC, arcivanov commented
@tk0miya  Ready for final review and commit.

2016-09-15 15:45 UTC, tk0miya commented on doc/invocation.rst
> +   Python 3.3 introduced PEP-0420 implicit namespaces that allow module path
It would be nice if using `:pep:` role. hyperlinks will help readers.

2016-09-15 15:46 UTC, tk0miya approved these changes
LGTM!

2016-09-15 15:47 UTC, arcivanov commented on doc/invocation.rst
> +   Python 3.3 introduced PEP-0420 implicit namespaces that allow module path
One sec, will fix.

2016-09-15 15:47 UTC, tk0miya commented
@shimizukawa do you have any comments?
If not, I will merge this soon (maybe in this weekend).

2016-09-15 15:51 UTC, arcivanov commented on doc/invocation.rst
> +   Python 3.3 introduced PEP-0420 implicit namespaces that allow module path
done

2016-09-15 15:56 UTC, tk0miya commented on doc/invocation.rst
> +   Python 3.3 introduced PEP-0420 implicit namespaces that allow module path
Thanks!

2016-09-17 05:49 UTC, merged

2016-09-17 05:49 UTC, tk0miya commented
Merged.
Thank you for contribution!