allow search hits in body text that are in title of other doc #2891
sphinx-doc/sphinx pull request #2971
Opened 2016-09-21 22:21 UTC by TimKam

2016-09-29 06:06 UTC, tk0miya requested changes
LGTM wit nits

2016-09-29 06:06 UTC, tk0miya commented on sphinx/search/__init__.py
> +                              and docname in self._title_mapping.get(stemmed_word)
I think `docname in self._title.mapping.get(stemmed_word, [])` is a bit simple.

2016-09-29 06:06 UTC, tk0miya commented on sphinx/themes/basic/static/searchtools.js_t
> +      //fileMap[file] = $.unique(fileMap[file]);
It seems this is not needed.

2016-09-29 06:07 UTC, tk0miya commented
@shibukawa Do you have any opinion about this case?
In detail, please refer #2891.

2016-09-29 16:11 UTC, TimKam commented
@tk0miya Thanks for the feedback! Worked it in.

2016-10-04 03:54 UTC, tk0miya approved these changes
Confirmed. Thank you for updating!

2016-10-06 02:12 UTC, tk0miya commented
If no comments until this weekend, I will merge this.

2016-10-10 15:42 UTC, merged

2016-10-10 15:44 UTC, tk0miya commented
Merged.
Thank you for contribution!