Add to new default latex settings
sphinx-doc/sphinx pull request #3083
Opened 2016-10-23 12:37 UTC by jfbu

This is based on #3064, to be considered after #3064 is merged. (currently #3064 Travis-CI fails because fontspec of Ubuntu Precise is not luatex aware).

I will rebase this branch depending on future evolutions of #3064. Making it a PR here for easier reviewing.

2016-10-25 17:36 UTC, tk0miya approved these changes
LGTM with nits

2016-10-25 17:36 UTC, tk0miya commented on sphinx/writers/latex.py
> +            self.elements['classoptions'] += ',' + self.babel.get_language()
Question: polyglossia also refers the language specification on `\documentclass`?

2016-10-25 17:36 UTC, tk0miya commented on sphinx/writers/latex.py
> +            if builder.config.language:
The `\setmainlanguage` is called only if users set up `language` variable. Is this intended?
If the function should be always called, this line should be removed.

2016-10-25 18:21 UTC, jfbu commented on sphinx/writers/latex.py
> +            self.elements['classoptions'] += ',' + self.babel.get_language()
I don't know (will check): but other packages may use this option. A documentclass option is presented to all packages and packages like "datetime/datetime2" use it.

2016-10-25 18:23 UTC, jfbu commented on sphinx/writers/latex.py
> +            if builder.config.language:
I copied this bit from former babel branch. You mean `\setmainlanguage{english}` should be issued if `language` variable is not set by user ?

2016-10-26 02:34 UTC, tk0miya commented on sphinx/writers/latex.py
> +            self.elements['classoptions'] += ',' + self.babel.get_language()
If so, is it better to move this line to outside of the if-block?
The language option is defined only if babel or polyglossia is enabled. When both are disabled, the option is not defined (ex. Japanese docs).

Anyway, I understand this option is worthy. so you don't need to check how polygolossia works.

2016-10-26 03:26 UTC, tk0miya commented on sphinx/writers/latex.py
> +            if builder.config.language:
Yes. For the babel package, latex writer always give a language option through documentclass even if `language` is not set. But, for the polyglossia, no `\setmainglanguage` is given if `language` is not set.

Of course, it's okay if polyglossia works fine without no main-language.

2016-10-26 10:54 UTC, jfbu commented on sphinx/writers/latex.py
> +            self.elements['classoptions'] += ',' + self.babel.get_language()
from short look at current polyglossia code, it does not do anything with document class options; furthermore it does not accept the language as package options (but older polyglossia) did. It is needed to use `\setmainlanguage` or `\setdefaultlanguage` which are synonyms.

If I understand correctly moving

     self.elements['classoptions'] += ',' + self.babel.get_language()

to before conditional will simply result in an added ``,`` in class options if neither babel nor polyglossia is enabled ? It is ok for LaTeX to  have ``,,`` in the document class options, so yes I think it is better to move this line before the if-block.

2016-10-26 10:57 UTC, jfbu commented on sphinx/writers/latex.py
> +            if builder.config.language:
I checked the polyglossia doc. The two `\setdefaultlanguage` and `\setmainlanguage` are the same macro. It is needed to use it for polyglossia.

2016-10-26 10:59 UTC, jfbu commented on sphinx/writers/latex.py
> +            if builder.config.language:
Thus, I conclude that if `language` variable is not explicitely set by user, then `\setmainlanguage{english}`  should be used. Does not `self.babel.get_language()` return the string ``'english'`` by default ?

2016-10-26 11:04 UTC, jfbu commented on sphinx/writers/latex.py
> +            if builder.config.language:
ah sorry anyhow it is not executed due to surrounding `if builder.config.language:`. I will add commit to address this.

2016-10-26 11:46 UTC, jfbu commented on sphinx/writers/latex.py
> +                    if self.elements['babel']:
I added this conditional by error, I will remove it (polyglossia could be ok with Japanese, but anyhow Japanese documents do not use xelatex by default)

2016-10-27 01:23 UTC, tk0miya commented on sphinx/writers/latex.py
> +            if builder.config.language:
>Does not self.babel.get_language() return the string 'english' by default ?

Yes, `self.babel.get_language()` returns 'english' by default and for invalid languages.

2016-11-03 16:52 UTC, jfbu commented
This looks OK to me. Perhaps the organization of conditionals about language settings is not the most condensed, but it is clear enough.

memo: We can not use package "newunicodechar" whose v1.1 requires TL2013 (and I could not find info for 1.0). Else ``\\newunicodechar{ }{~}`` (the space being `U+00A0`) would be less scary than the ``\\catcode`^^^^00a0\\active ... etc...``.

2016-11-04 11:08 UTC, tk0miya requested changes

2016-11-04 11:08 UTC, tk0miya commented on sphinx/writers/latex.py
> +                self.elements['multilingual'] = self.elements['babel']
Babel would be used when unsupported language is specified even if you use xelatex.

2016-11-04 11:13 UTC, tk0miya commented
To be simple, what about the following code?
```
        # move fncychap setting to outside of babel settings. they are not related.
        if builder.config.language:
            # use Sonny style if any language specified
            self.elements['fncychap'] = '\\usepackage[Sonny]{fncychap}'

        # setup multilingual package
        self.babel = ExtBabel(builder.config.language)
        if builder.config.language and self.babel.is_supported_language():
              # emit warning if specified language is invalid
              # (only emitting, nothing changed to processing)
              self.builder.warn('no Babel option known for language %r' %
                                builder.config.language)

        # simply use babel.get_language() always.
        # get_langauge() returns collect language-name even if language is invalid or empty (then returns “english”).
        self.elements['classoptions'] += ',' + self.babel.get_language()

        # set up multilingual module...
        if self.elements['polyglossia']:
            self.elements['babel'] = ''  # disable babel forcely
            self.elements['multilingual'] = “%s\n\\setmainlanguage{%s}” % (self.elements['polyglossia’], self.babel.get_language())
        elif self.elements['babel']:
            self.elements['multilingual'] = self.elements['babel']
            if builder.config.language:
                self.elements['shorthandoff'] = self.babel.get_shorthandoff()

                # Times fonts don't work with Cyrillic languages
                if self.babel.uses_cyrillic():
                    self.elements['fontpkg'] = ''

                # pTeX (Japanese TeX) for support
                if builder.config.language == 'ja':
                    ...
```

2016-11-04 12:32 UTC, jfbu commented on sphinx/writers/latex.py
> +                self.elements['multilingual'] = self.elements['babel']
yes,  sorry about oversight

the problem is that I am a bit confused about Babel (python) vs babel/polyglossia (latex). We have three sets of languages + dialects, those handled by Babel (python), those acceptable to babel (latex) and those acceptable to polyglossia (latex). The code in latex.py seems to worry only about the Babel (python) module.

2016-11-04 12:58 UTC, jfbu commented
+1 @tk0miya incorporated your code, I am off for next four hours

2016-11-04 13:51 UTC, tk0miya approved these changes
LGTM with nits.
Please merge this after clean up comments.

2016-11-04 13:51 UTC, tk0miya commented on sphinx/writers/latex.py
> +        # move fncychap setting to outside of babel settings (they are unrelated)
oops, this comment is only made to describe my idea to you.
this does not describe how the code works.

2016-11-04 20:59 UTC, jfbu commented
@tk0miya thanks a lot. Merging now after having rebased the refactoring of multilanguage setup.

2016-11-04 20:59 UTC, merged