fix #3150
sphinx-doc/sphinx pull request #3154
Opened 2016-11-16 03:02 UTC by shibukawa

2016-11-17 12:42 UTC, tk0miya requested changes

2016-11-17 12:42 UTC, tk0miya commented on utils/compat_regexp_generator.py
> +
Could you add a comment like "DO NOT EDIT. This is generated by compat_regexp_generator.py."?

2016-11-17 12:42 UTC, tk0miya commented on utils/compat_regexp_generator.py
> +# -*- coding: utf-8 -*-
Should this script be installed? What about move this into `utils` directory of root directory?

2016-11-17 12:42 UTC, tk0miya commented on utils/compat_regexp_generator.py
> +# -*- coding: utf-8 -*-
`compat_regexp` is very vague for me.
What about `jssplitter_generator`?

2016-11-17 12:42 UTC, tk0miya commented
LGTM with nits

2016-11-18 01:05 UTC, shibukawa commented on utils/compat_regexp_generator.py
> +# -*- coding: utf-8 -*-
done

2016-11-18 01:05 UTC, shibukawa commented on utils/compat_regexp_generator.py
> +
done

2016-11-18 01:23 UTC, tk0miya approved these changes

2016-11-18 01:24 UTC, tk0miya commented
LGTM!

2016-11-18 17:12 UTC, TimKam commented on CHANGES
> +* #3150: Fix query word splitter in JavaScript. It behaves as same as Python's regular expressio.
"It behaves the same as Python's regular expression."

2016-11-18 17:20 UTC, TimKam commented on utils/jssplitter_generator.py
> +
It'd be great to add a test with umlauts here, like:

```
console.log("test splitting umlauts. It should keep umlauts.")
assert.deepEqual(['Löschen', 'Prüfung', 'Abändern', 'ærlig', 'spørsmål'], splitQuery('Löschen Prüfung Abändern ærlig spørsmål'));
console.log('   ... ok\\n')
```

2016-11-19 01:09 UTC, shimizukawa commented
LGTM!

2016-11-19 05:11 UTC, tk0miya commented
Okay, I will merge this tomorrow.
@shibukawa could you update this PR until tomorrow?
If impossible, I will update CHANGES entry and please send us another PR to update test for umlauts.

2016-11-19 14:38 UTC, shibukawa commented on utils/jssplitter_generator.py
> +
I added. Thank you for your feedback.

2016-11-19 15:04 UTC, merged

2016-11-19 15:05 UTC, tk0miya commented
Merged. Thank you always!