Add possibility to specify a config file.
sphinx-doc/sphinx pull request #3166
Opened 2016-11-20 23:50 UTC by rweickelt

This pull request addresses #3133 and enhances the -c command line option. "-c" may now either specify a directory or point to a config file. In case of a directory, it is assumed to contain a conf.py file. The behavior of -c remains fully backwards compatible.

The commit contains the (small) functional changes in the command line parser and many changes in the documentation. Most occurrences of :file:`conf.py` have been replaced by a link to the configuration file
documentation. I've also simplified some sentences mentioning the config file whenever it seemed appropriate.

Please let me know what is needed in order to get this patch accepted.

2016-11-22 17:40 UTC, tk0miya requested changes
You also have to update the `TestApp` class in `tests/utils.py`.

2016-11-22 17:40 UTC, tk0miya commented on doc/ext/ifconfig.rst
> +   :doc:`configuration file</config>` are available).
Could you add a space before link target?
And more, could you remove the slash at the top from link target?

2016-11-22 17:40 UTC, tk0miya commented on doc/latex.rst
> +     the :doc:`config file <config>` only the prefixed names are defined.
"configuration file"?

2016-11-22 17:40 UTC, tk0miya commented on doc/latex.rst
> +    # inside the config file
"configuration file"?

2016-11-22 17:40 UTC, tk0miya commented on doc/markup/misc.rst
> +   within the configuration file, see :ref:`here <conf-tags>`) are true.  Boolean
This is not linked. Intended?

2016-11-22 17:40 UTC, tk0miya commented on sphinx/application.py
> +                 conffilename, confoverrides=None, status=sys.stdout,
This brings incompatibility for initialization. It's not acceptable.
Could you give a default value to `conffilename`?

And more, could you move the parameter to the end of the argument list?
Some application which Sphinx uses as library depends on the order of arguments.
(ex.`sphinx/setup_command.py`, `tests/utils.py`)

2016-11-22 17:40 UTC, tk0miya commented on sphinx/cmdline.py
> +        srcdir = path.abspath(args[0])
Please use naked `abspath()` instead.
It equals `sphinx.util.ospath.abspath()`, not `os.path.abspath()`.

2016-11-22 17:40 UTC, tk0miya commented on sphinx/cmdline.py
> +                confdir = srcdir
If `opts.noconfig` is specified, `confdir` should have None value.
Are you tested the option at local?

(unfortunately, there are no testcases for `sphinx.cmdline`. So we have to test it carefully)

2016-11-22 17:40 UTC, tk0miya commented on sphinx/cmdline.py
> +                conffilename = 'conf.py'
Please define constant like `sphinx.application.CONFIG_FILENAME`.

2016-11-22 17:45 UTC, tk0miya commented
BTW, did you see my comment on https://github.com/sphinx-doc/sphinx/issues/3133#issuecomment-260097278 ?

I feel this change brings complexity to the option parsing.
I would like to keep the code simple. So it would be nice if no update is needed.

2016-11-22 17:50 UTC, tk0miya commented on sphinx/cmdline.py
> +        elif opts.confpath:
How about this?
```
else:
    if opts.confpath:
        confpath = abspath(opts.confpath)
    else:
        # Could be replaced by auto-detection
        confpath = srcdir

    if path.isdir(confpath):
        ...
```

2016-11-22 17:53 UTC, tk0miya commented
In addition, please take a look errors on Travis.
It seems flake8 detected some errors.

2016-11-22 21:21 UTC, rweickelt commented
@tk0miya San, thank you very much for the extensive code review. Highly appreciated. I've already noticed the errors in Travis, but didn't have the time yet, to investigate. I'll address your remarks, but it might take some days.

2016-11-23 07:39 UTC, shimizukawa commented
+0 for improved command-line option `-c`.
-1 for implementation: new code in cmdline.py is too complex to maintain.

2017-04-15 07:21 UTC, tk0miya commented
Finally, I and @shimizukawa determined to close this PR because this brings complexity to our code.
Thank you for your proposal.

2017-04-15 07:21 UTC, closed without merging