Implement a py-classindex and py-funindex additionally to the default py-modindex
sphinx-doc/sphinx pull request #3278
Opened 2016-12-24 01:09 UTC by Naereen

Subject: Implement a `py-classindex` and `py-funindex` additionally to the default `py-modindex`.

### Feature
- Add two index pages for the Python domain: `classindex` and `funindex`
- Suggestion to fix #3178. Not fully mature yet, but it works already

### Purpose
- Provides a cleaner and fully static solution to [this question](https://stackoverflow.com/questions/12150491/toc-list-with-all-classes-generated-by-automodule-in-sphinx-docs)

### Detail
- The code in `sphinx.domains.python.PythonClassIndex` and `sphinx.domains.python.PythonFunIndex` is very similar  to `sphinx.domains.python.PythonModuleIndex`
- So the look of the resulting index pages are very similar, but they do the job I think (see below for screenshots in the comments)
- I added the new feature in the `CHANGES` file
- It adds two config value, `classindex_common_prefix` and `funindex_common_prefix` that are exactly like `modindex_common_prefix`, and are documented and initialized similarly
- I updated manually the French ``.po`` file, but cannot do the same for other languages

### Other things to do ?
- Add a test ?
- Add the label links to ``classindex`` and ``funindex`` after the label link to ``modindex`` in the default template (for Python domain only) ?
- Do the same for ``data`` (constants) ?

### Relates
- #3178

2016-12-24 01:22 UTC, Naereen commented
Here are some screenshots:

- The added `classindex` and `funindex` label link on a `.rst` page: (not translated yet)
![demo main index](https://cloud.githubusercontent.com/assets/11994719/21464500/32957dc0-c97f-11e6-87bc-af2049f56bec.png)

- Example of a class index with some classes, order by modules (exactly as the default mod index):
![demo class index](https://cloud.githubusercontent.com/assets/11994719/21464507/627143a8-c97f-11e6-9fd3-41a5058f81de.png)

- 2 examples of a fun index with some functions, order by modules (exactly as the default mod index):
![demo fun index](https://cloud.githubusercontent.com/assets/11994719/21464512/7b564fb2-c97f-11e6-80e4-75add3b23e35.png)
![demo fun index 2](https://cloud.githubusercontent.com/assets/11994719/21464523/db5c9f1a-c97f-11e6-833a-fe5735b8f711.png)

2016-12-24 01:24 UTC, Naereen commented
Note: I don't think the travis build failed because of my modification, based on what I saw.

2016-12-24 01:29 UTC, Naereen commented
Here is a demo of how it looks on a "real" (tiny) project:

- fun index: [example 1](http://perso.crans.org/besson/infoMP/TPs/solutions/py-funindex.html), [example 2](http://perso.crans.org/besson/infoMP/DSs/solutions/py-funindex.html),
- class index: [example 3](http://perso.crans.org/besson/infoMP/TDs/solutions/py-classindex.html).

2016-12-24 01:32 UTC, Naereen commented
@tk0miya what do you think?

By the way, merry Xmas to all ! :christmas_tree: :santa: :gift: !

2016-12-24 03:28 UTC, tk0miya requested changes
As a quick look, it looks good to me.
BTW, could you add testcase?

2016-12-24 03:28 UTC, tk0miya commented on doc/config.rst
> +.. confval:: funindex_common_prefix
Sphinx uses "func" as abbreviation of the function like `:py:func:`.
So I prefer to rename this to `funcindex_common_prefix`.

2016-12-24 03:28 UTC, tk0miya commented on sphinx/domains/python.py
> +class PythonClassIndex(Index):
It seems these three index classes are very similar.
How about making a common parent class?
It would be nice to keep code simple :-)

2016-12-24 03:28 UTC, tk0miya commented on sphinx/locale/fr/LC_MESSAGES/sphinx.po
> +# French translations for Sphinx.
Hmm? Did you translate this manually?
We use transifex.com to manage translations.
So you don't change *.po file manually (at least, in master branch).

2016-12-24 03:30 UTC, tk0miya commented on sphinx/domains/python.py
> +                            for (refname, (docname, type)) in iteritems(self.domain.data['objects'])
In addition, Mr flake8 warns this line is too long. Please fold the line :-)
Line 735 is also.
https://travis-ci.org/sphinx-doc/sphinx/jobs/186467941#L441

2016-12-24 03:32 UTC, tk0miya commented
@shimizukawa Could you give us advice?
I'd reviewed this in coding level, but I could not determine this is really needed or not to sphinx-core.

2016-12-24 10:00 UTC, Naereen commented on doc/config.rst
> +.. confval:: funindex_common_prefix
OK, I will fix that.

2016-12-24 10:15 UTC, Naereen commented on sphinx/locale/fr/LC_MESSAGES/sphinx.po
> +# French translations for Sphinx.
OK, I knew it was a bad idea...

2016-12-24 10:59 UTC, Naereen commented on sphinx/domains/python.py
> +class PythonClassIndex(Index):
I would rather write a function generating a class (a functor), to be able to easily have subclasses of `Index` for classes, functions, data, attributes, methods, classmethods, staticmethods etc.

2016-12-24 11:07 UTC, Naereen commented on sphinx/domains/python.py
> +                            for (refname, (docname, type)) in iteritems(self.domain.data['objects'])
OK, thanks. I fixed that.

2016-12-24 11:08 UTC, Naereen commented on sphinx/domains/python.py
> +class PythonClassIndex(Index):
Cf. b9d91d3
It seems cleaner.

2016-12-24 11:10 UTC, Naereen commented
Maybe it's too much, but I added the possibility to generate (and link to, with a label link) indeces of all these Python object types:

- `class`
- `function`
- `data`
- `exception`
- `method`
- `classmethod`
- `staticmethod`
- `attribute`

Example: [here (in French)](http://perso.crans.org/besson/infoMP/TPs/solutions/#table-des-matieres).

2016-12-24 12:45 UTC, Naereen commented on sphinx/locale/fr/LC_MESSAGES/sphinx.po
> +# French translations for Sphinx.
I reverted the changes, in c6cbd92. Sorry.

2016-12-24 12:47 UTC, Naereen reviewed
I changed the way to customize this, and `'()'` is now added to the displayed name of functions, classmethods, staticmethods, and methods in their respective index.

2016-12-24 13:12 UTC, Naereen commented
I am not sure how to add test cases for these changes. Any hint please?

2016-12-25 03:59 UTC, shimizukawa commented
Thank you for your PR. I also think that it is useful when implementing a large library to have a list of classes and functions as individual index pages. BTW, Sphinx is a tool suitable for document creation for Python, however it is also open to applications other than Python. Therefore, I would like to avoid adding Python specific settings and mechanisms to the global space drastically.

* +1: I think categorized index page is useful
* -1: Adding config and label specific to python domain in global space (it is not good that the existing `py-modindex` is specific to the Python domain but implemented in std)
* -1: There is no link to the new index pages and there is no documentation, so it is difficult for users to use it.
* Suggestion: You should have a representative index page and the page have links to each index pages
* Proposal: At the beginning, let's make it as an independent Sphinx extension. It can be grown in shorter cycles than Sphinx and you can act quickly based on user feedback.

2016-12-26 17:41 UTC, Naereen commented
Thanks @shimizukawa for your insights.
I know and understand your wish to keep the Python-specific things away from the generic Sphinx tool.

- About first -1 : I tried to define the `labels` and `anonlabels` for `py-classindex` (& all others) in the `python.py` domain file rather than the `std.py` domain file, but it ain't no good as the labels are mainly intended to be used in `.rst` files (std domain) rather than in Python docstrings...
- About second -1 and the suggestion, dff3d4b is a suggestion of how to had links to these index pages. Here is an example:
![demo all index](https://cloud.githubusercontent.com/assets/11994719/21484838/9f2701ae-cb99-11e6-9774-87d214060a4e.png)
- By the way, I found a surprising feature, on the `basic` theme, all the new index pages are added to the `relbar2` block. It might get too much if all the index pages are used, maybe `themes/basic/layout.html` should be modified to only include some links and not all (`{%- for rellink in rellinks %}`, line 31).

About your proposal, I agree it could be more efficient, but I prefer to be clear right away: I don't and won't have time to neither develop the extension nor maintain it. I know it takes some time, just to have either a PyPI package, or a merge in sphinxcontrib.
Sorry.

2017-01-11 15:53 UTC, Naereen commented
Any update ?

2017-01-12 12:05 UTC, shimizukawa commented
We also do not have much time. I think that the feature you want is wonderful. However, I feel that the current implementation you write complicates Sphinx's code base. For this reason, once we adopt the current proposal code, it is difficult for us to maintain in the future.

2017-01-13 15:25 UTC, tk0miya commented
@shimizukawa Could you close this? As a quick look, we decided not to merge this. So this should be closed.

2017-01-14 06:15 UTC, closed without merging