Added pyversion option for doctest (issue 3303)
sphinx-doc/sphinx pull request #3339
Opened 2017-01-13 21:46 UTC by marco-buttu

This pull request is related to the   #3303 . Now it is possible to specify the Python version required to execute the doctest. For instance:

```
.. doctest::
   :pyversion: >= 3.3
```

The operator could be: <, <=, ==, >=, >. I also added two tests.

2017-01-14 05:46 UTC, tk0miya commented on sphinx/ext/doctest.py
> +from distutils.version import StrictVersion as V
Why abbrviate? `V` is not clear name to me.

Anyway, it should be imported after importing six.
We usually import libraries in order of python standards, 3rd parties, docutils and sphinx's.

2017-01-14 05:49 UTC, tk0miya commented on sphinx/ext/doctest.py
> +            try:
Could you separate this into a single function and add some test?
It seems the evaluation code are not tested well.

2017-01-14 05:50 UTC, tk0miya reviewed
LGTM with nits

2017-01-14 05:52 UTC, tk0miya commented
Ah, I'd overlooked about travis.
It seems CI process was failed.
Please check the logs of travis ci and fix them.

2017-01-14 18:10 UTC, marco-buttu commented
Thanks for your time @tk0miya . I am not completely satisfied about the test, because I do not know how to propery create a TestDirective object, so I gave it dummy arguments...

2017-01-15 09:31 UTC, tk0miya reviewed
If you are not satisfied the tests, how about changing the interface like following?
```
def compare_version(ver1, ver2, operand):
    if operand not in operands:
        raise ValueError  # raise ValueError if unknown operand

    ...
    return result  # return boolean value as a result of comparison


class TestDirective(Directive):
    def run(self):
        ...
        if self.name == 'doctest' and 'pyversion' in self.options:
            try:
                if compare_version(platform.python_version(), version, operand):
                    ...
            except ValueError:
                # handle error for unknown operand and other reasons.
                self.state.document.reporter.warning(...)
```

2017-01-15 09:31 UTC, tk0miya commented on sphinx/ext/doctest.py
> +            self.document.reporter.warning(
Is this typo for self. **state** .reporter?
Did you check this warning works surely?

2017-01-15 09:43 UTC, marco-buttu commented on sphinx/ext/doctest.py
> +            self.document.reporter.warning(
Your interface is just perfect :-)  So, I will change my interface following your suggestion, fix the typo and check (with pytest) everything works properly. Thank you very much!

2017-01-16 03:22 UTC, tk0miya commented on doc/ext/doctest.rst
> +
style-check script says
```
doc/ext/doctest.rst:82: trailing whitespace
```

Please check Travis CI's status after fixed up.

2017-01-16 03:23 UTC, tk0miya approved these changes
LGTM with nits

2017-01-16 10:08 UTC, marco-buttu commented on doc/ext/doctest.rst
> +
I am sorry @tk0miya , I checked Travis but I was not able to figure out where the problem was, and I thought to fix it on this morning. I have not enough confidence with all the tools yet :-/

2017-01-16 10:11 UTC, marco-buttu commented
I double checked everything, the warning messages too, and it works properly. Thank you very very much @tk0miya

2017-01-16 14:33 UTC, tk0miya commented
LGTM!
I will merge this if no objection in a few days.

2017-01-25 17:58 UTC, tk0miya commented on CHANGES
> +* #3303: Added ``:pyversion:`` option to the doctest directive
Sorry, this feature will be released as 1.6.
1.5.x series is under maintenance period. so only bug fixes are allowed.

2017-01-25 17:59 UTC, tk0miya commented on doc/ext/doctest.rst
> +     .. versionadded:: 1.5
Please rewrite this to 1.6.

2017-01-26 01:26 UTC, tk0miya commented on sphinx/ext/doctest.py
> +                        "missing '+' or '-' in '%s' option." % option,
Could you wrap with `_(...)` function?
Ex:
```
from sphinx.locale import _
self.state.document.reporter.warning(_("missing '+' or '-' in '%s' option.") % option)
```

Then it makes the message translatable.

2017-01-26 03:14 UTC, tk0miya commented on sphinx/ext/doctest.py
> +                on_or_off, option_name = option[0], option[1:]
I feel `on_or_off` is a bit ugly name. How about `prefix`, `sign` or others?

2017-01-26 03:15 UTC, tk0miya requested changes
I reviewed again for latest update.
Could you check them please?

2017-01-26 10:05 UTC, marco-buttu commented on sphinx/ext/doctest.py
> +                on_or_off, option_name = option[0], option[1:]
``on_or_off`` is the name given to ``+/-`` in the doctest documentation, but I agree with you that is not meaningful. I wil use ``prefix``, thanks for the suggestion :-)

2017-01-26 10:06 UTC, marco-buttu commented on sphinx/ext/doctest.py
> +                        "missing '+' or '-' in '%s' option." % option,
:+1:

2017-01-26 10:06 UTC, marco-buttu commented on doc/ext/doctest.rst
> +     .. versionadded:: 1.5
:+1:

2017-01-26 10:41 UTC, marco-buttu commented
Done :) Thanks @tk0miya

2017-01-28 11:00 UTC, tk0miya commented on sphinx/ext/doctest.py
> +                on_or_off, option_name = option[0], option[1:]
I don't know that. But it looks better to me :-)

2017-01-28 11:00 UTC, tk0miya approved these changes

2017-01-28 11:34 UTC, merged

2017-01-28 11:34 UTC, tk0miya commented
Merged!
Thank you for contribution :-)