Fixed bug conf.py was'nt overwritten by template
sphinx-doc/sphinx pull request #3391
Opened 2017-02-05 01:02 UTC by pashango2

When adding templatedir with "sphinx-quickstart", only conf.py_t will not be overwritten.
Behavior is different from other template files, so I fixed it.

2017-02-05 14:13 UTC, tk0miya requested changes
LGTM with nits.

BTW, this is a bug fix. so it would be nice if you rebase this to stable branch.

2017-02-05 14:13 UTC, tk0miya commented on sphinx/quickstart.py
> +    # conf_path = os.path.join(templatedir, 'conf.py_t')
Could you remove this comment?

2017-02-05 15:30 UTC, pashango2 commented on sphinx/quickstart.py
> +    # conf_path = os.path.join(templatedir, 'conf.py_t')
Thank you for review
Comment deleted.

2017-02-06 10:37 UTC, pashango2 commented
Thank you for review.
removed comment.

2017-02-06 23:46 UTC, closed without merging