Make genindex support all kinds of letters, not only Latin ones
sphinx-doc/sphinx pull request #3470
Opened 2017-02-26 19:13 UTC by mitya57

Without this i.e. all names starting with a Cyrillic letter are moved into a Symbols section rather than being split into sections by letter. [Example page](http://docs.istina.msu.ru/genindex.html).

Before | After
------ | ------
![genindex](https://cloud.githubusercontent.com/assets/1381584/23342720/d918763a-fc78-11e6-84a5-3aa0541bb241.png) | ![genindex-new](https://cloud.githubusercontent.com/assets/1381584/23342721/d91c2e2e-fc78-11e6-89a3-cdac03f65241.png)

2017-02-27 02:55 UTC, tk0miya requested changes
LGTM with nits.
BTW could you add testcase to `tests/test_environment_indexentries.py` ?

2017-02-27 02:55 UTC, tk0miya commented on sphinx/environment/managers/indexentries.py
> +        def keyfunc(entry, lcletters=None):
Is `lcletters` still needed?

2017-02-27 02:55 UTC, tk0miya commented on sphinx/environment/managers/indexentries.py
> +        def keyfunc2(item, letters=None):
Is `letters` also needed?

2017-02-27 02:59 UTC, tk0miya commented
@shimizukawa This might be related with the key for glossaries. So please give us comment if you have.

2017-02-27 12:52 UTC, mitya57 commented
@tk0miya Updated! It should also support RTL languages now: I added a test that checks that the first letter of ‏תירבע‎ is ת.

2017-02-27 19:37 UTC, mitya57 commented
Note for future: ideally uppercase should be language-aware. I.e. uppercase i is I in most languages, but it is İ in Turkish.

But that would not be easy to fix.

2017-02-28 01:15 UTC, shimizukawa commented
> This might be related with the key for glossaries. So please give us comment if you have.

I checked and LGTM. 
Glossary key `glossary term : glossary key` feature is not affected by this change.

2017-02-28 05:11 UTC, tk0miya approved these changes

2017-02-28 05:16 UTC, tk0miya commented
LGTM!
I will merge this later (because adding CHANGES is needed after merging, but I don't have console now).

2017-02-28 17:31 UTC, merged

2017-02-28 17:32 UTC, tk0miya commented
Merged, Thanks!