Fix Python domain nesting
sphinx-doc/sphinx pull request #3520
Opened 2017-03-06 01:20 UTC by agjohnson

Moved #3465 here, to address this in `stable` instead.

This fixes a problem with the Python domain object nesting. Because only
one object name was stored in `ref_context`, and reset to `None` in
`after_content`, nesting broke if you put anything after a nested class:

```rst
.. py:class:: Parent

    .. py:method:: foo()

        This wouldn't resolve: :py:meth:`bar`

    .. py:class:: Child

        In the `after_content` method, the object is reset to `None`, so
       anything after this in the same nesting is considered to be top level
       instead.

    .. py:method:: bar()

        This is top level, as the domain thinks the surrounding object is `None`
```

This depends on #3519 and can be rebased after that is merged into stable

Fixes #3065 Refs #3067

2017-03-07 03:06 UTC, agjohnson commented
Rebased on stable with #3519 merged

2017-03-07 15:22 UTC, tk0miya requested changes
Almost LGTM

2017-03-07 15:22 UTC, tk0miya commented on sphinx/domains/python.py
> +                    self.env.ref_context['py:classes'] = [prefix]
Please use `dict.setdefault()` instead.
Then you don't need to catch any exceptions:
```
classes = self.env.ref_context.setdefault('py:classes', [])
classes.append(prefix)
```

2017-03-07 15:22 UTC, tk0miya commented on sphinx/domains/python.py
> +            except (KeyError, IndexError):
Are these exception raised here?

2017-03-07 15:22 UTC, tk0miya commented on sphinx/domains/python.py
> +            self.env.ref_context['py:class'] = cls_name
I prefer to simple implementation. How about this?
```
if len(self.env.ref_context['py:classes']) > 0:
    self.env.ref_context['py:class'] = self.env.ref_context['py:classes'][-1]
else:
    self.env.ref_context['py:class'] = None
```

2017-03-07 15:22 UTC, tk0miya commented on sphinx/domains/python.py
> +            (cls_name, cls_name_prefix) = self.names.pop()
Until now, `self.names.pop()` is not called.
Is there any side effect?

2017-03-07 15:22 UTC, tk0miya commented on sphinx/domains/python.py
> +                prefix = cls_name
`prefix` is determined by both `allow_nesting` and `cls_name_prefix`.
So how about this? I feel this is more simple.
```
if self.allow_nesting:
    prefix = cls_name
elif cls_name_prefix:
    prefix = cls_name_prefix.strip('.')
else:
    prefix = None
```

2017-03-07 15:22 UTC, tk0miya commented on sphinx/domains/python.py
> +        If this class is a nestable object, such as a class object, build up a
I feel a bit strange for "this class". How about "this instance" or "the instance"?

2017-03-07 15:22 UTC, tk0miya commented on sphinx/domains/python.py
> +            (cls_name, cls_name_prefix) = self.names.pop()
Hmm... `self.names.pop()` contains always "class name" ?
As a quick look, it also contains modules, methods, functions and so on.
If my consideration is true, please rename this to better one.

2017-03-08 06:15 UTC, agjohnson commented on sphinx/domains/python.py
> +        If this class is a nestable object, such as a class object, build up a
I feel like class is the most correct, as `allow_nesting` is used as a class variable. I can find a clearer way of describing this though.

2017-03-08 06:16 UTC, agjohnson commented on sphinx/domains/python.py
> +            (cls_name, cls_name_prefix) = self.names.pop()
That makes sense, I'll update this

2017-03-08 06:19 UTC, agjohnson commented on sphinx/domains/python.py
> +            except (KeyError, IndexError):
Both can, yes. `KeyError` if `py:classes` has not been set yet, and `IndexError` if this is an empty list.

2017-03-08 06:20 UTC, agjohnson commented on sphinx/domains/python.py
> +            self.env.ref_context['py:class'] = cls_name
I think the original is more succinct and pythonic, but I don't have a strong opinion. This change looks fine

2017-03-09 04:52 UTC, tk0miya commented on sphinx/domains/python.py
> +        If this class is a nestable object, such as a class object, build up a
I felt confused the description uses "class" twice. The first class; "this class" means subclasses of `PyObject`. It is an implementation of directives. so my proposal was wrong.
And second one; "a class object" means subjects of directives. Sometime it is a class, a method, and so on.

I'm not a native English speaker and not good at English. so If you feel this is okay, go ahead with this.

2017-03-09 04:57 UTC, tk0miya commented on sphinx/domains/python.py
> +            except (KeyError, IndexError):
Oh, sorry. I understand your code now.
Surely, it will be raised in case of no prefix found in `before_content()`.
Okay, no problem.

2017-03-16 07:05 UTC, agjohnson commented
Things are now cleaned up and rebased

2017-03-18 08:33 UTC, tk0miya approved these changes

2017-03-18 08:33 UTC, merged

2017-03-18 08:34 UTC, tk0miya commented
Merged. Thank you for contribution!