Callback on domains to annotate xrefs created from docfields.
sphinx-doc/sphinx pull request #3528
Opened 2017-03-08 12:14 UTC by jakobandersen

### Feature or Bugfix
- Bugfix: #2607, #2665.

### Purpose
Some docfields creates pending_xrefs, which needs to have extra information in some domains (e.g., Python and C++) in order to do name lookup in the right scope.
This PR adds an overrideable method to the domain base class, which is called from `docfields.Field.make_xref` with newly created pending_xref nodes. Is there a better way to do this?
The original problem is fixed in the C++ domain (not sure how to do it in Python).

### Detail
This is the updated example from #2665:

```rst
.. cpp:class:: NS::MyException : public std::exception

    Type of an exception.

.. cpp:namespace:: NS

.. cpp:function:: void my_function()

    :exception NS\:\:MyException:   This works.
    :exception MyException:         This now works. <================

    * Referencing :cpp:class:`NS::MyException` works.
    * Referencing :cpp:class:`MyException` also works.

.. py:class:: PyClass

    .. py:exception:: Ex

    .. py:method:: f()

        :raises PyClass.Ex: This works.
        :raises Ex: This happens to also work now, probably not for the right reason? <================

        * Referencing :py:class:`PyClass.Ex` works.
        * Referencing :py:class:`Ex` doesn't work (a bug #3065)

.. py:method:: g()

    :raises PyClass.Ex: This works.
    :raises Ex: This shouldn't work, but does (a new bug?) <================
```

Something strange is going on with scoping in the Python domain, maybe from fixing #3065?

2017-03-09 04:39 UTC, tk0miya requested changes
LGTM for your idea.
I proposed an order of arguments to keep compatibility. It might be needed.

BTW, this PR includes the changes of interface. I think it is not stable changes. so master branch is better to do that to me.

2017-03-09 04:39 UTC, tk0miya commented on sphinx/util/docfields.py
> +    def make_xref(self, env, rolename, domain, target,
I think this change might be incompatible changes.
We provides domains feature as an extensible point of Sphinx.
So I'm worry about any 3rd party domain uses these functions in docfields.

How about adding this as a optional argument?
It does not breaks the interface.

2017-03-11 13:22 UTC, jakobandersen commented
I have changed the signatures so the env argument is in the end and is defaulted. I think that should make it backwards compatible, but I can rebase it to master if needed.

2017-03-11 15:11 UTC, tk0miya approved these changes

2017-03-11 15:12 UTC, tk0miya commented
Approve. After updating, I don't opposite for merging stable. Please go ahead :-)

2017-03-12 03:32 UTC, merged

2017-03-12 03:33 UTC, jakobandersen commented
@tk0miya thanks for reviewing!