Prevent a TypeError bug for get_full_modname()
sphinx-doc/sphinx pull request #3536
Opened 2017-03-10 09:06 UTC by Naereen

Subject: prevent a TypeError bug for `get_full_modname()` in `sphinx.util`.

### Bugfix
It prevents this bug:
```python
viewcode can't import None, failed with error "__import__() argument 1 must be str, not None"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/ext/viewcode.py", line 28, in _get_full_modname
    return get_full_modname(modname, attribute)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/util/__init__.py", line 263, in get_full_modname
    __import__(modname)
TypeError: __import__() argument 1 must be str, not None
```

### Purpose
- Just a small trick, instead of waiting to the end to return `None`, return it directly if the rest of the function will fail if `modname = None` instead of a string.

2017-03-10 09:07 UTC, Naereen commented
Illustrating this small (non blocking) bug, obtained just now from the latest Sphinx release:
![bug sphinx](https://cloud.githubusercontent.com/assets/11994719/23788988/40da8390-0579-11e7-88cd-8daf66289e51.png)

2017-03-10 09:07 UTC, Naereen commented on sphinx/util/__init__.py
> +    # type: (str, unicode) -> Union[unicode, NoneType]
I changed manually the type, I don't know if that's the correct way to do it?

2017-03-10 18:06 UTC, tk0miya requested changes
LGTM, but it would be much better to move this to stable branch because this is bugfix. could you rebase this to the branch?

2017-03-10 18:06 UTC, tk0miya commented on sphinx/util/__init__.py
> +    # type: (str, unicode) -> Union[unicode, NoneType]
I think you don't need to update here. `-> unicode` annotation expects the return value is a unicode or None.

2017-03-10 21:57 UTC, Naereen commented on sphinx/util/__init__.py
> +    # type: (str, unicode) -> Union[unicode, NoneType]
OK

2017-03-10 21:57 UTC, Naereen commented
I don't think I can rebase from the web version.

2017-03-10 21:58 UTC, Naereen commented
And it's not a dangerous bug, my fix essentially just removes the error message.
No need to hurry into merging into the `stable` branch, IMO.

2017-03-11 00:27 UTC, tk0miya approved these changes

2017-03-11 00:27 UTC, merged

2017-03-11 00:28 UTC, tk0miya commented
Merged into master. I'll merge this into stable manually if needed.
Thank you for contribution!