Fix paths in conf.py on windows
sphinx-doc/sphinx pull request #3584
Opened 2017-03-24 10:57 UTC by eric-wieser

Otherwise paths like `somefolder\test` would be treated as containing a tab
character

2017-03-25 13:03 UTC, tk0miya commented
Is this work with py3?
It would be nice to escape the `module_path`.

2017-03-25 13:12 UTC, eric-wieser commented
`r` syntax is supported in all python versions.

the `u` will break in python 3.x<3.3, but that was there already, so shouldn't be an issue?

2017-03-25 13:23 UTC, tk0miya commented
AFAIK, `ur` prefix is not supported in python3. At least, it causes SyntaxError with py34 and py36 at my local.
```
$ python3.4
Python 3.4.5 (default, Jun 27 2016, 20:10:23)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ur'hello world'
  File "<stdin>", line 1
    ur'hello world'
                  ^
SyntaxError: invalid syntax
```
```
$ python3.6
Python 3.6.1 (default, Mar 23 2017, 13:18:18)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ur'hello world'
  File "<stdin>", line 1
    ur'hello world'
                  ^
SyntaxError: invalid syntax
```

As a quick look, it seems dropped sicne py33 (or py34).
http://stackoverflow.com/questions/26063899/python-version-3-4-does-not-support-a-ur-prefix

2017-03-25 13:33 UTC, eric-wieser commented
Ugh, you're right.

The goal of using `r` here was to make a path like `C:\Users\Someoné\doc` appear as `ur"C:\Users\Someoné\doc"` rather than `u"C:\\Users\\Someoné\\doc"`.

Alternatively, we could go for `br"C:\Users\Someoné\doc".decode('utf-8')`?

2017-03-25 13:44 UTC, tk0miya commented
I feel `u"C:\\Users\\Someoné\\doc"` is much better.
`encode()` and `decode()` technique is too hacky for me.
Why do you want to use `r` prefix? Why not escaping?

2017-03-25 13:51 UTC, eric-wieser commented
You actually should probably have the `encode` there anyway, to ensure that the encoding of the unicode matches the file encoding

2017-03-25 13:52 UTC, eric-wieser commented
> Why do you want to use r prefix? Why not escaping?

Because then users can directly paste a file path in without worrying

2017-03-26 03:06 UTC, tk0miya commented
I feel this is better way.
```
sys.path.insert(0, {{ repr(module_path).encode('utf-8') }})
```

>Is it important that a conf.py file generated with python 3 can be run on python 2 and vice versa?

I think this is a rare case, so it would not be problem (because py2 will be deprecated in 2020!).
@shimizukawa what do you think?

2017-03-26 11:59 UTC, eric-wieser commented
Also worth asking - does sphinx support 2.6?

2017-03-29 14:00 UTC, tk0miya commented
No, Sphinx supports 2.7 and 3.4+.

2017-04-20 12:31 UTC, shimizukawa commented
IMO, the fundamental problem is that any Windows PATH specified as a option for apidoc command is render to conf.py without being escaped.
Python treats both backslashes and slashes equally as path separators, so let's use this feature. It would be nice to replace the all backslashes in the path with slash when path received from apidoc command option.

2017-04-20 12:41 UTC, eric-wieser commented
> render to conf.py without being escaped.

Correct. And `repr` does that exact escaping - so we should use `repr`

2017-04-20 13:21 UTC, shimizukawa commented
`repr` is not suitable for escaping backslashes. `repr` is just for representation the string.
On py2, if you include a language-specific string in the path as below, a bad string will be rendered in conf.py.

```
>>> print(repr(ur'日本語\PATH').encode('utf-8'))
u'\u65e5\u672c\u8a9e\\PATH'
>>> print(repr(ur'αβ\PATH').encode('utf-8'))
u'\u03b1\u03b2\\PATH'
>>> print(repr(ur'АБГ\PATH').encode('utf-8'))
u'\u0410\u0411\u0413\\PATH'
>>>
```

2017-04-20 13:35 UTC, shimizukawa requested changes
This change doesn't work with Non-ASCII characters

2017-04-20 13:36 UTC, eric-wieser commented
> repr is not suitable for escaping backslashes. repr is just for representation the string.

This is untrue. `repr(s)` when `isinstance(s, (str, unicode))` is defined such that `eval(repr(s)) == s`. That's the definition of correct escaping. Overreaching escaping, perhaps, but definitely correct escaping.

> On py2 [...] a bad string will be rendered in conf.py.

The string that is rendered is correct. It's perhaps less readable that it could be, but it still does exactly the right thing, so "bad" is not really accurate

2017-04-20 13:49 UTC, eric-wieser commented
> This change doesn't work with

2017-04-29 06:01 UTC, tk0miya commented
+1 for human readable `conf.py`.
Indeed, `conf.py` is a python script, but at same time, it is a kind of configuration file. So it would be 
better if human readable.

How about replacing back-slashes with forward slashes?
I think that might work well in windows platform and human readable.

2017-04-29 10:24 UTC, eric-wieser commented
> So it would be better if human readable.

I agree. However, here's the choice we get to make:

* Human readable on non-ascii input
* `SyntaxError` or worse on input containing backslashes or quotes

I've updates my PR so that it now (hopefully) passes tests. Almost every interpolated string in this file suffered from the same bug.

In future, you could add a custom `urepr` jinja filter that emulates the python 3 `repr` behaviour on py2.

However, I don't think that needs to be in a bugfix PR.

2017-04-29 10:56 UTC, eric-wieser commented
> How about replacing back-slashes with forward slashes?

This does not really solve the problem elsewhere.

@shibukawa: I've added another commit with a custom repr handler that should make things both correct _and_ human readable

2017-04-29 10:59 UTC, eric-wieser commented
> What does sphinx do when autodocumenting def foo(s=ur'АБГ\PATH'): pass? Does it render a similarly "bad"-but-correct string?

I actually think that I might have fixed this problem too here

2017-04-29 13:33 UTC, shimizukawa commented
-1 because

- jinja2 `repr` filter implementation is too complex
- `repr` doesn't mean `backslash escaping`

(BTW shibukawa and shimizukawa is not a same person)

2017-04-29 14:30 UTC, eric-wieser commented
> jinja2 `repr` filter implementation is too complex

The only reason it exists in the first place is to make the python 2 `repr` match the python 3 `repr`. You've already rejected the simple method of using `repr` directly in python 2 for readability reasons - which I think is reasonable.

The implementation you see here is a port of the important bits of `PyObject_Repr` from the CPython source code.

> repr doesn't mean backslash escaping

`repr` means "take this object, and try to convert it into the python source code that generates itself". This is exactly the operation we want in a template outputting python code. From the [python 3 docs for `repr`](https://docs.python.org/3/library/functions.html#repr)

> this function makes an attempt to return a string that would yield an object with the same value when passed to `eval()`

So `repr(unicode)` absolutely does mean backslash escaping.

(Apologies for confusing the usernames - I assumed github would suggest participants first in the dropdown, and didn't read the full name)

2017-04-29 14:53 UTC, eric-wieser commented on sphinx/util/template.py
> +            return 'u' + repr(obj)
This is new behaviour, that means that `u`s are inserted into python 3 source code. I'd argue this is useful, as it means a conf file generated in python 3 will work correctly in python 2 (for non-ascii strings).

If you want to keep things as they are, I'm happy to remove this python 3 case

2017-09-24 15:31 UTC, tk0miya commented
It seems discussion is stopped for a long time. and @shimizukawa objected to this.
I also feel `repr` is not good for this case. So I'd like to close and file a new issue for this.

@shimizukawa what do you think?

2017-10-21 05:39 UTC, shimizukawa commented
+1 to @tk0miya 's opinion.

2017-10-21 05:58 UTC, eric-wieser commented
> It seems discussion is stopped for a long time

I was hoping you might respond with counterarguments to some of my points above. I don't understand why you argue `repr` is not good for this case, when this is the exact case that `repr` is designed for.

I'm happy to rebase this PR to solve conflicts if we can come to an agreement. There are also some bug fixes in here related to `unicode`/`bytes` that should go in anyway

2017-10-21 05:59 UTC, eric-wieser commented on sphinx/quickstart.py
> +        return text.decode('ascii')
This was a but - this function should always return `unicode`

2017-10-21 06:01 UTC, eric-wieser commented
> implementation is too complex

I'm also planning to go back and improve the comments there based on the comments I've been making here.

2017-10-21 07:45 UTC, tk0miya commented
>I was hoping you might respond with counterarguments to some of my points above. I don't understand why you argue repr is not good for this case, when this is the exact case that repr is designed for.

As I commented above, I think `conf.py` is used as configuration file. So readability is needed.
And I feel `u'\u0410\u0411\u0413\\PATH'` is not human readable.
I'm okay to this If your implementation does not escape Unicode character and show them as is.

In addition, I want to know why replacing back-slashes by forward-slashes is bad.

2017-10-21 07:50 UTC, eric-wieser commented
> I'm okay to this If your implementation does not escape Unicode character and show them as is

In the latest version, this is the case. It's possibly misleading that I called the filter `repr` - perhaps calling it `nice_repr` would reduce ambiguity?

> In addition, I want to know why replacing back-slashes by forward-slashes is bad.

It's a corner case, but paths on linux can actually contain backslashes, and converting them to forward slashes would break things. Better to be correct here.

2017-10-21 08:07 UTC, eric-wieser commented
[Demo of it working](https://www.ideone.com/NVvaHu#stdin). I think perhaps `reprlib` is doing more harm than good here, since the truncation behaviour is pretty ingrained

2017-10-21 08:23 UTC, eric-wieser commented
Ok, [here's](https://www.ideone.com/KV4ZsD) a better and simpler filter implementation, that throws out reprlib in favor of implement the few things you care about.

2017-10-21 09:15 UTC, eric-wieser commented
I've pushed a new version, and rebased, along with some tests. `urepr` is now in its own file, to contain the complexity - I strongly suspect that there are other places in sphinx that ought to be using it.

2018-01-18 16:16 UTC, tk0miya commented
Sorry for very late response.
I feel new `urepr` is good enough.

@shimizukawa what do you think? If you also agree, I'll start to review again.

Note: We will release 1.7 series soon. So this will be merged into `1.7-release` branch.

2018-02-11 06:53 UTC, shimizukawa reviewed
The code for urepr.py seems to be a necessary and sufficient code for what you want to realize, but I still feel that the maintenance cost is high. I will merge as soon as this PR's scope of influence only fixes path problems in Windows, but it will not be accepted as it will contain changes that affect other items in conf.py as well.

2018-02-11 07:13 UTC, eric-wieser commented
Looks like the title of the PR is misleading - I've updated it to match the first commit message, which describes the real change. Windows paths failing is a symptom of a wider problem - incorrect data escaping.

If you'd like, I can try to write a more comprehensive explanation of the change in the commit message when I rebase to solve the conflicts.

> I still feel that the maintenance cost is high.

I'd argue the overall cost has reduced because:

* Unlike the previous code, the escaping-of-strings now is all in one place, and has unit tests.
* When python 2 is dropped, then the entire `urepr` function can be replaced with `urepr = repr`, and everything will just work.
* I suspect you need `urepr` in other places within sphinx

2018-02-13 05:49 UTC, tk0miya commented
Sorry, I just removed `stable` branch last night. As a result, github closes this automatically. It was not intended. so I reopened this again and changed target branch to `1.7` (we decided to rename stable branch to versioned one).
Thanks,

2018-03-19 07:50 UTC, eric-wieser commented on sphinx/quickstart.py
>          d['exclude_patterns'] = ''
Note to self - change to `[]`

2018-08-25 10:27 UTC, tk0miya commented
I feel this PR is too longly alive, but not discussed. So I'd like to determine merging or rejecting.

In my opinion, this has some problem:

* tests have not been passed.
* @shimizukawa objects to this.
* I also feel this makes the template for conf.py complicated. +1 for using `repr` only for limited places. IMO, escaping to `dot` is too much.
* We'll drop py2 soon. So `urepr` also will be removed soon.

2018-09-09 11:18 UTC, tk0miya commented
Now I'm closing this because this was stopped discussing for a long time.
I'm sorry for our slowly response.
Thank you for your proposal.

2018-09-09 11:18 UTC, closed without merging

2018-09-09 17:45 UTC, eric-wieser commented
> IMO, escaping to dot is too much.

What do you mean by this?

> We'll drop py2 soon. So urepr also will be removed soon

True, but you'll still need `repr` in its place

2018-09-11 12:54 UTC, tk0miya commented
>>IMO, escaping to dot is too much.
>What do you mean by this?

This line is hard to read. I feel this is too much. Is `dot` really need to escaped?
```
templates_path = [{{ '{}templates'.format(dot) | repr }}]
```
https://github.com/sphinx-doc/sphinx/pull/3584/files#diff-b4e26a06e5a278dd53e3992672be2eedR48

>True, but you'll still need repr in its place

+1 for escaping. I don't opposite your idea itself.