Test appveyor in master
sphinx-doc/sphinx pull request #3619
Opened 2017-04-11 15:44 UTC by tk0miya

refs: #3615

2017-04-12 15:42 UTC, tk0miya commented
I'd update some testcases, but I can't fix two failures...
@shimizukawa could you check these please?

2017-04-13 00:52 UTC, shimizukawa commented
Two failures are:

1. [AssertionError: assert 'Datei mit UT...ts: äöü.\n' == 'Datei mit UTF...lauts: ���.\n'](https://ci.appveyor.com/project/sphinxdoc/sphinx/build/1.0.21#L1244)
2. [AttributeError: Can't pickle local object 'ParallelTasks.add_task.<locals>.<lambda>'](https://ci.appveyor.com/project/sphinxdoc/sphinx/build/1.0.21#L1336)

No 1, seems something a locale problem. I have no idea for now... I'll check it later.

No 2, is Windows related multiprocessing problem I guess. 
As [python doc mentioned](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods), `On Windows only 'spawn' is available`, so I think you can reproduce this problem with using `spawn` mode on Unix.
`spawn` mode invoke new process and send context as pickle format to new process from master process. So inner class/function/lambda does not work well like `child_process` function in the `test_logging_in_ParallelTasks` test method.

2017-04-13 01:56 UTC, tk0miya commented
The two problems seems hard to fix for me.

It seems appveyor raises errors for some new PRs. I feel that confuses our contributors. So I'd like to merge this ASAP. How about skipping them and fixing them on another PR?

2017-04-13 06:20 UTC, shimizukawa commented
Agreed to skip testing.
pytest can skip test by platform.
https://docs.pytest.org/en/latest/skipping.html#skip-all-test-functions-of-a-class-or-module

2017-04-13 09:32 UTC, eric-wieser commented on sphinx/environment/collectors/asset.py
> +                if not os.access(posixpath.join(app.srcdir, imgpath), os.R_OK):
This looks wrong to me - why are we always using posixpath for a local file?

2017-04-13 09:34 UTC, eric-wieser commented on sphinx/directives/code.py
> -                                 'be wrong, try giving an :encoding: option') %
What bug is this fixing?

2017-04-13 14:48 UTC, tk0miya commented on sphinx/environment/collectors/asset.py
> +                if not os.access(posixpath.join(app.srcdir, imgpath), os.R_OK):
Surely, this is not needed. Either is fine for me.

2017-04-13 14:51 UTC, tk0miya commented on sphinx/directives/code.py
> -                                 'be wrong, try giving an :encoding: option') %
Not a bug, all these changes are used to pass testcases in both unix-like OS and Windows.

2017-04-13 14:59 UTC, eric-wieser commented on sphinx/directives/code.py
> -                                 'be wrong, try giving an :encoding: option') %
My question is, what is the failure when you don't make this change?

2017-04-13 15:01 UTC, eric-wieser commented
@shimizukawa: Error number 1 is an encoding problem in the test file itself. Perhaps python needs a `utf8` marker at the top of the file, or those characters are simply garbage

2017-04-13 15:05 UTC, eric-wieser commented on sphinx/ext/intersphinx.py
> -                invdata = InventoryFile.load(f, uri, join)
This also looks wrong - foreign urls should continue to use `posixpath`

2017-04-13 15:05 UTC, eric-wieser commented on sphinx/ext/intersphinx.py
> +                invdata = InventoryFile.load(f, uri, posixpath.join)
This also looks wrong - posixpath should not be used to join filesystem paths on windows, which is exactly what the old code was here to prevent

2017-04-13 15:09 UTC, eric-wieser requested changes

2017-04-13 15:09 UTC, eric-wieser commented on tests/test_intl.py
> +@pytest.mark.skipif(platform.system() == 'Windows', reason='Skipped on windows')
This would be better as `@pytest.mark.xfail(...)`, so that if someone does make it pass, appveyor will report it

2017-04-13 15:12 UTC, tk0miya commented on sphinx/directives/code.py
> -                                 'be wrong, try giving an :encoding: option') %
Here: https://ci.appveyor.com/project/sphinxdoc/sphinx/build/1.0.3#L1178

2017-04-13 15:16 UTC, tk0miya commented on tests/test_intl.py
> +@pytest.mark.skipif(platform.system() == 'Windows', reason='Skipped on windows')
Thanks

2017-04-13 15:29 UTC, tk0miya commented
I gave up to fix these problem correctly because I'm not good at windows.
Please feel free to rearrange this and send us as pull request who wants to support the platform.
Now I have only very few time to develop Sphinx, so I'd like to use my time to improvements.

@shimizukawa Could you stop appveyor or improve its settings?
It prevents to develop our mainline. It seems some PRs were kicked by appveyor because of no configurations found.

2017-04-13 15:29 UTC, closed without merging

2017-04-13 15:32 UTC, eric-wieser commented
I would say don't fix them, but keep the `xfail`s and the appveyor going, so that someone else can

2017-04-14 09:10 UTC, shimizukawa commented
I set `Skip branches without appveyor.yml` now.