Don't ignore first argument passed to sphinx.apidoc.main
sphinx-doc/sphinx pull request #3668
Opened 2017-04-25 18:18 UTC by adamjstewart

### Feature or Bugfix

Bugfix? Depends on whether you consider it a bug or a feature 😉 

### Purpose

We use Sphinx to generate our documentation. Our API changes fairly often, so in order to make sure our API docs stay up-to-date, we always re-run `sphinx-apidoc` with each build. Unfortunately, Read the Docs skips our Makefile and directly calls:
```
$ sphinx-build -b html . _build/html
```
To get around this, we run `sphinx-apidoc` from our `conf.py`. Our call looks something like:
```python
import sphinx.apidoc.main as sphinx_apidoc

sphinx_apidoc(['--force', '--no-toc', '--output-dir=.', '../spack'])
```
At first I was really confused why this gave different results than:
```
$ sphinx-apidoc --force --not-toc --output-dir=. ../spack
```
but after reading the source code, I quickly discovered that `main` ignores the first argument it is passed. This makes perfect sense when running `sphinx-apidoc` from the command line, as the first argument will be the name of the script. But it is much less intuitive when being called directly from `main`. This PR fixes that.

### Detail

By default, `main` will still process `sys.argv[1:]`, but if passed a list of arguments, it will now process all of them. I'm not sure if this bug (feature?) is documented already. My only concern is that this change isn't really backwards compatible. If you wanted it to be, I could theoretically check if the first argument is `sphinx-apidoc` and skip it if so.

### Relates

First reported here:
https://github.com/LLNL/spack/pull/3982/files#r113266150

2017-04-26 16:42 UTC, tk0miya commented
@shimizukawa could you review this? I don't know what is the standards in python.

BTW, sphinx-build, sphinx-quickstart and sphinx-autogen are also uses `parser.parse_args(argv[1:])`. So we should also fix them if you'll accept this.
```
$ grep -r parse_args sphinx
sphinx/apidoc.py:    (opts, args) = parser.parse_args(argv[1:])
sphinx/cmdline.py:        opts, args = parser.parse_args(list(argv[1:]))
sphinx/ext/autosummary/generate.py:    options, args = p.parse_args(argv[1:])
sphinx/quickstart.py:        opts, args = parser.parse_args(argv[1:])
```

2017-04-26 16:43 UTC, adamjstewart commented
Let me know if this seems like the right thing to do. If so, I can modify the others as well.

2017-04-26 16:47 UTC, tk0miya commented
either is fine to me. I don't have strong opinion.

2017-05-07 07:33 UTC, shimizukawa approved these changes
Ether OK to me.

2017-05-07 07:46 UTC, tk0miya requested changes
Thank you for comment.
As I said, I'm okay to merge this after all other scripts are updated.

2017-05-07 12:59 UTC, adamjstewart commented
Sounds good, I'll try to take a stab at this sometime this week.

2017-05-09 19:45 UTC, adamjstewart commented
I think I got everything now? Hopefully you have good unit tests.

2017-05-11 09:44 UTC, tk0miya requested changes
It seems `test_extensions` in test_quickstart.py failed.
https://travis-ci.org/sphinx-doc/sphinx/jobs/230493513#L1859

Could you check this please?

2017-05-11 09:44 UTC, tk0miya commented on utils/check_sources.py
> +    sys.exit(main(sys.argv[1:]))
You also need to update the `main()` in this file.
This causes following error:
https://travis-ci.org/sphinx-doc/sphinx/jobs/230493517#L746

2017-05-13 07:59 UTC, tk0miya commented on sphinx/cmdline.py
> +def main(argv=sys.argv[1:]):
mypy warns here: https://travis-ci.org/sphinx-doc/sphinx/jobs/231257064#L753
Please mark this line as `# typing: ignore`.

2017-05-13 15:07 UTC, adamjstewart commented on sphinx/cmdline.py
> +def main(argv=sys.argv[1:]):
Thanks, I've never used mypy before. Alternatively, I could remove the default argument and go back to the way things were before. I was just trying to make everything the same.

2017-05-13 15:34 UTC, tk0miya commented on sphinx/cmdline.py
> +def main(argv=sys.argv[1:]):
Oh, sorry. I was wrong. `# type: ignore` is correct, not *typing*.

2017-05-13 16:11 UTC, merged

2017-05-13 16:11 UTC, tk0miya commented
Merged. Thank you for contribution!