apidoc: Move apidoc to ext/apidoc
sphinx-doc/sphinx pull request #3929
Opened 2017-07-13 16:23 UTC by stephenfin

The 'sphinx-apidoc' tool is no longer the only kid on the block when it
comes to automatic documentation of Python projects, with the likes of
'sphinx-autoapi' in development [1] and is not really maintained. Given
the fact that the tool is tangential to Sphinx's main goal, there isn't
really anything that warrants its continue existence as a core module.

Signify this by moving the feature to 'ext'. This allows the feature to
continue to exist in the package, but indicates that stability might be
worse than one would expect from the core library.

To avoid breaking packages that are using this feature directly, such as
pbr [3], aliases for the old 'main' method are included. This is based
on what Django does and, like Django, will allow us to safely remove the
old modules in Sphinx 2.0.

[1] https://github.com/rtfd/sphinx-autoapi
[2] https://github.com/sphinx-doc/sphinx/pull/3485#issuecomment-288081223
[3] https://github.com/django/django/blob/1.11/django/test/runner.py#L688-L695

2017-07-15 13:11 UTC, tk0miya requested changes
LGTM with nits.

2017-07-15 13:11 UTC, tk0miya commented on sphinx/ext/apidoc.py
> +    sphinx.apidoc
This should be `sphinx.ext.apidoc`.

2017-07-15 13:11 UTC, tk0miya commented on sphinx/ext/apidoc.py
> +# -*- coding: utf-8 -*-
It seems this is a new file.
Please rename from `sphinx/apidoc.py` and create `sphinx/apidoc.py` as a new file to keep commit history,

2017-07-15 13:13 UTC, tk0miya commented
It seems travis raises errors. please check them.

@shimizukawa Do you have any comments?
I wonder which is better `sphinx.ext.apidoc` or `sphinx.ext.autodoc.apidoc`. what do you think?

2017-07-16 05:47 UTC, shimizukawa commented
I have no objection. 
And +1 to `sphinx.ext.apidoc`. `sphinx.ext.autodoc.apidoc` is too deep to me.

2017-07-16 05:49 UTC, shimizukawa reviewed
There is no more comment than @tk0miya's point.

2017-07-17 08:17 UTC, tk0miya commented
Thanks, either is okay. I think `sphinx.ext.autodoc.apidoc` is better if apidoc is a part of autodoc. But I don't know so much about apidoc. so it is not strong opinion.
Let's go with `sphinx.ext.apidoc`.

2017-07-21 09:43 UTC, stephenfin commented on sphinx/ext/apidoc.py
> +# -*- coding: utf-8 -*-
I'm not able to do anything about this. Git does file rename detection automatically (`git [mv]` might well be an alias for `git cp [src] [dst]` and `git rm [src]`), and its heuristics seem to be failing us here.

2017-07-21 09:43 UTC, stephenfin commented on sphinx/ext/apidoc.py
> +    sphinx.apidoc
Done

2017-07-21 16:59 UTC, stephenfin commented
@tk0miya OK, I've pushed the reworked version up and the build looks to be good now (it was a pep8 issue). Think that's all that's needed now?

2017-07-21 17:01 UTC, stephenfin commented
> Thanks, either is okay. I think sphinx.ext.autodoc.apidoc is better if apidoc is a part of autodoc. But I don't know so much about apidoc. so it is not strong opinion.

It is and it isn't :smile: The `sphinx-apidoc` tool generates documents that contain `autodoc` directives. However, it's not really part of `autodoc`, per se. If we were to move this, we should probably move `sphinx.ext.autosummary` too, as that also generates stub documents with `autodoc` directives in them.

2017-09-20 10:40 UTC, stephenfin commented
Could I get some eyes on this again? I think I've resolved everything that needs resolving?

2017-09-26 06:42 UTC, tk0miya approved these changes
Sorry for late response. I'm in busy last 2-3 months. But I'm back now :-)

2017-09-26 06:42 UTC, merged

2017-09-26 06:42 UTC, tk0miya commented
Merged. Thank you for your good work!