Re-arrange WARNING messages about reference inconsistencies
sphinx-doc/sphinx pull request #4122
Opened 2017-10-05 16:39 UTC by cocoatomo

Subject: Display appropriate WARNING messages about reference inconsistencies

### Feature or Bugfix

- Bugfix

### Purpose

- Separate correctly causes for each WARNING message. (Which message is about which cause?)

### Detail

For reference inconsistencies, now, Sphinx outputs four messages:

1. auto-numbered footnote: "inconsistent footnote references in translated message"
2. reference with refname: "inconsistent references in translated message"
3. reference: "inconsistent term references in translated message"
4. named footnote & citation: "inconsistent references in translated message"

(these messages are all implemented in sphinx/transforms/i18n.py.)

However, reST specification do not define "named footnote", which is actually citation.
Furthermore, citation inconsistencies are reported from warn_missing_reference method of ReferencesResolver class (which is located in sphinx/transforms/post_transforms/__init__.py) and
check_consistency function of StandardDomain class (which is located in sphinx/domains/std.py).

In conclusion, Sphinx should output four messages:

1. footnote: "inconsistent footnote references in translated message"
2. reference with refname: "inconsistent references in translated message"
3. reference: "inconsistent term references in translated message"
4. citation: "Citation [hoge] is not referenced." and "citation not found: fuga"

### Relates
- This PR is a preparation for #4106 .

2017-10-06 01:00 UTC, tk0miya requested changes
In addition, I guess new testcase is needed to check new warning message of non-auto-numbered footnote refs.

2017-10-06 01:00 UTC, tk0miya commented on sphinx/transforms/i18n.py
> -            # auto-numbered foot note reference should use original 'ids'.
This block is only for auto-numbered footnote_refs. So please don't merge standard footnote_refs here.

2017-10-06 01:00 UTC, tk0miya commented on sphinx/transforms/i18n.py
> -            # refnamed footnote and citation should use original 'ids'.
To change the warning message, please make a copy of this block to separate verifications of foonote_refs and citation_refs.

2017-10-06 01:04 UTC, tk0miya commented
Ah, I'd forgotten to say you. This is a bugfix, so please rebase this to stable branch. Then it will released as next 1.6.x release.
Thank you for your help :-)

2017-10-07 02:04 UTC, cocoatomo commented
I have re-created a revised PR #4124, because `git rebase` was involving unrelated file diffs.

2017-10-07 02:04 UTC, closed without merging