Cope with List node_name in get_lvar_namesl
sphinx-doc/sphinx pull request #4138
Opened 2017-10-10 15:39 UTC by peterjc

Subject: Hack to solve a crash I was seeing locally under Python 3.4 using latest Sphinx from GitHub, but for which I have not produced a minimal test case.

### Feature or Bugfix
- Bugfix

### Purpose

- First, gives a clearer exception

Before:

```
$ more  /var/folders/x9/9z4wpg753_v3fvwq7qs1llhc0000gn/T/sphinx-err-ux021d4c.log 
# Sphinx version: 1.7+
# Python version: 3.4.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:
#   reading sources... [ 35%] Bio.MaxEntropy
#   
#   reading sources... [ 36%] Bio.Medline
#   
#   reading sources... [ 36%] Bio.NMR
#   
#   reading sources... [ 36%] Bio.NMR.NOEtools
#   
#   reading sources... [ 37%] Bio.NMR.xpktools
#   
# Loaded extensions:
#   sphinx.ext.viewcode (1.7+) from /Users/peterjc/lib/python3.4/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.todo (1.7+) from /Users/peterjc/lib/python3.4/site-packages/sphinx/ext/todo.py
#   alabaster (0.7.10) from /Users/peterjc/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.7+) from /Users/peterjc/lib/python3.4/site-packages/sphinx/ext/autodoc/__init__.py
Traceback (most recent call last):
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/__init__.py", line 91, in parse
    parser.parse()
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 446, in parse
    self.parse_comments()
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 454, in parse_comments
    picker.visit(tree)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 273, in visit
    super(VariableCommentPicker, self).visit(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 273, in visit
    super(VariableCommentPicker, self).visit(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 352, in visit_FunctionDef
    self.visit(child)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 273, in visit
    super(VariableCommentPicker, self).visit(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 280, in visit_Assign
    varnames = sum([get_lvar_names(t, self=self.get_self()) for t in node.targets], [])  # type: ignore  # NOQA
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 280, in <listcomp>
    varnames = sum([get_lvar_names(t, self=self.get_self()) for t in node.targets], [])  # type: ignore  # NOQA
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/parser.py", line 66, in get_lvar_names
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/environment/__init__.py", line 725, in read_doc
    app.emit('doctree-read', doctree)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/application.py", line 436, in emit
    return self.events.emit(event, self, *args)
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/ext/viewcode.py", line 100, in doctree_read
    if not has_tag(modname, fullname, env.docname, refname):
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/ext/viewcode.py", line 75, in has_tag
    analyzer.find_tags()
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/__init__.py", line 117, in find_tags
    self.parse()
  File "/Users/peterjc/lib/python3.4/site-packages/sphinx/pycode/__init__.py", line 103, in parse
    raise PycodeError('parsing failed: %r' % exc)
sphinx.errors.PycodeError: parsing failed: NotImplementedError()
```

After:

```
$ more  /var/folders/x9/9z4wpg753_v3fvwq7qs1llhc0000gn/T/sphinx-err-9xh9tmvo.log
# Sphinx version: 1.7+
# Python version: 3.4.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:
#   reading sources... [ 35%] Bio.MaxEntropy
#   
#   reading sources... [ 36%] Bio.Medline
#   
#   reading sources... [ 36%] Bio.NMR
#   
#   reading sources... [ 36%] Bio.NMR.NOEtools
#   
#   reading sources... [ 37%] Bio.NMR.xpktools
#   
# Loaded extensions:
#   sphinx.ext.todo (1.7+) from /Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/ext/todo.py
#   sphinx.ext.viewcode (1.7+) from /Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/ext/viewcode.py
#   sphinx.ext.autodoc (1.7+) from /Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/ext/autodoc/__init__.py
#   alabaster (0.7.10) from /Users/peterjc/lib/python3.4/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/__init__.py", line 91, in parse
    parser.parse()
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 446, in parse
    self.parse_comments()
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 454, in parse_comments
    picker.visit(tree)
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 273, in visit
    super(VariableCommentPicker, self).visit(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 273, in visit
    super(VariableCommentPicker, self).visit(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 352, in visit_FunctionDef
    self.visit(child)
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 273, in visit
    super(VariableCommentPicker, self).visit(node)
  File "/Users/peterjc/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 280, in visit_Assign
    varnames = sum([get_lvar_names(t, self=self.get_self()) for t in node.targets], [])  # type: ignore  # NOQA
  File "/Users/peterjc/lib/python3.4/site-packages/Sphinx-1.7.dev20171010-py3.4.egg/sphinx/pycode/parser.py", line 280, in <listcomp>
    varn [...]

2017-10-12 14:17 UTC, tk0miya requested changes
LGTM. Could you add some testcases for this?

2017-10-12 20:36 UTC, peterjc commented
I will have to try reproduce this (should be fine as the source project is under version control), and then narrow down what is triggering this, and then make a minimal test case. I will try.

2017-10-13 13:00 UTC, peterjc commented
I narrowed it down to processing ``Bio.NMR.xpktools.rst `` containing:

```
Bio\.NMR\.xpktools module
=========================

.. automodule:: Bio.NMR.xpktools
    :members:
    :undoc-members:
    :show-inheritance:
```

which referred to https://github.com/biopython/biopython/blob/biopython-170/Bio/NMR/xpktools.py and with additional debugging, I eventually traced it to this line:

https://github.com/biopython/biopython/blob/biopython-170/Bio/NMR/xpktools.py#L277

```python
    [dict_list, label_line_list] = _read_dicts(fn_list, keyatom)
```

Normally that would be written as just:

```python
    dict_list, label_line_list = _read_dicts(fn_list, keyatom)
```

(and I will update it to do so). This explains where the unexpected list comes from, and confirms that parsing it the same way as a tuple is sensible.

2017-10-13 13:26 UTC, peterjc commented
Tests added :)

2017-10-13 14:02 UTC, tk0miya approved these changes

2017-10-13 14:04 UTC, merged

2017-10-13 14:04 UTC, tk0miya commented
Thank you for contribution and update!