a single string value for ``html_sidebars`` will be deprecated in 2.0
sphinx-doc/sphinx pull request #4178
Opened 2017-10-22 06:28 UTC by tk0miya

### Feature or Bugfix
- Deprecation

### Purpose
- `html_sidebars` accepts a string as a value to keep compatible with 0.x
- It does not emit any warnings for deprecation
- This emits deprecation warnings
- It will be deprecated in Sphinx-2.0

2017-10-24 09:22 UTC, jfbu requested changes
I think you mean deprecated at 1.7 and removed at 2.0 but I am not entirely sure...

2017-10-24 09:22 UTC, jfbu commented on CHANGES
> +
Do you mean something like:
```
* using a string value for :confval:`html_sidebars` is deprecated and only list
  values will be accepted at 2.0.
```

2017-10-24 09:22 UTC, jfbu commented on doc/config.rst
> +
It is not clear to me if you mean it is deprecated at 1.7 and removed at 2.0 or simply deprecated at 2.0.

2017-10-24 09:22 UTC, jfbu commented on sphinx/builders/html.py
> +
It seems you mean it is deprecated at 1.7 and will be removed at 2.0 ?

2017-10-30 04:43 UTC, tk0miya commented
Thank you for reviewing! I just updated.
What I meant is ...
* Emit deprecation warning at previous 2.0 (1.8 or 1.9?)
* Remove the feature at 2.0

2017-10-30 17:27 UTC, jfbu approved these changes
LGTM!

2017-10-31 01:37 UTC, merged

2017-10-31 01:37 UTC, tk0miya commented
Thank you for reviewing!