inspect: Sort dictionary keys when possible
sphinx-doc/sphinx pull request #4181
Opened 2017-10-22 18:58 UTC by mitya57

I got this bug report in Debian: https://bugs.debian.org/877637.

This pull request should fix that bug, now dictionary keys will be sorted if possible. If not, the generic `repr()` implementation is used.

This should also help for finding items in large dictionaries.

2017-10-23 13:26 UTC, tk0miya requested changes
Could you add testcase for this?

2017-10-23 20:18 UTC, mitya57 commented
@tk0miya Done.

2017-10-25 14:48 UTC, tk0miya approved these changes

2017-10-25 14:48 UTC, merged

2017-10-25 14:48 UTC, tk0miya commented
Thanks!