Add more EXAMPLES
sphinx-doc/sphinx pull request #4222
Opened 2017-11-06 22:48 UTC by vedranmiletic

Subject: Add more EXAMPLES

2017-11-11 06:28 UTC, tk0miya requested changes

2017-11-11 06:28 UTC, tk0miya commented on EXAMPLES
> +* RPM Packaging Guide: https://rpm-packaging-guide.github.io/
This has moved to asciidoc.

>The document itself was originally written in sphinx-doc reStructuredText and was published at http://rpm-guide.readthedocs.io/en/latest/.
>
>The document is now being converted to AsciiDoc and its draft is published at https://rpm-packaging-guide.github.io/. Note that this is a work in progress.

https://github.com/redhat-developer/rpm-packaging-guide

2017-12-16 17:22 UTC, vedranmiletic commented
Sorry for the delay. Added a couple more.

2017-12-17 12:59 UTC, tk0miya approved these changes

2017-12-17 12:59 UTC, tk0miya commented
Thanks!

2017-12-17 12:59 UTC, merged