viewcode does not import when viewcode_import is False
sphinx-doc/sphinx pull request #4237
Opened 2017-11-12 04:05 UTC by AWhetter

### Feature or Bugfix
- Bugfix and Feature

### Purpose
With the `viewcode` extension loaded, and `viewcode_import` set to `False`, `viewcode` will still attempt to load documented modules.

### Detail
- Fixes #4035 
- Added `viewcode_source_dirs` config variable to tell viewcode where to search for module source code (instead of sys.path).

### Relates
- #4035

2017-11-12 10:09 UTC, tk0miya commented
@shimizukawa could you check this please?
It seems the `viewcode_import` was introduced by you at e8b870de0cbaf724986b65de9552262ac253a6d2.

2017-11-12 10:12 UTC, tk0miya commented on sphinx/ext/viewcode.py
> +def _find_module_source(app, modname):
It seems this function does not uses whole of app object. How about taking `viewcode_source_dirs` as an argument instead? It makes this function much simple and testable.

2017-11-12 10:13 UTC, tk0miya requested changes
Could you add testcases for this feature please?

2017-11-14 20:18 UTC, AWhetter commented
This is ready for another review

2017-11-15 15:51 UTC, tk0miya approved these changes
LGTM

2018-01-10 01:16 UTC, AWhetter commented
@shimizukawa Conflicts are fixed so this is ready to be reviewed.

2018-02-03 21:14 UTC, AWhetter commented
@tk0miya This is been waiting for @shimizukawa to review it for a while. Please could it be merged?

2018-02-05 05:47 UTC, tk0miya commented
I'll take a look in this weekend. Please wait a little more.

2018-04-01 13:29 UTC, shimizukawa commented
Thanks for your PR.

> With the viewcode extension loaded, and viewcode_import set to False, viewcode will still attempt to load documented modules.

The `viewcode_import` option means:
```
If this is ``True``, viewcode extension will follow alias objects that
imported from another module such as functions, classes and attributes.
```
So, "loading documented modules by viewcode extension even if viewcode_import is False" is intended behavior. The config name `viewcode_import` is not nice. From the viewpoint of behavior, it seems better to call `viewcode_follow_imported_members`.

I think that it is the main change of this PR to fallback python source path to the new config value `viewcode_source_dirs` in situations where it is not possible to load Python source code from egg archive. However, since the interpretation around of `viewcode_import` is different as described above, I can not proceed with the review of this PR. Please create a PR that performs processing independent of `viewcode_import` config value. Thanks.

2018-04-01 13:29 UTC, closed without merging

2018-04-02 12:11 UTC, tk0miya commented
@shimizukawa Thank you for reviewing. I don't know the purpose of `viewcode_import`.

BTW, there are many ways to obtain original source code. Searching local directory (like this PR) is one of them. We can also refer zipped-source codes, GitHub, GitLab, and any other source code archive. To support these situation, I think emitting an event is extensible way to obtain original source code.
```
entry = env._viewcode_modules.get(modname, None)  # type: ignore
try:
    analyzer = ModuleAnalyzer.for_module(modname)
except Exception:
    # emit an event for handlers
    code = app.emit_firstresult('viewcode-sourcecode-missing', modname)

    if code is None:
        env._viewcode_modules[modname] = False  # type: ignore
        return
```

I don't know searching local directory is better way. But this idea can helps users by their own ways.

2018-04-05 18:53 UTC, AWhetter commented
I agree that using an event would be a much more extensible way of implementing this so I'll start working on that.
However I would say that the documentation is not clear about whether modules should be imported or not. The warning in the documentation says "viewcode_import imports the modules to be followed real location.". To me this would imply that if viewcode_import is False then the modules wouldn't be imported. It isn't explicit though.
I can implement an event without needing to depend on the configuration option, but I think we should at least make the documentation clearer?

2018-04-05 23:31 UTC, shimizukawa commented
+1 to "make the documentation clearer"