Fixes #4223: Report failing doctests in correct file at correct line
sphinx-doc/sphinx pull request #4243
Opened 2017-11-16 10:28 UTC by Zac-HD

### Purpose
Giving the wrong location for a failing test is not good.  When humans are running the test we can usually find the true location reasonably quickly and remember it, but bots aren't so great.  Reporting an accurate location will make it far easier and more reliable to automatically fix failing doctests in downstream projects.

### Detail
- When doctests are included in a file via `sphinx.ext.autodoc`, the failure message points to the actual source file instead of the document file.
- Auto-doc'd doctests *also* report their line number relative to start of file, instead of relative to `inspect.cleandoc` of the runtime docstring.
- Compensated for an off-by-one error in line number for all other doctests (hackish, because I couldn't find the origin)
- Added tests so that later changes (including better fixes) don't break doctest reporting again (at least in the same way)
- One commit of unrelated cleanup, where I did some refactoring while trying to trace the problem around.  No change in behaviour, just easier to read.

### Relates
- #4223, HypothesisWorks/hypothesis-python#962

@tk0miya, just let me know if there's anything you want changed - I'd like to get this merged in time for 1.6.6 so we can use it downstream 😄

2017-11-19 06:07 UTC, Zac-HD commented
@shimizukawa, would you be able to review this and let me know if there's anything you want changed?  I was careful to make reviewing commit-by-commit as helpful as possible, and I'd like to get this merged in time for 1.6.6 so we can use it downstream 😄

2017-11-30 06:20 UTC, Zac-HD commented
Ping @birkenfeld for review?

2017-12-05 05:03 UTC, Zac-HD commented
Ping @shimizukawa, @birkenfeld, @tk0miya for review?  

It's been four weeks since I reported this, almost three since I finished the patch, and while there's been no response I really would like to get this merged for 1.6.6 😕

2018-01-06 12:55 UTC, Zac-HD commented
Ping @tk0miya for review?  Two months is a really long time to hear nothing about a simple bugfix 😢

2018-01-08 14:58 UTC, tk0miya commented
Oh, sorry. I'll take a look in this week.

2018-01-13 11:22 UTC, tk0miya requested changes
Reviewed. could you check my comment please?
Please let me know if my comments are wrong. (Unfortunately, I'm not an expert of doctest module!)

In addition, please rebase this to master branch. This introduce an incompatible changes for some interface.

2018-01-13 11:22 UTC, tk0miya commented on sphinx/environment/__init__.py
> +                self.app, parsers=self.app.registry.get_source_parsers())
why is this changed? Personally I prefer before style.

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +        # type: (unicode, unicode, int, Dict, str) -> None
I think unicode is better for filename. because we can use multibyte characters for filename.

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +        assert filename is not None
Why do you assert here? You'd give default value `None` to filename argument. so this is very strange.

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +                    .rsplit(':docstring of ', maxsplit=1)[0]
Personally, I prefer to use parens to multiline statement. But either is fine.

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +                s = 'no code/output in %s block at %s'
`s` is meaningless name.  How about `msg`?

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +            # HACK HACK HACK - `node.line` has an off by one error somewhere
Is `HACK HACK HACK` comment important? I feel it is meaningless.

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +                # Fixing `node.document` in `sphinx.ext.autodoc.AutoDirective.run`
Note: `AutoDirective` is removed at master branch

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +                    del lines[:idx + len(source_lines) + 1]
why removing here? I guess this confuses the line number.

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +            # HACK HACK HACK - `node.line` has an off by one error somewhere
Ah, I noticed there is already same comment in doctest....

2018-01-13 11:22 UTC, tk0miya commented on sphinx/ext/doctest.py
> +            if ':docstring of ' in path.basename(node.source or ''):
I feel this block is a bit large. How about splitting into a function like following?
```
def get_source_lineno(node, source, cache={}):
    ...
```

I think main block should be simple and readable.

2018-01-13 11:54 UTC, Zac-HD commented
> Please let me know if my comments are wrong. (Unfortunately, I'm not an expert of doctest module!)  
> In addition, please rebase this to master branch. This introduce an incompatible changes for some interface.

Your comments look correct and helpful to me - thanks!

> In addition, please rebase this to master branch. This introduce an incompatible changes for some interface.

Sure.  I don't think I can retarget a pull request, but I will fix everything you commented on and create a new pull request based on master by this time tomorrow.

2018-01-13 12:31 UTC, tk0miya commented
Thanks, I'll wait for your new PR.

Note: I'll call feature freeze in nearly days. But we can arrange the X-Day a bit. So please let me know if you don't have time for work.

2018-01-14 13:24 UTC, closed without merging