autodoc: Use logging module to emit warnings
sphinx-doc/sphinx pull request #4325
Opened 2017-12-19 15:36 UTC by tk0miya

As a second step of refactoring autodoc, I propose that replacing `self.directive.warn()` to logging module.
As a side effect, the warning messages are not appeared on generated document when users specifies `keep_warnings = True` (see below).

![2017-12-20 0 35 52](https://user-images.githubusercontent.com/748828/34164770-c73afc74-e51d-11e7-8042-c3758bcf5cf5.png)

2017-12-19 20:46 UTC, stephenfin commented
> As a side effect, the warning messages are not appeared on generated document when users specifies keep_warnings = True (see below).

The image and this statement make conflicting statements. Are you saying that warnings *are* shown when the option is enabled, or that they *are not* shown despite the option being enabled. What was the previous behaviour and what is the behaviour now?

2017-12-19 20:49 UTC, stephenfin requested changes
I'm not entirely sure why we're doing this when we actually lose functionality. Surely we can figure out a way to emit warnings to output and _still_ use logging for `stdout`?

2017-12-19 20:49 UTC, stephenfin commented on sphinx/ext/autodoc/__init__.py
> +        logger.warning(msg, line=self.lineno)
I'm assuming this where is the issue lies. Why can't we call warnings and still return this?

2017-12-20 01:42 UTC, tk0miya commented
>The image and this statement make conflicting statements. Are you saying that warnings are shown when the option is enabled, or that they are not shown despite the option being enabled. What was the previous behaviour and what is the behaviour now?

Sorry for my poor description. I meant latter one.

* Current behavior (default): warnings are emitted to stderr only
* Current behavior (with `keep_warnings = True`): warnings are emitted to stderr and shown on the document
* New behavior: warnings are emitted to stderr only (even if `keep_warnings = True`)

The screenshot describes the second case.

>I'm not entirely sure why we're doing this when we actually lose functionality. Surely we can figure out a way to emit warnings to output and still use logging for stdout?

My final goal is simplify the implementation whole of autodoc. It is very complicated and strong-coupled. so it is very hard to understand and modify. To maintain the extension, I'd like to refactor it because there are no active maintainer for it. (In other word, we have to make it maintainable)

So this PR's goal is making the modules less-coupled. To do that, it uses `sphinx.util.logging` as a logger. I know this change make the functionality lost. But I think maintainability is more important for us.

In addition, I believe this feature is not important. because it is hard to notice the warnings on checking output on each build. For the purpose, the warnings on stderr is better. We also have `-W` (warn-is-error) option to notice them.

2017-12-22 18:17 UTC, stephenfin commented
Ok, thanks for the info. It seems a shame to lose functionality but I understand that the maintainability of this module is really important. I could volunteer to maintain it at some point in the future, but first I need to work on the other items I have.

I'm going to look through this one more time tomorrow to see what I think and then leave my final comments. It looks pretty good so far though 😄

2018-01-07 11:51 UTC, shimizukawa approved these changes
LGTM. 

I guess most users are unaware of this feature and it will not be necessary.

2018-01-07 11:54 UTC, tk0miya commented
@stephenfin It seems you're requesting changes. Is this intended?

2018-01-08 14:47 UTC, stephenfin commented
@tk0miya I wanted to review it once again given the additional information you provided. However, @shimizukawa has already reviewed it so I'll remove my review.

2018-01-08 14:48 UTC, stephenfin approved these changes
I can't see anything obvious and we can re-add the missing feature in the future if anyone misses it.

2018-01-08 14:57 UTC, tk0miya commented
Thanks.
I feel `keep_warnings` option is no longer needed. But, as you said, we can re-add it if anyone wants it.

I'll merge this after Travis says ok. (in this week we gets many timeouts from travis...)

2018-01-08 14:59 UTC, stephenfin commented
> I'll merge this after Travis says ok. (in this week we gets many timeouts from travis...)

Blame Spectre/Meltdown 😞

2018-01-08 15:03 UTC, tk0miya commented
Oh, I understand. That's too bad.

2018-01-08 15:03 UTC, merged

2018-01-08 15:03 UTC, tk0miya commented
Merged! Thank you for reviewing :-)