doc: Resolve inconsistent 'sphinx-apidoc' docs
sphinx-doc/sphinx pull request #4464
Opened 2018-01-20 13:21 UTC by stephenfin

The signature for the 'sphinx-apidoc' call differs between the man page and the output of 'sphinx-apidoc --help'. Resolve this by considering the 'sphinx-apidoc --help' output the canonical reference.

Signed-off-by: Stephen Finucane <stephen@that.guru>
Fixes: #4451

2018-01-20 15:52 UTC, tk0miya requested changes
LGTM with nits

2018-01-20 15:52 UTC, tk0miya commented on doc/man/sphinx-apidoc.rst
> +the directory where the generated sources are placed. Any *EXCLUDE_PATTERNS*\s
typo in `EXCLUDE_PATTERN *S*`.

2018-01-20 23:04 UTC, stephenfin commented on doc/man/sphinx-apidoc.rst
> +the directory where the generated sources are placed. Any *EXCLUDE_PATTERNS*\s
Done

2018-01-21 03:20 UTC, tk0miya approved these changes

2018-01-21 03:20 UTC, merged

2018-01-21 03:20 UTC, tk0miya commented
Thanks, merged :-)

2018-01-21 09:16 UTC, jfbu commented
@tk0miya shouldn't this possibly have been merged to 1.7-release?

2018-01-21 10:17 UTC, stephenfin commented
It probably should. You can cherry-pick this easily.

    git checkout 1.7-release
    git cherry-pick -x $COMMIT

2018-01-21 10:28 UTC, tk0miya commented
I don't mind. I've merged all fixes for our docs to master branch.