mathbase.py: ValueError: too many values to unpack
sphinx-doc/sphinx pull request #4487
Opened 2018-01-24 14:56 UTC by jschueller

I tried to use the parallel build option -j8 and got stuck in this function where the eqno variable is not unpacked:
This pattern is used in several other files, careful review needed.

```
def merge_domaindata(self, docnames, otherdata):
        # type: (Iterable[unicode], Dict) -> None
        for labelid, (doc, eqno) in otherdata['objects'].items():
            if doc in docnames:
                self.data['objects'][labelid] = doc
```
```
# Sphinx version: 1.6.6
# Python version: 3.5.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 92%] user_manual/_generated/openturns.coupling_tools.get_line_col .. user_manual/response_surface/_generated/openturns.FittingAlgorithm
#   
#   reading sources... [ 96%] user_manual/response_surface/_generated/openturns.FixedStrategy .. user_manual/response_surface/_generated/openturns.SVDMethod
#   
#   reading sources... [100%] user_manual/response_surface/_generated/openturns.SequentialStrategy .. user_manual/user_manual
#   
#   
#   
#   waiting for workers...
#   
# Loaded extensions:
#   sphinx.ext.doctest (1.6.6) from /home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/doctest.py
#   alabaster (0.7.10) from /home/schueller/.local/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinx.ext.todo (1.6.6) from /home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.6.6) from /home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.autodoc (1.6.6) from /home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/autodoc.py
#   execforresourcemap_directive (0) from /home/schueller/projects/openturns/schueller2/build/python/src/sphinx_build/sphinxext/execforresourcemap_directive.py
#   sphinx.ext.autosummary (1.6.6) from /home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.imgmath (1.6.6) from /home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/imgmath.py
#   numpydoc (unknown version) from /home/schueller/.local/lib/python3.5/site-packages/numpydoc/__init__.py
#   matplotlib.sphinxext.plot_directive (unknown version) from /home/schueller/.local/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py
Traceback (most recent call last):
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 329, in build_update
    'out of date' % len(to_build))
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 342, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 599, in update
    self._read_parallel(docnames, self.app, nproc=self.app.parallel)
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 653, in _read_parallel
    tasks.join()
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/util/parallel.py", line 112, in join
    self._join_one()
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/util/parallel.py", line 123, in _join_one
    self._result_funcs.pop(tid)(self._args.pop(tid), result)
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 642, in merge
    self.merge_info_from(docs, env, app)
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 360, in merge_info_from
    domain.merge_domaindata(docnames, other.domaindata[domainname])
  File "/home/schueller/.local/lib/python3.5/site-packages/sphinx/ext/mathbase.py", line 68, in merge_domaindata
    for labelid, (doc, eqno) in otherdata['objects'].items():
ValueError: too many values to unpack (expected 2)
```

Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2018-01-25 15:26 UTC, tk0miya requested changes
Could you rebase this to stable branch?

2018-01-25 15:26 UTC, tk0miya commented on sphinx/ext/mathbase.py
>                  self.data['objects'][labelid] = doc
I think fixing this line is better like following:
```
self.data['objects'][labelid] = (doc, eqno)
```

I know your fix also works. But the variable name is not good (`doc` is a tuple of doc and eqno).

2018-01-25 15:46 UTC, jschueller commented on sphinx/ext/mathbase.py
>                  self.data['objects'][labelid] = doc
No, when I debugged this I think otherdata['objects'].items() was a tuple of list of two strings: the label and the file, so I didnt see any eqno, even as a string.

2018-01-25 16:58 UTC, tk0miya commented on sphinx/ext/mathbase.py
>                  self.data['objects'][labelid] = doc
I guess the `otherdata` was already broken on last `merge_domaindata` call (by this line).

2018-01-31 00:29 UTC, tk0miya commented
Merged instead #4526.
Thank you for your work!

2018-01-31 00:29 UTC, closed without merging