autodoc: prefer _MockImporter over other importers in sys.path
sphinx-doc/sphinx pull request #4491
Opened 2018-01-24 16:39 UTC by Emantor

Subject: Add _MockImporter in front of other importers in sys.meta_path

### Feature or Bugfix
- Bugfix

### Purpose
In case we want to mock modules which are actually available in the current
environment, we need to add the _MockImporter before other importers. We ran
into this problem in our application, where importing the existing modules
caused side effects which were not fixed by autodoc_mock_imports.

### Detail
-/-

### Relates
-/-

This is debatable, i am not sure whether this is the intended behaviour of autodoc_mock_imports. At least from my point of view, the documentation implied that it not only mocked missing modules, but in sys.path available modules as well.

A backport to stable would be needed as well. Thanks for your time and work on sphinx 👍

2018-01-25 16:27 UTC, tk0miya commented
@shimizukawa could you give us comments?

Note: The failure on Travis is not related with this PR. It will be resolved with master HEAD.

2018-01-25 23:33 UTC, shimizukawa commented
Actually, I did not specifically consider hook order. I think it's okay to hook before the defaults. If user don't specify mock target, hook will not do anything, and if user explicitly specify target, there is an intention to mock even existing modules.

2018-01-25 23:33 UTC, shimizukawa approved these changes

2018-01-27 03:29 UTC, tk0miya requested changes
@Emantor could you rebase this to 1.7-release branch? Then I'll merge this soon.
Thanks,

2018-01-27 12:52 UTC, Emantor commented
Rebased, should be ready to merge after tests 👍

2018-01-27 13:05 UTC, tk0miya approved these changes

2018-01-27 13:05 UTC, merged

2018-01-27 13:05 UTC, tk0miya commented
Thank you for quick response.
Merged!