fix broken links on pypi page
sphinx-doc/sphinx pull request #4607
Opened 2018-02-12 21:57 UTC by thijstriemstra

The pypi page, e.g. https://pypi.python.org/pypi/Sphinx/1.7.0, refers to a local github page which it obviously cannot resolve.

2018-02-13 00:40 UTC, tk0miya requested changes
LGTM!
Could you rebase (or cherry-pick) this into 1.7 branch?
Then this will be applied to next release.

2018-02-13 00:53 UTC, thijstriemstra commented
No i screwed up.. bleh

2018-02-13 15:35 UTC, tk0miya approved these changes

2018-02-13 15:36 UTC, merged

2018-02-13 15:36 UTC, tk0miya commented
Okay, I'll cherry-pick this from my side.
Thank you for contribution!

2018-02-20 02:12 UTC, thijstriemstra commented
thanks!