Fix #4630: Have order on msgids in sphinx.pot deterministic
sphinx-doc/sphinx pull request #4634
Opened 2018-02-17 05:20 UTC by cocoatomo

ref. #4630 

### Feature or Bugfix
- Bugfix

### Purpose
- Have order on msgids in sphinx.pot deterministic

### Detail
- Have order on msgids in sphinx.pot deterministic

2018-02-17 05:40 UTC, tk0miya requested changes
Could you rebase to 1.7 please?
And please add a testcase if possible.

2018-02-17 05:40 UTC, tk0miya commented on sphinx/builders/gettext.py
> +        files.sort()
Note: I think this is responsibility of `_collect_templates()`. On the other hand, a compatibility is another topic of maintenance. So I'd like to go with as is.

2018-02-18 13:21 UTC, cocoatomo commented on sphinx/builders/gettext.py
> +        self.metadata = OrderedDict()  # type: Dict[unicode, List[Tuple[unicode, int, unicode]]]
@tk0miya flake8 reports E501 line too long. Do you have any workaround for this error?
ref. https://travis-ci.org/sphinx-doc/sphinx/jobs/342938730#L495

2018-02-18 13:24 UTC, cocoatomo commented on sphinx/builders/gettext.py
> +        self.metadata = OrderedDict()  # type: Dict[unicode, List[Tuple[unicode, int, unicode]]]
Could I define a type alias for the type of metadata in the body of `if TYPE_CHECKING:` statement,
and use that type alias here?

2018-02-18 13:59 UTC, tk0miya commented on sphinx/builders/gettext.py
> +        self.metadata = OrderedDict()  # type: Dict[unicode, List[Tuple[unicode, int, unicode]]]
Please mark as `# NOQA` at tail.

2018-02-18 14:02 UTC, tk0miya requested changes
LGTM with nits

2018-02-18 14:02 UTC, tk0miya commented on tests/test_build_gettext.py
> +@pytest.mark.sphinx('gettext', testroot='intl-template')
Could you rename this to `test-gettext-template`?
This is a bug of gettext builder (extracting part), not internationalization (applying part).

2018-02-19 01:15 UTC, cocoatomo commented
Just finished fixing pointed issues.

2018-02-19 01:43 UTC, tk0miya approved these changes

2018-02-19 01:48 UTC, merged

2018-02-19 01:48 UTC, tk0miya commented
Merged!
Thank you for your contribution!