Fix error reporting for parameterless ImportErrors
sphinx-doc/sphinx pull request #4653
Opened 2018-02-19 20:52 UTC by adam-azarchs

In some cases, a module may raise an ImportError without any arguments, e.g.

if not_allowed():
    raise ImportError

In this case, the exception has no args.  This is bad practice, but it happens.

Currently, autodoc will crash with

IndexError: tuple index out of range

Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2018-02-20 12:02 UTC, tk0miya requested changes
+1; could you rebase this into 1.7 branch?
Then I will merge this soon.

2018-02-20 20:25 UTC, adam-azarchs commented
Rebased to 1.7 branch.

2018-02-21 00:51 UTC, tk0miya approved these changes

2018-02-22 15:11 UTC, merged

2018-02-22 15:14 UTC, tk0miya commented
Merged. Thanks!