codecov: Disable status checks
sphinx-doc/sphinx pull request #4755
Opened 2018-03-19 12:24 UTC by stephenfin

We don't currently care if a commit changes our coverage metrics, so we
can disable the status checks that would enforce that.

Signed-off-by: Stephen Finucane <stephen@that.guru>
Fixes: #4738

2018-03-19 13:01 UTC, tk0miya requested changes
Could you rebase this onto 1.7 branch?

2018-03-20 15:34 UTC, stephenfin commented
> Could you rebase this onto 1.7 branch?

Sure. Done.

2018-03-21 02:46 UTC, tk0miya approved these changes

2018-03-21 02:47 UTC, merged

2018-03-21 02:47 UTC, tk0miya commented
Merged. Thank you always.
I'll take a look another PR soon!

2018-03-21 13:31 UTC, stephenfin commented
> I'll take a look another PR soon!

I'd appreciate that :smile: