Wrap graphviz diagrams in <div class="graphviz">
sphinx-doc/sphinx pull request #4866
Opened 2018-04-20 06:20 UTC by goerz

The graphviz extension is modified to wrap the `<img>` and `<object>`
tags it creates for diagrams in the png and svg formats in an additional
`<div class="graphviz">...</div>` tag. This allows to apply additional
CSS styling to the the diagrams that cannot be applied to `<img>` and
`<object>` directly. Most notably,

    div.graphviz {
      overflow: auto;
    }

would be a useful style that the standard themes might consider.

In any case, it would allow users to add custom CSS code to their
project that gets around the problems with inheritance-diagrams
discussed in https://github.com/sphinx-doc/sphinx/issues/4865

The tests for the `grahviz` and `inheritance_diagram` have been modified
to test for the presence of the additional `<div>` tag.

Closes #4865

2018-04-20 06:34 UTC, goerz commented
http://qnet.readthedocs.io/en/latest/symbolic_algebra.html illustrates the result of the applied patch, together with the proper custom CSS to solve #4865: it has scrollable diagrams with proper click-maps

2018-04-20 06:37 UTC, goerz commented
Travis reports

    ./sphinx/ext/graphviz.py:301:96: E501 line too long (111 > 95 characters)
    ./sphinx/ext/graphviz.py:306:96: E501 line too long (98 > 95 characters)

Would you like me to fix this?

2018-04-20 15:16 UTC, tk0miya requested changes
LGTM with nits.

2018-04-20 15:16 UTC, tk0miya commented on tests/test_ext_graphviz.py
> +    #assert re.search(html, content, re.S)
Why did you comment out here?

2018-04-20 15:16 UTC, tk0miya commented on sphinx/ext/graphviz.py
> +                    outfn + '.map', mapfile.read(), dot=code)
Why did you fold this line?

2018-04-20 15:16 UTC, tk0miya commented on sphinx/ext/graphviz.py
> +                        (fname, alt, imgmap.id, imgcss))
I feel additional `self.body.append` is better:
```
+ self.body.append('<div class="graphviz">')
  self.body.append('<img src="%s" alt="%s" usemap="#%s" %s/>' %
                   (fname, alt, imgmap.id, imgcss))
+ self.body.append('</div>\n')
```

What do you think?

2018-04-20 16:10 UTC, goerz commented on tests/test_ext_graphviz.py
> +    #assert re.search(html, content, re.S)
While fixing the tests, I went through the different `assert`s in the tests one by one, and then I forgot to un-comment the last one. Good catch! Fixed.

2018-04-20 16:12 UTC, goerz commented on sphinx/ext/graphviz.py
> +                    outfn + '.map', mapfile.read(), dot=code)
The first time I pushed, TravisCI complained about some overlong lines. In the process of fixing these , I also folded the line in question, even through it wasn't over Travis' 95 character limit. But I suppose you're right, and I shouldn't do "PEP8 cleanups" on lines not directly related to my patch. Reverted.

2018-04-20 16:16 UTC, goerz commented on sphinx/ext/graphviz.py
> +                        (fname, alt, imgmap.id, imgcss))
I agree, your solution looks cleaner. I've changed both the png and the svg case to use additional appends. I'll force-push a new version with all of the changes above in a minute.

2018-04-20 16:47 UTC, goerz commented
@tk0miya I just force-pushed a new version with all your requested changes. This should be ready to merge now. Thanks for the review!

2018-04-20 17:48 UTC, tk0miya approved these changes
Thank you for quick work.
LGTM!

2018-04-21 02:27 UTC, goerz commented
Actually, can you hold off on merging for a minute? I found the tests do not cover the inheritance-diagram with SVG.

Also, for consistency, it would probably best if the SVG `<object>` had the same `class="inheritance"` attribute that the PNG `<img>` has.

2018-04-21 05:43 UTC, tk0miya commented
+1 again.
I'll merge this within a week if no objection.

2018-04-29 13:22 UTC, merged

2018-04-29 13:27 UTC, tk0miya commented
Merged. Thank you for contribution!