Remove usage of internal shorthandoff variable from LaTeX writer
sphinx-doc/sphinx pull request #5045
Opened 2018-06-05 16:40 UTC by jfbu

Subject: brings simplicity by removing shorthandoff internal variable from LaTeX writer

Neither bugfix nor feature, but refactoring.

Pros: simplified code

Cons: now, some LaTeX code gets exported to all Sphinx produced LaTeX documents ; in the past it was incorporated only language conf val was set to certain languages. Code was not included for Japanese, or when latex_engine was lualatex xelatex and document used polyglossia, or when engine was pdflatex but certain languages were used.

But the TeX code is crafted to be usable in all circumstances (platex incorporates e-TeX extensions, hence `\ifdefined` can be used).

### Relates
- #5040 

see https://github.com/sphinx-doc/sphinx/pull/5040#discussion_r193122150

**attention** this PR includes no deprecation and simply removes the internal variable. Maybe this is bad...

2018-06-06 13:00 UTC, tk0miya requested changes
LGTM with nits

2018-06-06 13:00 UTC, tk0miya commented on sphinx/writers/latex.py
> -    def get_shorthandoff(self):
Please follow our deprecation rule. I know this is minor and internal API. But sometimes extensions uses such an API. So let deprecate this before removing.

* Add deprecation warnings `warnings.warn()`
* Update CHANGES and deprecation list on `doc/extdev/index.rst`

2018-06-06 17:24 UTC, jfbu commented
@tk0miya updated. I set removal of ``ExtBabel.get_shorthandoff()`` at 2.0, perhaps should be 3.0 ?

I had not noticed during merging of #5040 that there was also your d17f3955a5546a9eb30ee9161946f8bb900441c5 which fixed #4877. This partially reverts it.

Should also ``latex_elements['shorthandoff']`` get deprecated before some future removal? Currently I have left it untouched but added `SHORTHANDOFF` constant.

2018-06-07 15:47 UTC, tk0miya commented
>I set removal of ExtBabel.get_shorthandoff() at 2.0, perhaps should be 3.0 ?

In our deprecation policy, it should be removed after a release. So 3.0 would be better.
http://www.sphinx-doc.org/en/master/devguide.html#deprecation-policy

>Should also latex_elements['shorthandoff'] get deprecated before some future removal? Currently I have left it untouched but added SHORTHANDOFF constant.

`shorthandoff` is only used in `BEGIN_DOC` variable. So I think the removal does not effect to templates. In addition, the template variable will be replaced with empty string even if user templates refers it. Hence the removal of the key is okay to me.

2018-06-07 16:33 UTC, jfbu commented
> 
> 
> >     I set removal of ExtBabel.get_shorthandoff() at 2.0, perhaps should be 3.0 ?
> 
> 
> In our deprecation policy, it should be removed after a release. So 3.0 would be better.
> http://www.sphinx-doc.org/en/master/devguide.html#deprecation-policy
> 

Done

> >     Should also latex_elements['shorthandoff'] get deprecated before some future removal? Currently I have left it untouched but added SHORTHANDOFF constant.
> 
> 
> shorthandoff is only used in BEGIN_DOC variable. So I think the removal does not effect to templates. In addition, the template variable will be replaced with empty string even if user templates refers it. Hence the removal of the key is okay to me.

I simply removed mention of it from doc/usage/configuration.rst.

Memo #4000 is impacted by this. It could be possible to move SHORTHANDOFF contents entirely to LaTeX template, then we can remove `latex_elements['shorthandoff']`. Currently I keep it to keep former behaviour that for example Japanese does nothing special.

2018-06-08 17:34 UTC, tk0miya approved these changes
LGTM. Thank you for update!

2018-06-08 18:30 UTC, jfbu commented
@tk0miya thanks,  merging.

2018-06-08 18:30 UTC, merged