change format_args to prefer annotations from typing.get_type_hints
sphinx-doc/sphinx pull request #5280
Opened 2018-08-09 19:36 UTC by terencehonles

Subject: change format_args to prefer annotations from typing.get_type_hints

### Feature or Bugfix
- Bugfix

### Purpose

The current code looks for the pattern:

```python
class Node:
    def parent(self) -> 'Node': pass
```

This change allows more complex forward references:

```python
class Node:
    def children(self) -> Set['Node']: pass
```

2018-08-10 12:45 UTC, tk0miya requested changes
LGTM.
I'd like to merge this into 1.7 branch. Could you rebase this please?

2018-08-10 18:59 UTC, terencehonles commented
@tk0miya done!

2018-08-13 12:19 UTC, tk0miya approved these changes

2018-08-13 12:20 UTC, tk0miya commented
Thank you for quick work!

2018-08-13 12:20 UTC, merged