Make generated texinfo files reproducible by sorting the anchors
sphinx-doc/sphinx pull request #5359
Opened 2018-08-27 07:39 UTC by mitya57

This fixes the problem with reproducible builds originally reported in Debian: https://bugs.debian.org/907352.

2018-08-29 13:27 UTC, tk0miya requested changes
LGTM with nits

2018-08-29 13:27 UTC, tk0miya commented on tests/test_build_texinfo.py
> +        texi_source = texi_file.read(8000)
We usually use `path.text()` to read the content on testing scripts. Then you don't need to open a file.
Could you use `(app.outdir / 'SphinxTests.texi').text(encoding='utf8')` instead?

2018-08-30 10:21 UTC, mitya57 commented
@tk0miya Fixed! The Python 3.5 build on Travis got stuck, can you please retry it?

2018-08-30 14:46 UTC, tk0miya approved these changes

2018-08-30 14:46 UTC, merged

2018-08-30 14:46 UTC, tk0miya commented
Merged. Thank you always your support!