Ensure frozetset object descriptions are reproducible
sphinx-doc/sphinx pull request #5388
Opened 2018-09-05 11:27 UTC by lamby

Whilst working on the Reproducible Builds effort [0], we noticed
that sphinx could generate output that is not reproducible.

In particular, the rendering of `frozenset` objects in default
arguments and elsewhere is currently non-determinstic.

For example:

    frozenset(['a', 'b', 'c'])

Might be rendered as any of:

    frozenset({'a', 'b', 'c'})
    frozenset({'a', 'c', 'b'})
    frozenset({'b', 'a', 'c'})
    frozenset({'b', 'c', 'a'})
    frozenset({'c', 'a', 'b'})
    frozenset({'c', 'b', 'a'})

Patch attached that sorts the contents of frozensets whilst rendering.
This is parallel to the `dict` and `set` type logic

  [0] https://reproducible-builds.org/

Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2018-09-05 13:53 UTC, tk0miya requested changes
LGTM with nits.
Could you rebase this into 1.8 branch?
Then I'll merge this soon.

2018-09-05 14:59 UTC, lamby commented
Rebased against `1.8` branch.

2018-09-05 16:07 UTC, tk0miya approved these changes

2018-09-05 16:08 UTC, merged

2018-09-05 16:08 UTC, tk0miya commented
Thanks a lot!

2018-09-10 09:44 UTC, lamby commented
Thanks @tk0miya. Do you know when this might hit a release? :)

2018-09-10 13:12 UTC, tk0miya commented
It will be released within a few days. Please watch #4986.