Display meaningful names in type annotations for mocked objects
sphinx-doc/sphinx pull request #5394
Opened 2018-09-07 12:29 UTC by maxme1

Consider this snippet:
```python
from mocked_module import x

def f(arg: x.y):
    pass
```

The resulting documentation will be something like
```
f(arg: <sphinx.ext.autodoc.importer._MockObject at 0x54313513513>)
```
This patch fixes this:
```
f(arg: mocked_module.x.y)
```

Same goes for mocked superclass names in classes documentation.

### Feature or Bugfix
- Feature

2018-09-09 09:02 UTC, tk0miya requested changes
Great!
Could you add a testcase to `test_autodoc` also please?

2018-09-09 18:24 UTC, maxme1 commented
Yeah, sure

2018-11-11 05:59 UTC, shimizukawa approved these changes
LGTM. (please add test_autodoc as tk0miya mentioned).

2018-11-15 07:06 UTC, maxme1 commented
Oh, sorry. I totally forgot about it. I'll push the tests in a few days.

2019-02-11 03:32 UTC, merged

2019-02-11 03:34 UTC, tk0miya commented
Just merged.
Thank you for your contribution!