Fix AttributeError in ExtensionError
sphinx-doc/sphinx pull request #5401
Opened 2018-09-08 17:35 UTC by jdufresne

Subject: Fix AttributeError in ExtensionError

### Feature or Bugfix
- Bugfix

### Purpose

In Python 3, the attribute BaseException.message doesn't exist.

```
$ python3
>>> from sphinx.errors import ExtensionError
>>> e = ExtensionError('foo')
>>> repr(e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sphinx/sphinx/errors.py", line 65, in __repr__
    return '%s(%r)' % (self.__class__.__name__, self.message)
AttributeError: 'ExtensionError' object has no attribute 'message'
```

2018-09-09 08:21 UTC, tk0miya requested changes
LGTM.
Could you rebase this to 1.7 branch? Then I'll merge this soon.

2018-09-09 10:24 UTC, tk0miya commented
Oh, sorry. My last comment was wrong.
We'll release 1.8.0 soon, and development of 1.7.x will be stopped. So please rebase this into **1.8** branch.

Thanks,

2018-09-09 19:13 UTC, jdufresne commented
Rebased to 1.8

2018-09-10 11:40 UTC, tk0miya approved these changes

2018-09-10 11:40 UTC, merged

2018-09-10 11:40 UTC, tk0miya commented
Thanks!