Remove use of Python 2 os.getcwdu()
sphinx-doc/sphinx pull request #5402
Opened 2018-09-08 20:06 UTC by jdufresne

os.getcwdu() is Python 2 only. It was removed from Python 3. As Sphinx
is now Python 3 only, can remove the workaround.

```
$ python2 -c 'import os; print(os.getcwdu)'
<built-in function getcwdu>
$ python3 -c 'import os; print(os.getcwdu)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'getcwdu'
```

2018-09-09 08:28 UTC, tk0miya requested changes
LGTM with nits

2018-09-09 08:28 UTC, tk0miya commented on sphinx/util/osutil.py
> -def getcwd():
To keep compatibility, please don't remove this. Unfortunately some extensions might has used this.
To do that, please do following procedure:

1. Show deprecation message using `warnings.warn()` and `RemovedInSphinx40Warning` inside this function.
2. Move this to `sphinx.util.compat`.
3. Import it on this module.

2018-09-09 18:37 UTC, jdufresne commented
> 2. Move this to sphinx.util.compat.
> 3. Import it on this module.

Unfortunately, this creates a circular import. `sphinx.util.compat` has the import `from sphinx.util import import_object` and `sphinx/util/__init__.py` has the import `from sphinx.util.osutil import fs_encoding`. So `sphinx/util/osutil.py` can't also import `sphinx.util.compat` as the top level.

I have restored `sphinx.util.osutil.getcwd()` with a deprecation warning.

2018-09-10 11:42 UTC, tk0miya approved these changes

2018-09-10 11:42 UTC, merged

2018-09-10 11:42 UTC, tk0miya commented
Thank you for quick work! And sorry for my wrong comment.