Remove unused argument, content, from guess_mimetype
sphinx-doc/sphinx pull request #5403
Opened 2018-09-08 21:21 UTC by jdufresne

Unused since its introduction in be261ed71ec797d32fe88dae1acf73adb2b33c8e.

2018-09-09 08:39 UTC, tk0miya commented
OMG. It's not my intension. We should use it for remote images...

2018-09-09 08:44 UTC, tk0miya commented
Okay, I understand why I did not use the argument. Surely, it is not needed because all images are passed by file, not a string.

As commented other PR, could you add deprecation message instead of removal?
```
if content:
    warning.warn('content argument of guess_mimetype() is deprecated', RemovedInSphinx30Warning)
```

2018-09-09 08:44 UTC, tk0miya requested changes
LGTM with nits.
In addition, it would be better to rebase this into 1.8 branch.

Thanks,

2018-09-09 19:34 UTC, jdufresne commented
- Changed removal to deprecation with a warning (restored tests).
- Rebased to 1.8

2018-09-10 11:43 UTC, tk0miya approved these changes

2018-09-10 11:43 UTC, merged

2018-09-10 11:43 UTC, tk0miya commented
Thank you for your contribution!