Remove use of six.binary_type; use bytes instead
sphinx-doc/sphinx pull request #5481
Opened 2018-09-23 22:15 UTC by jdufresne

2018-09-24 00:05 UTC, tk0miya commented
Thank you always :-)

2018-09-24 00:09 UTC, tk0miya approved these changes
Note: I'll merge this after all tests passed.

2018-09-24 00:25 UTC, tk0miya commented
oh, sorry. I'd failed to merge accidentally.

2018-09-24 00:36 UTC, tk0miya commented on sphinx/cmd/build.py
> +        if likely_encoding and isinstance(val, bytes):
Does argparse return bytes object in py3? I'll take a look later.

2018-09-24 00:36 UTC, tk0miya commented on sphinx/cmd/quickstart.py
> +        if isinstance(value, bytes):
This is also. Does `input()` return bytes object?

2018-09-24 00:36 UTC, tk0miya commented on sphinx/config.py
>                                'Please use Unicode strings, e.g. %r.'), name, u'Content')
I think this warning is not meaningful for py3.
This will be warned if users writes binary-string in conf.py like `b'Sphinx'`

2018-09-24 00:36 UTC, tk0miya commented on sphinx/ext/apidoc.py
> +        if isinstance(args.release, bytes):
Same as quickstart.

2018-09-24 00:36 UTC, tk0miya commented on sphinx/ext/doctest.py
> +        if isinstance(text, bytes):
I don't know that doctest gives bytes object or not. But I suppose this is not needed. binary object is mainly used on IO boundary.

2018-09-24 00:38 UTC, tk0miya commented
In this morning, I don't have time for review anymore. I'll take a look this again later.
Thank you for your work!

2018-09-24 02:16 UTC, jdufresne commented
Thanks for the review @tk0miya. I agree with your analysis, those identified type checks are no longer necessary under Python 3. I've rebased and resolved the merged conflicts. I've removed those type checks, which resulted in deprecating `check_unicode()`. All additional feedback is welcome. Thanks!

2018-11-02 01:56 UTC, jdufresne commented
Rebased to resolve merge conflicts.

2018-11-11 14:25 UTC, tk0miya requested changes
LGTM with nits

2018-11-11 14:25 UTC, tk0miya commented on sphinx/ext/doctest.py
> +            self.outfile.write(text)
This line is wrong indented.

2018-11-11 14:25 UTC, tk0miya commented on sphinx/util/__init__.py
>  def force_decode(string, encoding):
I think this function will become meaningless. Let's deprecate this in another PR :-)

2018-11-11 14:25 UTC, tk0miya commented on sphinx/config.py
>                                'Please use Unicode strings, e.g. %r.'), name, u'Content')
Ah, sorry. This function was already deprecated. So no more change is needed.

2018-11-11 17:09 UTC, jdufresne commented
Good catch. I fixed the indentation.

2018-11-12 02:04 UTC, tk0miya approved these changes
LGTM!

2018-11-12 03:29 UTC, jdufresne commented
Rebased to resolve merge conflicts.

2018-11-12 13:45 UTC, merged

2018-11-12 13:45 UTC, tk0miya commented
Merged. Thank you for rebasing :-)