Correct intro.rst with regards to required Python version
sphinx-doc/sphinx pull request #5484
Opened 2018-09-24 02:31 UTC by jdufresne

(Sorry, I missed this one in #5477.)

2018-09-24 23:40 UTC, tk0miya requested changes
Could you also updated related text?

2018-09-24 23:40 UTC, tk0miya commented on doc/intro.rst
> +Jinja2_ libraries. Sphinx should work with docutils version 0.10 or some (not
Since 2.0, we updated requirement to docutils-0.12 or above.

2018-09-24 23:40 UTC, tk0miya commented on doc/intro.rst
> +support, you must also install the Pygments_ library.
Now pygments has been added to requirements list. So this sentence is not needed!

2018-09-25 00:19 UTC, jdufresne commented
Done. Let me know if that is what you had in mind. I can do any other edits if needed.

2018-09-29 12:36 UTC, tk0miya approved these changes

2018-09-29 12:36 UTC, tk0miya commented
Thank you always :-)

2018-09-29 12:36 UTC, merged