LaTeX: add styling to general index, similar to domain indices
sphinx-doc/sphinx pull request #5583
Opened 2018-10-31 18:40 UTC by jfbu

Closes: #5579. Also closes #5576.

With this here is for example how CPython 3.7 library.pdf renders:

![capture d ecran 2018-10-31 a 19 16 38](https://user-images.githubusercontent.com/2589111/47810377-72995980-dd43-11e8-97fe-09f67a404015.png)

and 

![capture d ecran 2018-10-31 a 19 16 52](https://user-images.githubusercontent.com/2589111/47810389-7c22c180-dd43-11e8-827a-010c1f6e380c.png)

Compare to the images posted at #5579.

About the underscore character, it shows fine because CPython uses xelatex for pdf builds and this means another font is used than the Sphinx default `Courier`. Unfortunately the Courier font used by default for monospace font by Sphinx has an underscore glyph which creates continuous lines... one can see that in Sphinx own pdf doc, see top left.

![capture d ecran 2018-10-31 a 19 09 22](https://user-images.githubusercontent.com/2589111/47810592-f81d0980-dd43-11e8-860a-ca2dd007ecee.png)

Sphinx own doc uses `\footnotesize\raggedright` which explains smaller size.

It fixes #5576 in a way different from #5577: the regex argument of `visit_index()` in latex.py is used for something completely different: separate from the index a parenthesized comment ("extra") and style it especially as in Python Module Index.

Another slightly breaking change is in `\sphinxstyleindexextra`, the parentheses stay upright. I feel it looks better. (I will do more detailed review some time later)

2018-11-01 10:25 UTC, jfbu commented on sphinx/texinputs/sphinx.sty
> +\def\sphinxstyleindexextra   #1{ (\emph{#1})}
I moved the parentheses outside the scope of `\emph`. imho, it looks better this way.

2018-11-01 10:25 UTC, jfbu commented on sphinx/texinputs/sphinx.sty
> +\protected\def\spxextra#1{#1}% will get \let to \sphinxstyleindexextra in index
The `visit_index()` from LaTeX writer will use `\spxentry` and `\spxextra`, this makes smaller LaTeX file than using everywhere `\sphinxstyleindexentry`, `\sphinxstyleindexextra`. The macros need to be `\protected` because they are used inside `\index{}` macro, and this may occur for example in a `tabulary` environment (same reason why verbatim can't be used inside `tabulary`).

2018-11-01 10:25 UTC, jfbu commented on sphinx/texinputs/sphinx.xdy
>  (markup-locref :open "\hyperpage{" :close "}" :attr "default")
Initially I had also added a `spxpage` attribute so that one would would have `\spxpage{\hyperpage{37}}` for example, allowing to style the page number. But this would mean all `\index` macros would end in `\index{...|spxpage]` increasing size and overhead of LaTeX file. Then I thought about simply modifying the `"default"` above to do `...\spxpage{\hyperpage{...`, but this method would have been xindy-only. Only the `\index{....|spxpage}` would have also affected `makeindex` way.

In the end I dropped this: it is always possible if wanted to style the index page number at LaTeX macro level by modifying `\hyperpage`.

2018-11-01 10:25 UTC, jfbu commented on sphinx/texinputs/sphinx.xdy
> +\let\spxextra\sphinxstyleindexextra
Regarding `\sphinxstyleindexentry` and `\sphinxstyleindexextra` they are the macros used by the LaTeX writer for the mark-up associated with domain indices. The method above allows same mark-up also in general index. But it means too that separate customization will mean from user some extra measure. One method would add to preamble some definition of `\stylegeneralindexentry`,  `\stylegeneralindexextra` macros, and insert `\let\sphinxstyleindexentry\stylegeneralindexentry\let\...` before the final index via the `latex_elements` `'printindex'` key.

I also hesitated about moving these `\let` to the definition of the `sphinxtheindex` environment, but the latter is used for all indices, including domain indices, where `\spxentry` and `\spxextra` do not arise.

2018-11-01 10:25 UTC, jfbu commented on sphinx/writers/latex.py
> +    def visit_index(self, node, extrare=re.compile(r'^(.*\S)\s+\(([^()]*)\)\s*$')):
This is breaking change for extensions who counted on the third argument of `visit_index` to be the regex allowing to recognize semi-colon. A priori this was not used as public API? so I felt there is no problem using this for something completely different.

The aim of the regex is to identify strings of the type `"text (extra in parentheses)"`. Then the `extra in parenthesis` will be styled especially. This is a new feature which has drawback that sometimes the parentheses were used by Sphinx user with a somewhat different intent. I found an example in Sphinx own docs, [at line 125 of doc/man/sphinx-quickstart.rst](https://github.com/sphinx-doc/sphinx/blob/master/doc/man/sphinx-quickstart.rst):

```
.. option:: --use-make-mode (-m), --no-use-make-mode (-M)
```

In this case this will produce in LaTeX file:

```
\index{--use-make-mode (-m), --no-use-make-mode (-M)@\spxentry{--use-make-mode (-m), --no-use-make-mode}\spxextra{-M}!...}
```

which causes the `-M` to be emphasized. In general any 

```
.. option:: --long-name (-l)
```

will get the `-l` styled by `\spxextra`, where the `--long-name` gets styled by `\spxentry`.

But this syntax is not the one described at https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-option, so maybe this is not really breaking change. And it only affects typography.

2018-11-01 10:25 UTC, jfbu commented on sphinx/writers/latex.py
> +                return match.expand(r'\\spxentry{\1}\\spxextra{\2}')
This mark-up is modeled on 

https://github.com/sphinx-doc/sphinx/blob/8b687ac30481e7204677138d8f2f3b49e354963e/sphinx/writers/latex.py#L800-L804

which applies to entries for domain indices. But here the "extra" is recovered from this input syntax:
```
.. index::
   single: foo (bar)
```

2018-11-01 10:25 UTC, jfbu commented on sphinx/writers/latex.py
> +                        self.body.append(r'\index{%s@%s%s}' % (p, P, m))
This also fixes #5576.

2018-11-01 10:25 UTC, jfbu commented on sphinx/writers/latex.py
> +                         p3, p3, p1, p2, p1, p2, m))
Here for triples  I dropped addition of `\spxextra` styling. But I should add it, I guess.

2018-11-01 10:25 UTC, jfbu commented on sphinx/writers/latex.py
> +                    self.body.append(r'\index{%s@%s|see{%s}}' % (p1, P1, p2))
I did not make any attempt into adding mark-up in the `see{%s}` part as I expected problems, especially to maintain compatibility with both `makeindex` and `xindy`.

2018-11-01 10:25 UTC, jfbu commented on sphinx/texinputs/sphinx.sty
> +\protected\def\spxextra#1{#1}% will get \let to \sphinxstyleindexextra in index
I decided to re-use the same `\sphinxstyleindexentry` and `\sphinxstyleindexextra` already used by LaTeX writer for domain indices at https://github.com/sphinx-doc/sphinx/blob/8b687ac30481e7204677138d8f2f3b49e354963e/sphinx/writers/latex.py#L784.

An alternative would be to define independent macros `\sphinxstylegeneralindexentry`, etc...

The `\spxentry/\spxextra` are privately used, only `\sphinxstyleindexentry/...` should get redefined by user. The reason for `\spxentry/\spxextra` is for shorter macro names, hence smaller file.

On the xindy side I looked a bit about using `markup-indexentry` which currently (in `sphinx.xdy`) is

```
(markup-indexentry :open "~n  \item "           :depth 0)
```
but did not see a way to add there the  `\spxentry{..}` wrapper. Because in case of sub-items, a closing `}` for example would enclose all sub-items, causing errors. And anyway, the `@\spxentry{...}` works both with `makeindex` and `xindy`. Furthermore I later decided (to match the domain indices) to use `\spxentry{...}\spxextra{...}`,  not `\spxentry{...\spxextra{...}}`, which I had started with.

2018-11-01 10:35 UTC, jfbu commented on sphinx/writers/latex.py
> +                         p3, p3, p1, p2, p1, p2, m))
I will push update to incorporate `\spxextra` styling for `p1`, `p2`, `p3` if they use `foo (bar)` style also in this "triple" case.

2018-11-03 16:23 UTC, tk0miya requested changes
LGTM with nits

2018-11-03 16:23 UTC, tk0miya commented on sphinx/writers/latex.py
> +    def visit_index(self, node, extrare=re.compile(r'^(.*\S)\s+\(([^()]*)\)\s*$')):
Yes, I agree with this is not a public API.  But this must be a breaking change. So -1 for changing signature of method.

I think marking `scre` keyword as deprecated is better. And I think `extrare` is not needed to substitute. So how about moving it to constant?
```
EXTRA_RE = re.compile('...')

...

def visit_index(self, node, scre=None):
    if scre:
        warnings.warn('scre option for visit_index() is deprecated')

    ...
```

2018-11-06 16:18 UTC, tk0miya approved these changes
LGTM!

2018-11-06 17:12 UTC, jfbu commented
@tk0miya thanks for quick reviewing! I will merge now into 1.8.2 although this is less minimal change than #5577. My estimate indeed is that absence of styling of general index in LaTeX output was a bug.

2018-11-06 17:12 UTC, merged