Improve index for command line options.
sphinx-doc/sphinx pull request #5593
Opened 2018-11-05 13:38 UTC by serhiy-storchaka

Create separate entry for every alias of command line option. Not include option arguments in index, so that options with different names of arguments can be grouped.

Fixes #5592.

2018-11-11 07:14 UTC, tk0miya requested changes
Could you add testcase please?

2018-11-11 07:36 UTC, tk0miya commented on sphinx/domains/std.py
> +                 signode['ids'][0], '', None))
Is this working fine for `-X <ARG>, -XXX <ARG>`?

2018-11-15 20:14 UTC, serhiy-storchaka commented
I am not very well familiar with Sphinx testing. Could you please give me tips? In what file should new tests be added and what tests can be used as a pattern? Are there any existing tests for `cmdoption` or other directives that add index entries?

2018-12-25 16:08 UTC, tk0miya commented
Sorry for late.

1. Please add directory named `tests/root/test-*` for new testcase
2. Please add a testcase for tests/test_*.py`. In this case, `tests/test_domain_std.py` would be better.
    - Please read other testcase to make your testcode.
    - In this case, I propose you 1) build HTML, 2) read `genindex.html` and 3) check it.

2019-02-11 04:02 UTC, tk0miya commented
any updates? We'll call feature freeze in this weekend. So it would be nice to update this until then.

2019-07-07 08:08 UTC, tk0miya commented
Merged #6494 instead. Thank you for proposal!

2019-07-07 08:08 UTC, closed without merging