WIP: #5605 fix Chinese search index
sphinx-doc/sphinx pull request #5611
Opened 2018-11-11 14:21 UTC by TimKam

Subject: generate search index for Latin words correctly if search language is Chinese

### Feature or Bugfix
- Bugfix

### Purpose
- As described at #5605
- Conf: ``html_search_language = 'zh'``

### Detail
- Removes trailing (and preceding) spaces from Latin search index terms
- WIP, because a Chinese-speaking person needs to confirm the correctness

### Relates
- Fixes #5605

2018-11-12 00:03 UTC, TimKam commented
@DaGeger can you test once again? What do you think, @tk0miya?

2018-11-12 14:13 UTC, tk0miya commented on sphinx/search/zh.py
> +        should_not_be_stemmed =\
I feel folding with `\` is a bit ugly. How about using parenthesis like this?
```
should_not_be_stemmed = (
            word in self.latin1 and
            len(word) >= 3 and
            len(self.stemmer.stem(word.lower())) < 3
)
```

2018-11-12 14:13 UTC, tk0miya approved these changes
LGTM with nits

2018-11-12 14:14 UTC, tk0miya requested changes
I noticed this should be merged into 1.8 branch because this is a bug fix.

2018-11-13 14:07 UTC, tk0miya approved these changes
LGTM

2018-12-17 14:13 UTC, tk0miya commented
Is this still WIP?

2018-12-18 08:36 UTC, TimKam commented
Sorry, yes. I wrote some tests locally and found out it needs more work. Will get back to it at the weekend.

2018-12-18 14:43 UTC, tk0miya commented
Okay. Please let me know if you finished. I'll review this again :-)

2018-12-22 23:35 UTC, TimKam commented
@tk0miya Could you have another look? I needed to add a list that contains all Latin terms and change the regexp that splits Chinese from Latin characters. @DaGeger comments from you regarding the initial problem are also welcome.

2018-12-23 08:55 UTC, tk0miya approved these changes
LGTM!

2018-12-25 17:41 UTC, merged