Deprecate and drop internal use of force_decode()
sphinx-doc/sphinx pull request #5620
Opened 2018-11-12 18:28 UTC by jdufresne

In the Python 3 only code base, this function is no longer necessary.
The type of values is well understood and deliberate. Code should avoid
arbitrary mixing of bytes & str.

By removing force_decode() calls from docstring values, can deprecate
the now unused 'encoding' arguments to various autodoc methods.

Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2018-11-13 13:29 UTC, tk0miya requested changes
LGTM with nits

2018-11-13 13:29 UTC, tk0miya commented on sphinx/util/__init__.py
> +    warnings.warn('force_decode() is deprecated.', RemovedInSphinx40Warning)
Please add `stacklevel=2` parameter to let developers know where this function is called from.

2018-11-13 15:18 UTC, jdufresne commented
Good call. Added `stacklevel=2`. :slightly_smiling_face:

2018-11-13 15:28 UTC, tk0miya approved these changes
LGTM!

2018-11-13 15:47 UTC, merged

2021-06-11 22:14 UTC, kloczek commented
Any chance to make soon a new release (4.0.3?) with that commit?

2021-06-12 07:28 UTC, astrojuanlu commented
This was merged in 2018, and it's present in Sphinx 4.0.2 as well as other versions.

2021-06-13 06:58 UTC, tk0miya commented
I noticed the removal of `force_decode()` harms some projects and people. So it would be better to extend the deprecation period of it until 5.0.