Fix "invalid escape sequence" warnings emitted during tests
sphinx-doc/sphinx pull request #5622
Opened 2018-11-12 19:55 UTC by jdufresne

```
  sphinx/tests/test_quickstart.py:221: DeprecationWarning: invalid escape sequence '\*'
    content = filename.bytes().decode('unicode-escape')
  sphinx/tests/test_quickstart.py:221: DeprecationWarning: invalid escape sequence '\`'
    content = filename.bytes().decode('unicode-escape')
```

2018-11-12 21:46 UTC, stephenfin commented
What was the reason for `unicode-decode`? Was it ever valid?

2018-11-12 22:01 UTC, jdufresne commented
I don't think it was ever valid.

It was added in commit a462284f952bcfd1462f0a7662d1d3145cbe0510. The contents of `make.bat`/`Makefile` are encode as uft-8, not Python `unicode` literals. It may have been a simple misunderstanding or oversight.

2018-11-13 07:55 UTC, stephenfin approved these changes
Fair fair. I've never seen this used elsewhere and the CI is happy, so...

2018-11-13 12:53 UTC, tk0miya requested changes
Could you rebase this into 1.8 branch please?
I'd like to merge this to 1.8.

2018-11-13 15:15 UTC, jdufresne commented
Rebased :slightly_smiling_face:

2018-11-13 15:28 UTC, tk0miya approved these changes
Thanks!

2018-11-13 15:47 UTC, merged