Fix incorrect handling of nested class names
sphinx-doc/sphinx pull request #5637
Opened 2018-11-15 03:55 UTC by bwohlberg

Subject: Fix incorrect handling of nested class names in sphinx.ext.inheritance_diagram and when the autodoc show-inheritance option is enabled

### Feature or Bugfix
- Bugfix

### Purpose
- Correct incorrect handling of nested class names

### Detail
- Names of nested classes are currently incorrect when inheritance details are included

### Relates
- See issue #5538

2018-11-22 17:06 UTC, tk0miya requested changes
Thank you for your work. Could you add a testcase for this please?

2018-11-22 17:45 UTC, bwohlberg commented
I assumed this would be covered by existing tests since the changes are so minor. Presumably you'd like the new test to confirm that the correct name is now being used for nested classes?

2018-12-02 15:39 UTC, bwohlberg commented
@tk0miya: Tests added as requested.

2020-02-11 16:31 UTC, tk0miya approved these changes
Sorry for very very late response. LGTM with nits. But they are very minor. so I'll work for it after merging.

2020-02-11 16:31 UTC, tk0miya commented on sphinx/ext/autodoc/__init__.py
> +                         u':class:`%s.%s`' % (b.__module__, b.__qualname__)
u-prefix is no longer needed because we drop all py2 support now.

2020-02-11 16:31 UTC, tk0miya commented on tests/roots/test-inheritance/dummy/test_nested.py
> +r"""
Why is this raw prefixed?

2020-02-11 16:58 UTC, merged

2020-02-11 16:59 UTC, tk0miya commented
Merged. Thank you for your contribution!