Simplify ensuredir() with Python3 stdlib features
sphinx-doc/sphinx pull request #5640
Opened 2018-11-16 13:07 UTC by jdufresne

- Simplify `ensuredir()` to equivalent `os.makedir(name, exist_ok=True)`
- Do not check if a directory exists before calling `ensuredir()` (`ensuredir()` already handles it)
- Add `exist_ok` argument to `path.makedirs()` to follow same pattern
- Drop unnecessary `.exists()` check immediately before `.isdir()`
- Add tests for `ensuredir()`

2018-11-20 15:22 UTC, tk0miya requested changes
LGTM with nits

2018-11-20 15:22 UTC, tk0miya commented on tests/test_util.py
> +        # Does not raise an exception.
Could you add comment about purpose of the case like "does not raise an exception for existing directory" please?

2018-11-21 02:38 UTC, jdufresne commented
Thanks! I have added the suggested comment. Let me know if you any other suggestions.

2018-11-21 11:29 UTC, tk0miya approved these changes
Thank you for quick work!

2018-11-21 11:29 UTC, merged