Replace six.string_types with native str
sphinx-doc/sphinx pull request #5653
Opened 2018-11-21 03:52 UTC by jdufresne

2018-11-21 11:29 UTC, tk0miya requested changes
LGTM with nits

2018-11-21 11:29 UTC, tk0miya commented on sphinx/ext/napoleon/docstring.py
> +            docstring = docstring.splitlines()  # type: ignore
How about like this?
```
if isinstance(docstring, str):
    self._lines = docstring.splitlines()
else:
    self._lines = docstring
```

I guess this change removes the `type: ignore` comment.

2018-11-21 11:29 UTC, tk0miya commented on sphinx/testing/fixtures.py
> +            not isinstance(result['shared_result'], str)):
I think this change allows not to fold the condition of if-clause.

2018-11-21 11:29 UTC, tk0miya commented on sphinx/util/inspect.py
>                              param.name in self.annotations:
This is also unfold-able.

2018-11-21 14:33 UTC, jdufresne commented on sphinx/ext/napoleon/docstring.py
> +            docstring = docstring.splitlines()  # type: ignore
I made this change, but there is still a mypy error on the `self._lines = docstring` line:

```
sphinx/ext/napoleon/docstring.py: note: In member "__init__" of class "GoogleDocstring":
sphinx/ext/napoleon/docstring.py:136:13: error: Incompatible types in assignment (expression has type "Union[unicode, List[unicode]]", variable has type "List[str]")
```

I think the `unicode`/`str` issues can be resolved once mypy can be passed the `--python-version` argument. 

Without that, resolving the above error would require checking a different type on the `isinstance` line (such as `six.text_type`). What do you prefer? Ignoring the type check or keeping the `six` import?

2018-11-21 14:48 UTC, jdufresne commented on sphinx/ext/napoleon/docstring.py
> +            docstring = docstring.splitlines()  # type: ignore
`._lines` is never actually accessed as an instance variable. So I've converted it to a local variable.

2018-11-21 14:52 UTC, jdufresne commented
I've made the suggested edits. All additional feedback welcome. :slightly_smiling_face:

2018-11-22 13:58 UTC, tk0miya approved these changes
LGTM!

2018-11-22 13:59 UTC, merged