Document how to make custom indices referencable
sphinx-doc/sphinx pull request #5677
Opened 2018-11-28 16:47 UTC by douardda

Subject: Document how to make custom indices referencable

### Feature or Bugfix
- Feature

### Purpose
- Add a paragraph to sphinx.domains.Index docstring to document how to make a custom Index referencable, ie. adding it to the labels and anonlabels of the std domain.

### Detail
- This has been inspired by the code from sphinx/ext/autosectionlabel.py

### Relates
- #2316

2018-12-20 17:28 UTC, stephenfin approved these changes
Looks good to me

2018-12-23 11:26 UTC, tk0miya requested changes

2018-12-23 11:26 UTC, tk0miya commented on sphinx/domains/__init__.py
> +            anonlabels['name'] = 'domain-name', ''
I feel very strange because this code touches internal data of standard domain.

@shimizukawa Do you know where the indices are generated? I'd like to know whether there is hook point to insert `target` node before generated indices.
If none, it would be better to add new APIs to add labels to `StandardDomain`.

2019-01-12 22:29 UTC, shimizukawa commented on sphinx/domains/__init__.py
> +            anonlabels['name'] = 'domain-name', ''
index node is generated by Index domain class:

https://github.com/sphinx-doc/sphinx/blob/76e9f57c2e4457dec11d258435b7a6c6ec5de005/sphinx/directives/other.py#L188

and index role processor function:

https://github.com/sphinx-doc/sphinx/blob/76e9f57c2e4457dec11d258435b7a6c6ec5de005/sphinx/roles.py#L193

After that, indices are collected into `env.indexentries` at:

https://github.com/sphinx-doc/sphinx/blob/76e9f57c2e4457dec11d258435b7a6c6ec5de005/sphinx/environment/collectors/indexentries.py#L41

.. and `env.indexentries` are processed at:

https://github.com/sphinx-doc/sphinx/blob/76e9f57c2e4457dec11d258435b7a6c6ec5de005/sphinx/environment/adapters/indexentries.py#L60

2019-01-13 05:16 UTC, tk0miya commented on sphinx/domains/__init__.py
> +            anonlabels['name'] = 'domain-name', ''
Thanks,

@douardda It seems indices are already registered as anonymous. I don't understand what this code does. I feel this comment would confuse other developers. Please check it please.

BTW, is this working fine for multiple same-named indices?

2019-02-11 04:00 UTC, tk0miya commented
any updates?

2019-05-30 16:33 UTC, tk0miya commented
I'm closing this now because not updated so long.
Please feel free to reopen if you'd like to continue discussion.
Thank you for proposal.

2019-05-30 16:33 UTC, closed without merging