#5660 add classes for different version modications
sphinx-doc/sphinx pull request #5861
Opened 2018-12-23 15:46 UTC by TimKam

Subject: Add classes for different version modifications

### Feature or Bugfix
- Feature

### Purpose
- To allow users to use different styles for different modification types.
### Detail
* Generic class: ``versionmodified``
* *Changed* class: ``changed``
* *Added* class: ``added``
* *Deprecated* class: ``deprecated``

### Relates
- Closes #5660

2018-12-23 15:59 UTC, tk0miya requested changes
LGTM with nits.
In addition, you need to modify some testcases.
Please check errors on CI servers.

2018-12-23 15:59 UTC, tk0miya commented on sphinx/domains/changeset.py
> -
Please keep this line as is :-)

2018-12-23 16:04 UTC, tk0miya approved these changes
Looks good!
Go ahead. Add an entry to CHANGES file and merge this :-)

2018-12-23 18:19 UTC, TimKam commented
Ok, when the build on ``master`` no longer fails, I will control merge and merge back.

2018-12-24 03:21 UTC, tk0miya commented
Oh, sorry. I just fixed master branch.

2018-12-24 14:12 UTC, merged