Clean up import for annotations
sphinx-doc/sphinx pull request #6133
Opened 2019-03-03 11:32 UTC by tk0miya

### Feature or Bugfix
- Refactoring

### Purpose
- New flake8 command supports py2 style type annotations. So `NOQA` comment is not needed for them.
- This removes the comment all, and also removes unused import

2019-03-03 11:49 UTC, stephenfin commented
Have you a link to the flake8 change?

2019-03-03 11:50 UTC, stephenfin requested changes
Do we need the `if False:` still? In fact, why was that ever needed? Also, we should set a minimum version for `flake8` in `tox.ini`

2019-03-03 12:48 UTC, tk0miya commented
It was added pyflakes-2.1.0. And flake8-3.7 depends on it.

>Mark names used in PEP 484 # type: ... comments as used
>https://github.com/PyCQA/pyflakes/blob/master/NEWS.rst

>Pyflakes has been updated to >= 2.1.0, < 2.2.0 (See also GitLab!283, GitLab!285)
>https://github.com/PyCQA/flake8/blob/master/docs/source/release-notes/3.7.0.rst

2019-03-03 12:54 UTC, tk0miya commented
>Do we need the if False: still? In fact, why was that ever needed? Also, we should set a minimum version for flake8 in tox.ini

It is needed for avoiding circular import. It is same as `typing.TYPE_CHECKING` (Added since py3.5.2).
https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

Some of the import would be able to move to top level. But we need to be careful to do that. So I'd like to do that in another PR.

2019-03-03 23:37 UTC, stephenfin commented
> It was added pyflakes-2.1.0. And flake8-3.7 depends on it.

OK, could you update this so and then I'm happy :+1: 

https://github.com/sphinx-doc/sphinx/blob/b58d0e88ce9cb477a87bf112adde8075535c8690/setup.py#L46

2019-03-06 14:45 UTC, tk0miya commented
I'd not like to upgrade dependency. So I stopped to remove `NOQA` comment. This PR only removes unused imports.

2019-03-06 14:48 UTC, tk0miya commented
I prefer to migrate our annotations to py3 style. I believe it does not requires new flake8.

2019-03-06 15:13 UTC, stephenfin approved these changes

2019-03-06 15:13 UTC, stephenfin commented
OK, then I'm happy with this as-is

2019-03-06 15:28 UTC, merged

2019-03-06 15:29 UTC, tk0miya commented
Thank you for reviewing!