propogate cite_reference node classes to pending_xref node
sphinx-doc/sphinx pull request #6147
Opened 2019-03-08 00:34 UTC by chrisjsewell

Subject: propogate `cite_reference` node classes to `pending_xref` node

### Feature

small addition to `sphinx.transforms.CitationReferences` to
propogate `cite_reference` node classes to `pending_xref` node

### Purpose

This is useful for extensions, 
that wish to act on only `cite_reference` nodes that they create

2019-03-08 12:57 UTC, tk0miya requested changes
LGTM with nits.

2019-03-08 12:57 UTC, tk0miya commented on sphinx/transforms/__init__.py
> +                refnode.set_class(class_name)
`Element.set_class()` is marked as deprecated. So please modify `refnode['classes']` directly instead.
https://repo.or.cz/docutils.git/blob/HEAD:/docutils/docutils/nodes.py#l1021

2019-03-08 12:59 UTC, tk0miya commented
Could you rebase this to 2.0 branch? I'd like to merge into the branch.

2019-03-08 14:33 UTC, chrisjsewell commented
@tk0miya the only issue I found while creating PR mcmtroffaes/sphinxcontrib-bibtex#161
is that, if a citation is not found for a citation reference, then
[this line](https://github.com/sphinx-doc/sphinx/blob/c5f533d73ddc84d0a07ea2f91f9443dd11ec1643/sphinx/transforms/post_transforms/__init__.py#L71) will be activated. The preceding lines `docutils.nodes.replace_self` will then fail, because  `sphinx.addnodes.pending_xref` now has class attributes that cannot be transferred to a `docutils.nodes.Text` node.

Would it be best to then to replace that line with:

```python
except NoUri:
    newnode = contnode
    newnode['classes'] = []
```

2019-03-09 06:14 UTC, tk0miya commented
Thank you for letting me know that. I think the `AttributeError` must be a bug of Sphinx, not bibtex extension's.
Sphinx expects that a child node of pending_xref is kind of TextElement. But our `CitationReferences` transform breaks it. I'll work for it in another PR.
Thanks,

2019-03-09 06:14 UTC, tk0miya approved these changes

2019-03-09 06:15 UTC, merged

2019-03-09 06:48 UTC, tk0miya commented
I just made a fix #6151 for `CitationReferences`. Could you check it please?