#5877: Allow setting imported_members for autosummary in conf.py
sphinx-doc/sphinx pull request #6212
Opened 2019-03-27 14:31 UTC by tsanikgr

Subject: Allow the user to set the `imported_members` argument of the function [generate_autosummary_docs](https://github.com/sphinx-doc/sphinx/blob/a2246152872c801fbe44c286f79973b3b4fe5479/sphinx/ext/autosummary/generate.py#L91) in conf.py

### Feature or Bugfix
- Feature

### Purpose
Currently, when `autosummary` is triggered when the `builder-inited` event is fired, the argument `imported_members` [is ignored](https://github.com/sphinx-doc/sphinx/blob/a2246152872c801fbe44c286f79973b3b4fe5479/sphinx/ext/autosummary/__init__.py#L737). This PR adds a new conf variable, `autosummary_imported_members` which solves that.

Our use case is the following:
We expose public functionality in our `__init__.py` files, and we want to document them automatically using `autosummary`:

*module/__init__.py:*
```python
from .submodule import Foo
```

*module/submodule.py:*
```python
class Foo:
   pass
```

- <Environment if this PR depends on>
Any environment?

### Relates
- #4247
- #4372
- #5877

2019-03-31 16:45 UTC, tk0miya requested changes
LGTM with nits!

2019-03-31 16:45 UTC, tk0miya commented on doc/usage/extensions/autosummary.rst
> +     By default this if disabled.
This text is duplicated with `confval` entry. It would be better to merge this into the entry.

2019-03-31 16:45 UTC, tk0miya commented on doc/usage/extensions/autosummary.rst
> +     .. versionadded:: 2.1.1
`2.1` ?

2019-04-03 16:36 UTC, tsanikgr commented
Thanks @tk0miya :)
Updated, can you please have another look?

2019-04-04 14:04 UTC, tk0miya approved these changes

2019-04-04 14:04 UTC, merged

2019-04-04 14:05 UTC, tk0miya commented
Merged.
Thank you for your contribution!