Add support for bound methods posing as functions in the module
sphinx-doc/sphinx pull request #6288
Opened 2019-04-13 05:07 UTC by alsrgv

Subject: add support for bound methods posing as functions in the module

Fixes #6287

2019-04-13 05:08 UTC, alsrgv commented
@tk0miya, please suggest additional tests, if any.

2019-04-14 03:02 UTC, tk0miya requested changes
At first, could you rebase this to 2.0 branch? Then, it will be released as Sphinx-2.1.0.

Next, could you add a testcase which generates reST marked up text like `test_partialfunction()` and so on?

1. Add a test subject to `tests/roots/test-ext-autodoc/target/functions.py`
2. Add a testcase to `tests/test_autodoc.py`. There are many examples for generating internal reST code.

2019-04-14 03:02 UTC, tk0miya commented on sphinx/ext/autodoc/__init__.py
> +                (inspect.isroutine(member) and isinstance(parent, ModuleDocumenter)))
Could you add comment for this code? I've often lost sight of purpose of the code because autodoc is too complicated.

2019-04-14 03:02 UTC, tk0miya commented on tests/test_autodoc.py
> +
This empty line is not needed.

2019-04-14 08:09 UTC, alsrgv commented on sphinx/ext/autodoc/__init__.py
> +                (inspect.isroutine(member) and isinstance(parent, ModuleDocumenter)))
Is the added comment sufficient, or did you have something more in mind?

2019-04-14 08:09 UTC, alsrgv commented
@tk0miya, thanks for the feedback.  I've updated the PR, please let me know if you have more comments.

2019-04-14 10:33 UTC, tk0miya approved these changes
Thank you for update! LGTM.

2019-04-14 10:33 UTC, tk0miya commented on sphinx/ext/autodoc/__init__.py
> +                (inspect.isroutine(member) and isinstance(parent, ModuleDocumenter)))
LGTM :-)

2019-04-14 10:33 UTC, merged

2019-04-14 10:34 UTC, tk0miya commented
Merged. Thank you for your contribution!