viewdoc linenos
sphinx-doc/sphinx pull request #6319
Opened 2019-04-23 13:25 UTC by benkrikler

Subject: Add an option to the viewcode extension to include line-numbering in the output

### Feature or Bugfix
- Feature
- (and included in here, I believe is potentially a Bugfix; this wasn't the original intention, so I could split it out)

### Purpose
I felt that it could help a project I was working on if I the source code as highlighted by the `viewcode` extension could include line numbers.  When I looked into the viewcode source, it seemed relatively straightforward to add this, and so as a way to learn a bit about the internals of sphinx I took a go at it.
At that point, it seemed like it could be something of use / interest and worth contributing back to the main repository.  I'm sorry that this hasn't followed what I believe is the normal approach to adding a feature (I read the Contributing guidelines, and whilst it didn't look like a hard rule, I think I should have opened an issue first)!

### Detail
Along the way though, I noticed that, at least in my browser (Firefox 66.0.2) the extra `div` inserted around the `[docs]` link in the highlighted sourcecode output was adding an extra line intermittently (this was with tag v2.0.1 of Sphinx).  The div only seems to have served to add a css class, so I have moved that css class to the `<a>` element instead and removed the encasing `div`.  I appreciate that might be a bit drastic (for example, styles might be selecting on the `div`), but it did fix the issue.  It seems #4701 and #4709 concerned this problem as well, but as far as I could tell the fix as implemented has only partially worked.

### Relates
- #4701
- #4709

2019-04-25 16:37 UTC, tk0miya requested changes

2019-04-25 16:37 UTC, tk0miya commented on sphinx/ext/viewcode.py
> -                '<div class="viewcode-block" id="%s"><a class="viewcode-back" '
This `<div>` tag is used for highlighting the source code when user came from description:
![スクリーンショット 2019-04-26 1 15 02](https://user-images.githubusercontent.com/748828/56751368-dd8e8f00-67c0-11e9-9935-defb8f72b24c.png)

I think this removal disables the highlights. This is not a bug fix.

2019-04-25 16:37 UTC, tk0miya commented on sphinx/ext/viewcode.py
> +def split_code_lines(lines):
I feel this code is a bit tricky. To be our code robust, we need to make a custom Formatter for pygments. I'll take a look in this weekend.

2023-07-28 04:52 UTC, merged

2023-07-28 04:53 UTC, AA-Turner commented
Thanks @benkrikler!

A