productionlist: Put the full production in production.rawsource
sphinx-doc/sphinx pull request #6358
Opened 2019-05-12 16:34 UTC by cpitclaudel

This makes it possible to iterate over the productions and see exactly the text
that was entered by the author, which is useful to e.g. extract information from
the grammar (like syntax-highlighting patterns).

2019-05-13 05:38 UTC, tk0miya requested changes
LGTM.
Could you rebase this into 2.0 branch? Then I'll merge this soon.

2019-05-14 03:24 UTC, cpitclaudel commented
Done! (I think? :)
As always, thanks for your dedication and your hard work!

2019-05-14 13:30 UTC, tk0miya approved these changes

2019-05-14 13:30 UTC, merged

2019-05-14 13:30 UTC, tk0miya commented
Merged. Thank you for your contribution :-)

2019-05-14 13:32 UTC, tk0miya commented on CHANGES
> +  production rule.
Note: I moved this entry to features list.