apidoc: Insert newlines between submodules
sphinx-doc/sphinx pull request #6445
Opened 2019-06-04 15:21 UTC by stephenfin

Fix a regression introduced in 2.1.0 where submodules didn't have a
newline between them resulting in the following warning:

  Explicit markup ends without a blank line; unexpected unindent.

Signed-off-by: Stephen Finucane <stephen@that.guru>
Closes: #6440

2019-06-05 13:34 UTC, tk0miya requested changes
It seems failed. Could you check the code please?
In addition, I'll release 2.1.1 package for some reasons. So it would be nice if this goes into 2.1.1 branch.

2019-06-06 17:13 UTC, stephenfin commented
> It seems failed. Could you check the code please?
> In addition, I'll release 2.1.1 package for some reasons. So it would be nice if this goes into 2.1.1 branch.

My mistake. Jinja2 gets complicated real fast. Should be fixed now.

2019-06-06 17:27 UTC, tk0miya commented
It seems template is fixed. But this still goes forward to master branch. Could you rebase this please?
In addition, please add an entry of CHANGES.
Thanks,

2019-06-06 22:07 UTC, stephenfin commented
Which branch? I don't see a 2.1 branch?

2019-06-07 13:48 UTC, tk0miya commented
Please merge into 2.1.1 branch.

2019-06-07 14:34 UTC, stephenfin commented
> Please merge into 2.1.1 branch.

Okay. Unrelated but can we rename this to the 2.1 branch (i.e. the branch that all 2.1.x releases will be made from)? The current name is very confusing. I thought that was a tag.

2019-06-08 02:54 UTC, tk0miya approved these changes
LGTM. Go ahead!

2019-06-08 03:45 UTC, tk0miya commented
>Note that it also means we can't browse documentation at https://www.sphinx-doc.org/en/2.1/ even though we can browse https://www.sphinx-doc.org/en/2.0/

IMO, document for each minor release is not needed. I agree with `.../2.0` path is confusable. Personally, it is enough to provide the only one document for each major release. So renaming it to `.../2.x` is better.

>Unrelated but can we rename this to the 2.1 branch (i.e. the branch that all 2.1.x releases will be made from)?
..

I agree that `2.0` is confusable for 2.x series. So +0 for renaming. But I think `2.x` is better. Anyway, we need to discuss more. So please file an another issue to propose the change.
ping @shimizukawa; Can you tell us your idea for us in the coming issue.

2019-06-08 13:02 UTC, merged