Remove "universal" configuration from setup.cfg
sphinx-doc/sphinx pull request #6480
Opened 2019-06-13 01:59 UTC by jdufresne

Sphinx is Python-3-only and therefore is not a universal wheel. It
should still distribute a 'py3' wheel, just not a universal one.

From https://wheel.readthedocs.io/en/stable/user_guide.html

> If your project contains no C extensions and is expected to work on
> both Python 2 and 3, you will want to tell wheel to produce universal
> wheels by adding this to your setup.cfg file: …

As Sphinx doesn't work on Python 2, it should not be universal.

2019-06-13 13:44 UTC, tk0miya requested changes
Reasonable.
Could you rebase this to 2.0 branch?

2019-06-13 13:49 UTC, tk0miya commented
Note: this is related with #6470.

2019-06-13 15:38 UTC, jdufresne commented
>  Could you rebase this to 2.0 branch?

No problem. Done. :slightly_smiling_face:

2019-06-15 03:43 UTC, tk0miya approved these changes

2019-06-15 03:43 UTC, merged

2019-06-15 03:43 UTC, tk0miya commented
Thanks!