Fix #6545. Strip doctests for doctest_node blocks.
sphinx-doc/sphinx pull request #6547
Opened 2019-07-02 14:24 UTC by ngoldbaum

This fixes the regression described in #6545.

### Feature or Bugfix

- Bugfix

### Detail
When support for `trim_doctest_flags` was expanded for all output types in #5199, only code literal blocks were checked for doctest flags. However, docutils has a `doctest_block` role that must also be handled. This pull request adds some additional logic to also strip doctest flags from `doctest_block` elements.

### Relates
- #6545
- #5199

2019-07-02 16:07 UTC, ngoldbaum commented
@tk0miya I have no idea why the one test failed on x64 windows - do you have any insight here? Is that test flaky maybe?

2019-07-06 04:34 UTC, tk0miya requested changes
LGTM with nits.
And it would be better to rebase this into 2.0 branch.

2019-07-06 04:34 UTC, tk0miya commented on sphinx/transforms/post_transforms/code.py
> +        # type: (Union[nodes.literal_block, nodes.doctest_block]) -> None
mypy warns this line:
```
sphinx/transforms/post_transforms/code.py:120: error: Name 'Union' is not defined
```
https://travis-ci.org/sphinx-doc/sphinx/jobs/553354669

Could you import `Union` please?

2019-07-06 04:34 UTC, tk0miya commented on sphinx/transforms/post_transforms/code.py
>          for node in self.document.traverse(nodes.literal_block):
Could you add an annotation `#  type: Element` the end of this line please?
```
sphinx/transforms/post_transforms/code.py:117:13: error: Incompatible types in assignment (expression has type "doctest_block", variable has type "literal_block")
```

2019-07-07 19:58 UTC, ngoldbaum commented
OK, rebased onto the 2.0 branch and responded to your nits. This is the first time I've worked with a codebase that uses type annotations so thank you for your patience with that.

2019-07-08 15:14 UTC, tk0miya approved these changes

2019-07-08 15:14 UTC, merged

2019-07-08 15:15 UTC, tk0miya commented
Thank you for quick updates. Merged :-)