LaTeX: Avoid section titles at the end of a page
sphinx-doc/sphinx pull request #6633
Opened 2019-08-05 09:46 UTC by sebhub

The topic directive uses in LaTeX rendering a framed box which
encourages a pagebreak before it even if the element is a section title.
This can be avoided with the nobottomtitles option of the titlesec
package.

Fixes: #6618

2019-08-22 12:42 UTC, jfbu requested changes
Thanks. Could you please rebase this to 2.0 branch (after doing it locally, force push, then edit the PR to change the branch to merge to), so that it can be merged to become part of 2.3.0 release ? (It is some kind of a bug fix indeed but not an urgent one, and I don't feel it adds strong backwards incompatibilities although it may slightly modify PDFs, overall it looks like it should rather improve output; and I checked the option has long been available (since 1999) in the `titlesec` package).

**edit** I have now rebased your branch on tip of 2.0. Hope you don't mind.

2019-09-05 07:18 UTC, jfbu approved these changes

2019-09-05 07:22 UTC, jfbu commented
Thanks for contribution!

2019-09-05 07:23 UTC, merged

2019-09-06 13:26 UTC, sebhub commented
Thanks, for rebasing it for me. I am still recovering from holidays.