Fix use of html_file_suffix instead of html_link_suffix in search results
sphinx-doc/sphinx pull request #7278
Opened 2020-03-07 17:23 UTC by rdb

The links in the search results have `html_file_suffix` appended instead of `html_link_suffix`.  This fixes that.

To reproduce the bug, build any documentation with `html_file_suffix` set to ".html" and `html_link_suffix` set to "".  The regular links between pages will be extensionless, but the search results will have .html at the end.

2020-03-07 21:54 UTC, blueyed commented
I'm not familiar with Sphinx' tests yet, but think it would be great to have a test for this - in case you are more familiar with it already.. :)

2020-03-08 03:14 UTC, tk0miya requested changes
LGTM. But it would be better to merge this into 3.x branch. So please resolve conflicts with 3.x branch. Then I'll merge this.

Note: Unfortunately, there are no good testcases for search JS. You can add a case to `tests/js/doctools.js`, but it seems many works are needed to do that. So I'm okay with no testing.

2020-03-08 03:15 UTC, tk0miya commented
BTW, I don't still understand how useful `html_link_suffix` is. Could you let me know what purpose you've used if possible.

2020-03-08 08:50 UTC, rdb commented
OK, I will do that.

In my set-up, I want to upload .html files to my server, but I want the user to see clean URLs without the .html extension at the end.  So I configured my web server to automatically add on the .html extension when asking for a URL without extension, and set html_link_suffix to the empty string.  This generally works pretty well:
https://docs.panda3d.org/1.10/python/index

2020-03-08 16:27 UTC, tk0miya commented
Thank you for update and explanation. I understand.

2020-03-08 16:28 UTC, tk0miya approved these changes

2020-03-08 16:28 UTC, merged

2020-03-08 16:29 UTC, tk0miya commented
Merged. Thank you for your contribution!