Escape some links in HTML templates
sphinx-doc/sphinx pull request #7426
Opened 2020-04-06 19:42 UTC by mgeier

### Feature or Bugfix

- Bugfix

### Purpose

If a user chooses a strange `master_doc`, e.g.:

    master_doc = 'my"index'

... the links to the main page will be broken.

Same for `logo`, `favicon` and style sheets.

If a user chooses strange characters for sub-directories of the source directory, "previous" and "next" links might be broken, too.

2020-04-08 16:51 UTC, tk0miya requested changes
+0; I suppose such characters might cause other errors. So I'd not like to support them like this approach. But I don't know what kind of characters effect to our build. Therefore this is reasonable until we determine the prohibited characters for docnames.

BTW, we have a bug fix release 3.0.1 in nearly days. So it's nice if you rebase this into the 3.0.x branch.
Thanks,

2020-04-08 20:24 UTC, mgeier commented
Thanks for the review!

> I suppose such characters might cause other errors.

I tried it and there were no other errors.

I don't think any of this has any real consequences. I just noticed it while creating a theme and playing around with escaping and I thought I'd make a PR, just for completeness' sake.

> rebase this into the 3.0.x branch

Done.

2020-04-09 15:23 UTC, tk0miya commented
>I tried it and there were no other errors.

Sphinx supports many kind of formats (including 3rd party extensions). I worried these strange characters cause trouble in one of them.

2020-04-09 15:23 UTC, tk0miya approved these changes

2020-04-09 15:23 UTC, merged

2020-04-09 15:24 UTC, tk0miya commented
Thank you for rebasing. Merged.