Relbar breadcrumb should contain current page
sphinx-doc/sphinx pull request #7476
Opened 2020-04-13 17:39 UTC by timhoffm

The relbar at the top contains the sequence of parents, which looks like [breadcrumb navigation](https://en.wikipedia.org/wiki/Breadcrumb_navigation):
![grafik](https://user-images.githubusercontent.com/2836374/79143595-caa01080-7dbd-11ea-9d23-2e6e9a033d8c.png)

However, breadcrumbs also contain the current page itself (see linked wikipedia article above). This makes sense as it's a self-contained display of the current location. Having the current page missing always confuses me.

This PR adds the current page as well:

![grafik](https://user-images.githubusercontent.com/2836374/79143568-c07e1200-7dbd-11ea-9c93-d8ff35fdd93b.png)

This is a change of the layout. If you have concerns about backward-compatibility, we could make it configurable via an option. (But IMHO it's generally the right thing to do, so not sure if we can just regard this as bug fix).

2020-04-15 16:30 UTC, tk0miya requested changes
LGTM. But it would be better to merge this into the 3.x branch. Could you rebase this please?

2020-04-16 21:02 UTC, timhoffm commented
Thanks! Rebased.

2020-04-17 13:39 UTC, tk0miya approved these changes

2020-04-17 13:39 UTC, merged

2020-04-17 13:39 UTC, tk0miya commented
Merged. Thank you for your work!