UML inheritance diagram
sphinx-doc/sphinx pull request #7665
Opened 2020-05-15 00:34 UTC by vallsv

Hi. Here is a first attempt to allow to display inheritance diagram with UML-like notation.

### Feature
- Feature
- Refactoring

### Purpose
The aim was to allow to use UML-like diagram, without leaning graphvis language.

### Detail
- A `:style:` was added
   - It supports `default` for the current look
   - And `uml` which generates edges in the reversed direction and with the right arrow symbol (as specified in the issue) 
- Unittests was refactored in order to:
   - Split a big test (as it was called in a comment in the source code)
   - If you have an example with a module-scope fixture to build stuff, it could be much cleaner (i tried, i failed)
   - Allow to introspect the dot syntax

Here is the result with the unittests:
![inheritance](https://user-images.githubusercontent.com/7579321/81998860-d2b8cd80-9653-11ea-84e8-372ed63efb47.png)

### Relates
- Closes #2969

2020-05-16 10:29 UTC, vallsv commented
I am working on something bigger than that. There is a huge clean up to do. How can i contribute? Anybody care if i extend this PR?

2020-05-16 12:59 UTC, eric-wieser commented
Can you update the PR description to show what that inheritance graph looks like _without_ this PR too, so we can see before / after?

2020-05-16 15:20 UTC, vallsv commented
Yes sure, but that's an optional directive, so if you do not specify `:style: uml` to your diagram, the result is the one without this PR.

2020-05-16 15:26 UTC, eric-wieser commented
Sure, I'm just asking for a comparison of the two styles in the description.

2020-05-16 15:51 UTC, vallsv commented
I have updated the description as requested.

As reference, here is the current state on my side: https://github.com/vallsv/sphinx/tree/improve-inheritance-diagram (other things than UML), with that i can do what i want, so i do not plan another changes.

2020-08-03 16:57 UTC, tk0miya requested changes
LGTM with nits.

2020-08-03 16:57 UTC, tk0miya commented on doc/usage/extensions/inheritance.rst
> +
Please add `versionchanged` tag here? I think this would be added into 3.3.0 release.

2020-08-03 16:57 UTC, tk0miya commented on sphinx/ext/inheritance_diagram.py
> +                 private_bases: bool = False, parts: int = 0, style: str = "default",
Please append a new parameter to the tail of the argument list to keep compatibility.

2020-08-03 16:57 UTC, tk0miya commented on sphinx/ext/inheritance_diagram.py
> +        'style': str,
How about using `docutils.parsers.rst.directive:choice` instead? Then you don't need to validate the value manually.

2020-08-22 20:26 UTC, vallsv commented on sphinx/ext/inheritance_diagram.py
> +        'style': str,
How does it work?

2020-08-22 20:27 UTC, vallsv commented on doc/usage/extensions/inheritance.rst
> +
I have updated it with `versionadded` trying to follow the previous use.

2020-08-22 20:36 UTC, vallsv commented
I have updated the PR, but it contains a little more than what there was. It mostly fixes behaviors on the gtaph generation and not only add `style`.

If you prefer i can remove that extra stuffs for now.

2020-08-22 20:36 UTC, vallsv commented on sphinx/ext/inheritance_diagram.py
> +                 private_bases: bool = False, parts: int = 0, style: str = "default",
Done

2020-08-22 21:03 UTC, vallsv commented
mypy CI is making me crazy, is there an easy way to test it on my side?

2020-08-22 21:11 UTC, vallsv commented on sphinx/ext/inheritance_diagram.py
> +        'style': str,
I found an example in `graphviz.py` ext

2020-08-23 12:11 UTC, vallsv commented
I have reworked the commits. This can be reviewed.

2020-08-23 12:20 UTC, eric-wieser commented on sphinx/ext/inheritance_diagram.py
> +            self.derived = set([])  # type: Set[Any]
nit:
```suggestion
            self.based = set()  # type: Set[Any]
            self.derived = set()  # type: Set[Any]
```

2020-08-23 14:22 UTC, vallsv commented on sphinx/ext/inheritance_diagram.py
> +            self.derived = set([])  # type: Set[Any]
Thanks. No idea why i use to write it this way...

2020-08-23 20:57 UTC, vallsv commented
I think this fixes #5518 and #5523

2020-08-23 21:16 UTC, vallsv commented
I have pushed the last things i add on my side when i was working on. So it also closes #7660.

2021-05-09 03:24 UTC, closed without merging

2021-05-10 08:13 UTC, vallsv commented
@tk0miya it means you have merged the stuff on your own? Or you think it is not mergeable?

2021-05-10 08:18 UTC, eric-wieser commented
@vallsv: The 3.x branch has been deleted, which results in all PRs to it being closed.