Closes #7887: Updated the sphinx.js locale files to improve readability
sphinx-doc/sphinx pull request #7900
Opened 2020-06-30 18:58 UTC by chuckyQ

Subject: Improving format of sphinx.js locale files for readability

### Feature or Bugfix

- Refactoring

### Purpose
- Modify the formatting of the locale files to improve readability.
- No environment needed for PR

### Detail
- Added indentation to the `json.dump` call in setup.py

### Relates
- None

2020-07-02 13:48 UTC, tk0miya requested changes
Looks good. Could you regenerate `sphinx.js` by this command?

2020-07-04 19:47 UTC, chuckyQ commented
So after reading up on the cmdclass, I was able to test it out. Turns out, at least on my machine (Windows 10), I was able to create the sphinx.js files only if the files were opened with 'utf8' encoding. I updated the pull request to handle this.

2020-07-05 02:35 UTC, tk0miya approved these changes

2020-07-05 02:36 UTC, tk0miya commented
Okay, I'll regenerate sphinx.js on my side. Thanks,

2020-07-05 02:36 UTC, merged