Add autosummary_filename_map config to avoid clashes
sphinx-doc/sphinx pull request #7927
Opened 2020-07-08 06:49 UTC by jnothman

Subject: Add `autosummary_filename_map` config to allow users to configure alternative filenames for autodoc objects, avoiding name clashes on case-insensitive file systems.

### Feature or Bugfix
- Feature
- Bugfix

### Purpose
- This allows the user to configure the mapping between object name and filename when performing autodoc generation of HTML files. It adds a config param called `autosummary_filename_map` to do so. It is a simple dict between name and filename to be generated.
- The intention is that this will allow renames on case-insensitive file systems (per #2024), albeit requiring users to manually identify filenames that might result in name clashes, and propose an alternative filename for the generated docs.

### Relates
- Fixes #2024
- https://github.com/scikit-learn/scikit-learn/issues/12712 ping @thomasjpfan

2020-07-08 06:52 UTC, jnothman commented
[fixed branching and force-pushed.]

2020-07-09 14:07 UTC, tk0miya requested changes
LGTM with nits! I'll merge this after your update soon :-)

2020-07-09 14:07 UTC, tk0miya commented on tests/roots/test-autosummary/sphinx.rst
> -Autosummary test
Why did you update this file? I suppose this change is not needed.

2020-07-09 14:07 UTC, tk0miya commented on tests/roots/test-ext-autosummary-filename-map/index.rst
> +   autosummary_importfail
I think this entry is not needed for this case, right?

2020-07-09 14:07 UTC, tk0miya commented on tests/test_ext_autosummary.py
> +                    confoverrides={'autosummary_filename_map':
Please set this on conf.py if you don't have a plan to change this in other test cases.

2020-07-09 14:07 UTC, tk0miya commented on tests/roots/test-ext-autosummary-filename-map/conf.py
> +source_suffix = '.rst'
This settings is no longer needed. It's default now.

2020-07-09 14:07 UTC, tk0miya commented on tests/roots/test-ext-autosummary-filename-map/autosummary_dummy_module.py
> +qux = 2
Could you remove unused entries from this code, please?

2020-07-09 14:07 UTC, tk0miya commented on sphinx/ext/autosummary/generate.py
> +        self.config.add('autosummary_filename_map', {}, True, None)
Good work!

2020-07-10 01:26 UTC, jnothman commented on tests/roots/test-autosummary/sphinx.rst
> -Autosummary test
I thought I just copied, but I might have added more than intended.

2020-07-10 01:30 UTC, jnothman commented
Thank you for the review. I hope I have addressed all comments.

2020-07-10 15:17 UTC, tk0miya commented on sphinx/ext/autosummary/generate.py
> +                            'strings to strings')
You don't need to check the value is dict here. The Sphinx automatically checks the given value is the same type as the default value. But it does not check the contents of the dict. I think the default check is enough.

Note: If you'd like to add more careful validations, please use a hook for the config-inited event to validate user configurations.

https://github.com/sphinx-doc/sphinx/blob/98a854deca55dc14b66e222fd94dcecc993e691d/sphinx/builders/latex/__init__.py#L498-L503
https://github.com/sphinx-doc/sphinx/blob/98a854deca55dc14b66e222fd94dcecc993e691d/sphinx/builders/latex/__init__.py#L558

2020-07-10 15:19 UTC, tk0miya commented on sphinx/ext/autosummary/__init__.py
> +    app.add_config_value('autosummary_filename_map', {}, 'html')
It is better to add a new config variable alphabetically. Could you move this above?
(I noticed `autosummary_imported_members` is not. I'll fix it later)

2020-07-13 02:11 UTC, thomasjpfan commented
Tried this for scikit-learn and got an expected warning:

```
checking consistency... /Users/thomasfan/Repos/scikit-learn-1/doc/modules/generated/dbscan-lowercase.rst: WARNING: document isn't included in any toctree
done
```

2020-07-13 18:24 UTC, tk0miya commented
Oops. `Autosummary.run()` is also fixed using the new configuration. It constructs a toctree node as a reference to the document file.

2020-07-13 21:47 UTC, jnothman commented
I don't really understand... Is there something I should change?

2020-07-14 14:34 UTC, tk0miya commented
I think some fix is needed to here. Is my understanding incorrect?
https://github.com/sphinx-doc/sphinx/blob/03e1070888cffe746705637468cee8c47daffb75/sphinx/ext/autosummary/__init__.py#L255-L257

2020-07-15 08:05 UTC, jnothman commented
> I think some fix is needed to here. Is my understanding incorrect?

Seems reasonable. I suppose I need to come up with a test case.

2020-07-21 05:11 UTC, jnothman commented
This is ready for review.

2020-07-23 04:38 UTC, tk0miya requested changes
LGTM with nits. I'll merge this after the fix soon.

2020-07-23 04:38 UTC, tk0miya commented on tests/roots/test-ext-autosummary-filename-map/index.rst
> +:autolink:`autosummary_importfail`
This link is still remaining. Please remove this. I guess the link above is also not needed for this testcase.

2020-07-23 16:07 UTC, tk0miya approved these changes

2020-07-23 16:07 UTC, merged

2020-07-23 16:07 UTC, tk0miya commented
Just merged. Thank you for your contribution!