basic CSS: fix "highlight-" selector
sphinx-doc/sphinx pull request #7986
Opened 2020-07-19 18:54 UTC by mgeier

In 0dc6e3ac458dd6c10ed2c7bd03ca95bd694d7ec6 I've added

```css
div[class^="highlight-"] {
    margin: 1em 0;
}
```

and in 03be040ca8f5aa6c52b19cf3bf3ab10e284159f6 I've added

```css
div[class|="highlight"] {
    clear: both;
}
```

In the first case I wanted to select `highlight-*` but not `highlight`.
In the second case I didn't care whether `highlight` was selected or not.

The problem is that both selectors only work if they are at the beginning of the `class` attribute.
If they are not (which happens e.g. in a `compound` directive), the selectors don't work as expected.

In this PR, I'm suggesting to change both cases to `div[class*="highlight-"]` which should work in both cases as expected.

This also selects classes which have `highlight-` somewhere in the middle or at the end, but I hope such class names are not used in practice.

### Feature or Bugfix

- Bugfix

### Relates

#7540
#7657

2020-07-20 14:53 UTC, tk0miya requested changes
I can't imagine what happens with this change. Could you upload a screenshot if you have? In addition, please add a CHANGES entry.

2020-07-23 17:33 UTC, tk0miya commented
It seems you changed the target branch. Is this a critical bug? Only critical bug fixes are allowed to 3.1.x branch.

2020-08-01 18:57 UTC, mgeier commented
> Is this a critical bug?

No. I've re-based this PR onto the `3.x` branch and I've changed the base branch here on Github.

> Could you upload a screenshot if you have?

Sure. Here's an example for the `margin` problem:

```rst
.. image:: https://docs.python.org/3/_static/py.png

.. compound::

    .. code-block:: python

        print('hello')

    .. code-block:: python

        print('world')

.. image:: https://docs.python.org/3/_static/py.png
```

**before** (using the ` sphinxdoc` theme):

![image](https://user-images.githubusercontent.com/705404/89108150-71c0ba80-d436-11ea-97e0-9b6feebfe625.png)

Obviously, the `margin` is missing.

**after**:

![image](https://user-images.githubusercontent.com/705404/89108187-b77d8300-d436-11ea-993c-62c118a458fd.png)

The second problem (with `clear`) isn't really visible, but it can be experienced with this example:

```rst
.. sidebar:: A Sidebar

    Some text in the sidebar.

.. compound::

    .. code-block:: python

        print('hello')

    Some text in the compound paragraph.
```

When looking at this `<div>` in the browser's developer tools:

```html
<div class="compound-first highlight-python notranslate">
...
</div>
```

... we can see that it covers the sidebar.

With this PR, it does not cover the sidebar.

None of this is visible with the HTML themes I tried, but it might be visible with a different one?

> In addition, please add a CHANGES entry.

Done: 416438366d0df4cef446e302a2b8a7fd9f1ae5be

2020-08-02 03:03 UTC, tk0miya approved these changes

2020-08-02 03:03 UTC, tk0miya commented
Thank you for your explanation. Merging now.

2020-08-02 03:03 UTC, merged