adds ability for users to provide a custom pygments Style object
sphinx-doc/sphinx pull request #7990
Opened 2020-07-22 03:09 UTC by jmaggio14

Subject: adds ability for users to provide a custom pygments Style object

### Feature or Bugfix
- Feature

### Purpose
Allows users to pass in a pygments Style or a string for the conf.py _pygments_style_ parameter 

This would save them the trouble of adding the Style to their module, making a separate plugin, or monkey patching in a change to pygments directly (as is the in the link below). This was an annoying problem for our project when we wanted to implement custom syntax highlighting, but couldn't figure out the `fully-qualified name of a custom Pygments style class` (link to docs below)

### Relates
docs for  _pygments_style_ parameter: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-pygments_style

monkey patching example: https://stackoverflow.com/questions/48615629/how-to-include-pygments-styles-in-a-sphinx-project)

2020-07-22 03:25 UTC, jmaggio14 commented
fixes linter issue

2020-07-23 04:34 UTC, tk0miya requested changes
+1 for the idea. Could you update document of `pygments_style` and add a testcase for this?

2020-08-07 16:13 UTC, tk0miya commented
Now I change the milestone of this PR to 3.3.0 release (almost 2 months). Please update this until then.

2020-10-04 05:29 UTC, tk0miya commented on sphinx/highlighting.py
>          elif '.' in stylename:
I guess a style object get a failure with this if-block. Is this PR well tested at local?
As I already commented, a testcase is needed to merge this.

2020-12-19 13:22 UTC, tk0miya commented
I noticed `pygments_style` configuration supports a fully-qualified python module. It means it's not hard to add a custom style now. So I change my opinion not to merge this into Sphinx.

>Changed in version 0.3: If the value is a fully-qualified name of a custom Pygments style class, this is then used as custom style.

Thank you for your contribution!

2020-12-19 13:22 UTC, closed without merging