adding a link to the docutils.nodes documentation to make it easier f…
sphinx-doc/sphinx pull request #8010
Opened 2020-07-27 07:13 UTC by maltfield

…or sphinx extension developers to find the list of all useable nodes

Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix
- Refactoring

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2020-07-27 16:18 UTC, tk0miya commented
How about adding docutils' official document instead?
https://docutils.sourceforge.io/docs/ref/doctree.html

2020-07-27 16:29 UTC, maltfield commented
Does that list all the nodes? I did a ctrl+f on that page, and I only found one instance of "nodes," and it said that the reader should instead reference the implentation of the docutils.nodes module (but it also provides no link to said documentation)

> This document does not discuss implementation details. Those can be found in internal documentation (docstrings) for the docutils.nodes module, where the document tree data structure is implemented in a class library.

2020-12-29 16:49 UTC, tk0miya requested changes

2020-12-29 16:49 UTC, tk0miya commented on doc/extdev/nodes.rst
> +.. note:: This page does not list the complete set of nodes available in sphinx. Please also see the `nodes provided by docutils.nodes <http://epydoc.sourceforge.net/docutils/private/docutils.nodes-m
It seems this page has been no longer maintained. This is a document for docutils-0.3.0. It's better to use https://docutils.sourceforge.io/docs/ref/doctree.html instead. This is well maintained upstream's page.

2020-12-29 16:50 UTC, tk0miya commented on doc/extdev/nodes.rst
> +.. note:: This page does not list the complete set of nodes available in sphinx. Please also see the `nodes provided by docutils.nodes <http://epydoc.sourceforge.net/docutils/private/docutils.nodes-m
Oops. I already commented as same...

2020-12-29 16:55 UTC, tk0miya commented
>Does that list all the nodes?

Maybe, yes. On the other hand, the page you pasted does not contains `math` and `math_block` nodes. Because it only describes nodes of docutils-0.3 (17th years ago!).

>(but it also provides no link to said documentation)

The page you used is not an official page. It was created by epydoc project.

2021-01-23 13:20 UTC, closed without merging