i18n: Add support for having single text domain
sphinx-doc/sphinx pull request #8058
Opened 2020-08-06 07:23 UTC by nijel

The gettext_compact can now be a string which is then a single domain
for all documents.

Fixes #784

Subject: Add support for having single text domain

### Feature or Bugfix

- Feature

### Purpose
In many cases it is more useful to have single text domain for all translations. It is now possible to configure that.

### Relates
- https://github.com/sphinx-doc/sphinx/issues/784

2020-08-07 13:26 UTC, tk0miya requested changes
An additional testcase is needed for this to confirm the only a single file is generated. Can you add it please?

2020-08-07 13:26 UTC, tk0miya commented on doc/usage/configuration.rst
> +   .. versionchanged:: 3.2
We'll release 3.2 in this weekend. But some discussion is still needed for this PR. So this would be a part of 3.3.

2020-08-07 18:23 UTC, nijel commented
I've added the test now.

2020-08-08 08:18 UTC, tk0miya approved these changes
LGTM. I'll wait for @shimizukawa 's comment for a while. Please wait until then.

2020-08-13 21:30 UTC, shimizukawa approved these changes
LGTM! 

I was worried in 2015 that having `gettext_compact` have a number or character other than True/False would cause confusion. But I think the "treat it as a domain if you specify a string" idea as implemented in this PR is easy to understand.

2020-08-14 05:21 UTC, merged

2020-08-14 05:22 UTC, tk0miya commented
Now merging. Thank you for your contribution!

@shimizukawa Thank you for wisdom comment :-)