Use alt text as short caption
sphinx-doc/sphinx pull request #8089
Opened 2020-08-09 18:47 UTC by yves-chevallier

In LaTeX figures captions can be written as: 

    \caption[Short description]{Long description}

Having long descriptions for figures will compromise the `\listoffigures`. It is therefore useful to have short description for figures, but Sphinx does not support this out of the box. 

One solution is to use the `alt` text used in HTML `<img alt="text" src="..."/>` for the LaTeX short description. 

There are too many `if` in my patch. Feel free to propose something better.

2020-08-10 05:22 UTC, tk0miya requested changes
+1 for your idea.

2020-08-10 05:22 UTC, tk0miya commented on sphinx/writers/latex.py
> +    def visit_caption(self, node):
Why did you remove annotations?

2020-08-10 05:22 UTC, tk0miya commented on sphinx/writers/latex.py
> +                        short = '[' + texescape.escape(alt) + ']'
How about this? I think this condition should be flatten as others above.
```suggestion
    elif (isinstance(node.parent, node.figure) and isinstance(node.parent.children[0], node.image) and 'alt' in node.parent.children[0]):
        alt = node.parent.children[0]['alt']
        self.body.append(r'\caption[%s]{' % texescape.escape(alt))
    else:
```

2020-08-10 06:00 UTC, yves-chevallier commented on sphinx/writers/latex.py
> +    def visit_caption(self, node):
Bad bad, I as testing it at first...

2020-08-10 07:26 UTC, tk0miya commented
Thank you for update. LGTM.
I'll merge this after you'll add a testcase for this :-)

2020-08-10 08:14 UTC, mgeier commented
I don't think it's a good idea to ab-use the `alt` text as "short description" for the list of figures.

The `alt` text has a quite specific intention, mostly for accessibility, see e.g. https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt.

I think if a "short description" is needed, a separate field should be added.

2020-08-10 08:35 UTC, yves-chevallier commented
@mgeier I partially agree with you. `alt` is not a short description, but as you said a text that is visible for accessibility (when the figure is missing or when the user has some trouble to see the image. 

That said an image that shows the Addams Family with a caption such as:

> The Addams family, from left to right Gomez, Morticia, Wednesday and the Thing on her shoulder.

A good `alt` would be simply 

> The Addams Family

and it would also perfectly fit the purpose the short description...

However, where you are right is if the sphinx user is working with blind people and write the following `alt` for this HTML output, it won't work as short description...

> This is a picture (aspect ratio 3:2) describing the Addams Family in front of their castle at night with some zombies on the backend...

Your suggestion of adding a `short-description` option is good, but everything is currently done in docutils.

2020-08-11 07:22 UTC, yves-chevallier commented
@mgeier I thought more about what you said and I think you're right. If somebody truly use `alt` text for its primarily purpose in HTML, he doesn't want his LaTeX code to be alt'ered with this patch. 

So yes, adding a `short-caption` attribute may be the right option. Then comes the next question : how to do it properly? `figure` is a Docutils node and adding this kind of attribute seems difficult. Any clues would be appreciated.

2020-08-12 16:56 UTC, tk0miya commented
>So yes, adding a short-caption attribute may be the right option. Then comes the next question : how to do it properly? figure is a Docutils node and adding this kind of attribute seems difficult. Any clues would be appreciated.

The proper way is adding a new option to the figure directive. So it would be better to propose this to docutils project. But I don't know that will be accepted. I think reST is a lightweight mark-up language. So it is not a goal to represent all kind of documentations, I believe.

2020-08-12 21:15 UTC, yves-chevallier commented
How difficult is it to enhance the `figure` directive on sphinx side only?

2020-08-13 13:22 UTC, tk0miya commented
No so difficult. But I object to do that for two reasons.

* It makes compatibility problem with docutils. It causes confuses not good to add a directive that is similar to common directive, but different. 
* As I commented above, reST's goal is not representing all kind of document. It's a lightweight mark-up language.

2020-08-13 13:33 UTC, yves-chevallier commented
So I agree with you... What do we do with this PR, should I close it or do we go with the `alt` as *short-caption*?

2020-08-13 13:48 UTC, tk0miya commented
As mgeier said, `:alt:` is not good for short description. So we should close this, sadly.

2020-08-13 13:48 UTC, closed without merging