autodoc: fix constructor signatures for classes derived from typing.Generic
sphinx-doc/sphinx pull request #8142
Opened 2020-08-21 12:14 UTC by jcarrano

Subject: take the constructor signature from __init__ instead of __new__ for classes derived from typing.Generic

### Feature or Bugfix

- Bugfix

### Purpose

When documenting classes derived from `typing.Generic` (essentially all classes in the typing module) the constructor signature would show an unhelpful `(*args, **kwds).`

`typing.Generic.__new__` was being picked up by sphinx.ext.autodoc. With this patch it is skipped and constructor signatures for generic classes are taken from `__init__`.

### Detail

I copied the code that was used to skip callable metaclasses.

2020-08-21 14:07 UTC, tk0miya requested changes
LGTM with nits.

2020-08-21 14:07 UTC, tk0miya commented on tests/test_ext_autodoc.py
> +def test_autodoc_process_signature_typing_generic(app):
Could you rewrite testcase using `do_autodoc()`?

* Add a target class to `tests/roots/test-ext-autodoc/targets/`
* Call `do_autodoc()`. There are many examples in this file.

2020-08-21 16:49 UTC, jcarrano commented on tests/test_ext_autodoc.py
> +def test_autodoc_process_signature_typing_generic(app):
Done. I added a new file because I did not feel it fit in any of the existing test files.

2020-10-02 16:23 UTC, tk0miya approved these changes

2020-10-02 16:23 UTC, merged

2020-10-02 16:23 UTC, tk0miya commented
Merged. Thank you for your support!