Allow production lists to refer to tokens from other production groups.
sphinx-doc/sphinx pull request #8247
Opened 2020-09-28 06:47 UTC by silene

### Feature or Bugfix
- Feature

### Purpose

Outside production lists, syntax `` `foo:bar` `` already makes it possible to refer to the production `bar` of group `foo`. This commit offers the same feature inside production lists. Similarly to the reference syntax, prefixing with a tilde prevents the group from being displayed.

This commit also makes it possible to use `` `:bar` `` to refer to production `bar` from a production list without a group name. This is especially useful when one has a main (unnamed) grammar and one or several named extensions that need to refer to it.

2021-01-20 14:51 UTC, tk0miya requested changes
Looks good. Could you add testcases for this new syntax?

2021-01-20 16:27 UTC, silene commented
I am a bit confused with the testing framework. I suppose I can add some testcases to `tests/roots/test-productionlist/`. But are there some reference files somewhere else that are used to assert that the output is correct? Or is it just a matter of getting the files to compile without errors/warnings?

2021-01-23 05:50 UTC, tk0miya commented
This is a testcase that corresponds with `tests/roots/test-productionlist/`. It builds the document and inspect the result. 
https://github.com/sphinx-doc/sphinx/blob/3.x/tests/test_domain_std.py#L352-L405

It's okay to modify them or to add new pair of project under `tests/roots/` and testcase in `test_domain_std.py`.

2021-01-23 08:01 UTC, silene commented
Thanks for the help. It seemed a bit too frail and tedious to parse the HTML output. (Contrarily to the other tests for `productionlist`, it is the productions themselves that had to be parsed, and they have no structure.) So, I instead decided to check the doctree, as many other tests do.

2021-01-23 08:07 UTC, tk0miya approved these changes

2021-01-23 08:07 UTC, tk0miya commented
Thank you for your work. LGTM!

2021-01-23 08:07 UTC, merged

2021-01-23 08:09 UTC, tk0miya commented
Note: I was wrongly labeled this as "4.0.0". But it's unexpected.