Bump version
sphinx-doc/sphinx pull request #8289
Opened 2020-10-05 08:22 UTC by graingert

Subject: <short purpose of this pull request>

### Feature or Bugfix

- Feature
- Bugfix
- Refactoring

### Purpose
- <long purpose of this pull request>
- <Environment if this PR depends on>

### Detail
- <feature1 or bug1>
- <feature2 or bug2>

### Relates
- <URL or Ticket>

2020-10-05 14:13 UTC, tk0miya requested changes
LGTM with nits

2020-10-05 14:13 UTC, tk0miya commented on CHANGES
> +* #8289: Allow to suppress "duplicated ToC entry found" warnings from epub builder
Please add "epub:" prefix to the after the issue number.

2020-10-05 14:13 UTC, tk0miya commented on doc/usage/configuration.rst
> +
nits: It seems two blank lines here. Could you remove this blank line?

2020-10-05 21:09 UTC, graingert commented on CHANGES
> +* #8289: Allow to suppress "duplicated ToC entry found" warnings from epub builder
```suggestion
* #8289: epub: Allow to suppress "duplicated ToC entry found" warnings from epub builder
```

2020-10-05 21:09 UTC, graingert commented on doc/usage/configuration.rst
> +
```suggestion
```

2020-10-05 21:12 UTC, graingert commented on CHANGES
> +  using :confval:`suppress_warnings`.
```suggestion
* #8289: epub: Allow to suppress "duplicated ToC entry found" warnings from epub
  builder using :confval:`suppress_warnings`.
```

2020-10-06 08:27 UTC, graingert commented
@tk0miya suggestions applied

2020-10-14 13:08 UTC, graingert commented
@tk0miya bump

2020-10-21 12:02 UTC, graingert commented
@sphinx-doc bump

2020-10-24 11:28 UTC, tk0miya approved these changes

2020-10-24 11:29 UTC, merged

2020-10-24 11:29 UTC, tk0miya commented
Merged. Thank you for your contribution!

2020-10-24 11:37 UTC, graingert commented
@tk0miya will this land in 3.2.2?

2020-10-24 11:46 UTC, tk0miya commented
This will be shipped as 3.3.0.