sphinx/themes/basic/layout: Set url_root properly on index, don't use '#'
sphinx-doc/sphinx pull request #8524
Opened 2020-12-07 16:47 UTC by rkdarst

- url_root is set to `#` on the index page, which layout.html tries to
  change back to `''` (the empty string).
- But, this updated url_root wasn't used in the actual location, as an
  argument to `documentation_options.js`.
- Thus, clever enough templates, which tried to use
  `$DOCUMENTATION_OPTIONS.URL_ROOT` inside javascript would fail.
  This was manifested as broken links, which led to this issue:
  https://github.com/executablebooks/sphinx-copybutton/issues/110
- I have eventually traced that back to sphinx itself, and found that
  layout.html tried to fix the problem, but the fixed value wasn't
  used.
- This fix works in my basic test, but I will continue with more tests.
- Review:
  - someone more clever should examine this and make sure it makes
    sense
  - This does not have tests.  Should it?

2020-12-07 18:02 UTC, rkdarst commented
It is a bit hidden in there, but this is a full analysis of *what goes wrong* and why this is needed: https://github.com/executablebooks/sphinx-copybutton/issues/110

2020-12-12 08:09 UTC, tk0miya requested changes
Look good. Could you rebase this into the 3.x branch? Then I'll merge this soon.

2020-12-13 17:20 UTC, rkdarst commented
Ah yes, I forgot 3.x is dev.  Rebased.  Thanks!

2020-12-14 07:56 UTC, rkdarst commented
Now PR edited to have a base branch of `3.x`, which I forgot to do before.

2020-12-14 14:36 UTC, tk0miya approved these changes

2020-12-14 14:36 UTC, merged

2020-12-14 14:36 UTC, tk0miya commented
Thank you for your great work!