Overloaded function signatures do not require a separating backslash
sphinx-doc/sphinx pull request #8841
Opened 2021-02-06 18:25 UTC by AWhetter

### Feature or Bugfix
- Feature

### Purpose
autodoc supports reading multiple docstrings from the start of the docstring. It requires signatures to be separated by a backslash, but it is conventional to not include a backslash as can be seen in the CPython codebase (https://github.com/python/cpython/blob/c0f22fb8b3006936757cebb959cee94e285bc503/Objects/rangeobject.c#L156).
This change allows autodoc to find multiple signatures at the start of the docstring by reading lines from the docstring until it finds the first line that does not look like a signature.

### Detail
N/A

### Relates
- A similar change is being considered in pybind to support this convention: https://github.com/pybind/pybind11/issues/2619

2021-03-02 17:42 UTC, AWhetter commented
Is there anything that I can do to help move this pull request forwards? Should I make an associated issue for it?

2021-03-25 16:27 UTC, brenthuisman approved these changes
lgtm!

2021-03-27 10:05 UTC, tk0miya requested changes
Sorry for the late response. At first, I worried about the side effects of this PR. But it can be ignored (very little). So let's go forward. Could you update the document please?

2021-03-27 10:05 UTC, tk0miya commented on doc/usage/extensions/autodoc.rst
> +   .. versionchanged:: 3.5
This will be merged and released as 4.0. Could you update this please?

2021-03-27 17:27 UTC, AWhetter commented
@tk0miya Thanks for your review. I have made the requested changes. I've also changed the branch to merge into as master, but let me know if that's incorrect.

2021-04-04 09:01 UTC, tk0miya approved these changes

2021-04-04 09:02 UTC, merged

2021-04-04 09:02 UTC, tk0miya commented
Merged. Thank you for your contribution!