#1708 Changed the visited link color for all themes except alabaster
sphinx-doc/sphinx pull request #9027
Opened 2021-03-22 15:16 UTC by Vaibhavi1707

Subject: Changing the visited link colour for all themes except alabaster

### Bugfix

The colors of the visited link have been changed for all themes except alabaster, as I'll commit to the alabaster repository later.

### Detail
- I've changed the colour of all visited links to initial so that it can use the colours as defaulted by the browser.

2021-03-25 04:21 UTC, tk0miya requested changes
Looks good. This will be released as 4.0.0. So, could you rebase this into the master branch and move the CHANGES entry to the 4.0.0 release, please?

2021-03-25 04:22 UTC, tk0miya commented
It would be helpful if you take a screenshot for this change. It's very helpful to me to see how the visited links shown after this change.

2021-03-25 11:36 UTC, Vaibhavi1707 commented
How do we see the changes made? I tried using the `make docs` command but it couldn't show the changes in a particular theme? This is the change from the sphinx13 theme 
![after](https://user-images.githubusercontent.com/53178543/112466847-4eaf9600-8d8c-11eb-879a-15ccc53e4c01.png)

2021-04-04 09:50 UTC, tk0miya commented
Now I took screenshots for this PR (I just made a new project and change its theme):

| name | screenshot |
| --- | --- |
| agogo | <img width="506" alt="スクリーンショット 2021-04-04 18 37 21" src="https://user-images.githubusercontent.com/748828/113504715-d065a780-9574-11eb-9c2f-008e650f54f0.png">
| bizstyle | <img width="426" alt="スクリーンショット 2021-04-04 18 37 55" src="https://user-images.githubusercontent.com/748828/113504726-e1161d80-9574-11eb-9f9b-a9862ec42e38.png">
| classic | <img width="485" alt="スクリーンショット 2021-04-04 18 36 18" src="https://user-images.githubusercontent.com/748828/113504699-b035e880-9574-11eb-8b38-8a69b1bd16c4.png">
| nature | <img width="390" alt="スクリーンショット 2021-04-04 18 38 35" src="https://user-images.githubusercontent.com/748828/113504737-f8eda180-9574-11eb-9635-be9fda2bc545.png">
| pyramid | <img width="485" alt="スクリーンショット 2021-04-04 18 39 00" src="https://user-images.githubusercontent.com/748828/113504749-073bbd80-9575-11eb-813f-a704fd59179a.png">
| scrolls | <img width="429" alt="スクリーンショット 2021-04-04 18 39 27" src="https://user-images.githubusercontent.com/748828/113504759-17ec3380-9575-11eb-9c07-c30368aa5d60.png">
| sphinxdoc | <img width="432" alt="スクリーンショット 2021-04-04 18 39 51" src="https://user-images.githubusercontent.com/748828/113504767-263a4f80-9575-11eb-8731-15edcfaa80ae.png">

It seems visited links are displayed as black text. IMO, it's hard to find the visited hyperlinks from a paragraph. Especially, some themes erase the underscore style from hyperlink. It makes to find them harder. And it seems style is not changed with scrolls theme. Is this as expected?

2022-01-12 17:29 UTC, tk0miya commented
I'm closing this because not been updated for long. Please file a new PR if you'll update this.
Thank you for your contribution!

2022-01-12 17:29 UTC, closed without merging