🐛 FIX: `Config.__getitem__` typing
sphinx-doc/sphinx pull request #9118
Opened 2021-04-19 22:33 UTC by chrisjsewell

Should return `Any` (as for `__getattr__`) rather than `str`

2021-04-20 15:21 UTC, tk0miya requested changes
Could you rebase this into the 4.0.x branch? Then I'll merge this soon.

2021-04-23 20:52 UTC, chrisjsewell commented
Yep done 👍

2021-04-24 08:37 UTC, tk0miya approved these changes

2021-04-24 08:37 UTC, merged

2021-04-24 08:37 UTC, tk0miya commented
Thank you for your work. Merged!