Fix detection when targets are out of date.
sphinx-doc/sphinx pull request #9360
Opened 2021-06-17 20:54 UTC by marxin

Fix detection when targets are out of date.

Fixes #9359.

2021-06-20 03:34 UTC, tk0miya commented
Thank you for your proposal. It seems some tests are failed. Could you check them please?

2021-06-21 07:20 UTC, marxin commented
Well, I am not fully sure why the tests fail. I removed 2x `shared_result` which fixed some tests.
Apart from that I see:
```
app = <SphinxTestApp buildername='texinfo'>, status = <_io.StringIO object at 0x7ffff0876a60>, warning = <_io.StringIO object at 0x7ffff0876af0>

    @pytest.mark.sphinx('texinfo', testroot='markup-rubric')
    def test_texinfo_rubric(app, status, warning):
        app.build()
        print(app)
    
>       output = (app.outdir / 'python.texi').read_text()

tests/test_build_texinfo.py:74: 
```

but when I run only a single test, it works fine `pytest tests/test_build_texinfo.py`. So it's likely about sharing `SphinxTestApp` among tests? Can you please help me?

2021-06-21 08:10 UTC, marxin commented
I've got a tentative patch that works. But as said, I'm not much experienced with Sphinx.

2021-08-06 08:53 UTC, marxin commented
@tk0miya May I please ping this pull request?

2021-11-22 18:47 UTC, marxin commented
May I please ping this pull request?

2022-10-03 11:50 UTC, marxin commented
Rebased this pull request. Is it something @AA-Turner can take a look at, please?

2022-10-05 09:17 UTC, AA-Turner requested changes

2022-10-05 09:17 UTC, AA-Turner commented on tests/test_build_latex.py
> -    app.build()
Please use kwargs here

2022-10-05 09:17 UTC, AA-Turner commented on tests/test_build_manpage.py
> +    app.build(True)
Please use kwargs here

2022-10-05 09:17 UTC, AA-Turner commented on tests/test_build_texinfo.py
> +    app.build(True)
Please use kwargs here

2022-10-05 13:06 UTC, AA-Turner approved these changes

2022-10-05 13:07 UTC, AA-Turner commented
Please add a CHANGES entry

A

2022-10-05 13:31 UTC, marxin commented
> Please add a CHANGES entry

Done.

2022-10-05 13:43 UTC, AA-Turner commented on CHANGES
> +  in source files. Patch by Martin Liska.
```suggestion
* #9360: Fix caching for now-outdated files for some builders (e.g. manpage)
  when there is no change in source files. Patch by Martin Liska.
```

2022-10-05 13:44 UTC, merged

2022-10-05 13:44 UTC, AA-Turner commented
Thanks @marxin!

A

2022-10-05 13:46 UTC, marxin commented
I thank you!