#2021: changed behaviour to only consider elements of __all__ members…
sphinx-doc/sphinx pull request #9455
Opened 2021-07-15 19:20 UTC by randolf-scholz

…, if __all__ exists

Addresses https://github.com/sphinx-doc/sphinx/issues/2021

### Feature or Bugfix

- Feature
- Bugfix

Not sure if it should be considered a feature enhancement or bug fix.

### Purpose
- autosummary ignores `__all__` files when determining members, this PR changes the behaviour to always respect the `__all__` list, if it exists.

### Detail
- Changed 2 iterators from
- 
```python
for name in dir(obj):
```

to

```python
for name in getall(obj) or dir(obj):
```
using the `sphinx.util.inspect.getall` function, which returns `__all__`, if it exists, else `None`.

### Relates
- https://github.com/sphinx-doc/sphinx/issues/2021

2021-09-07 10:09 UTC, marscher commented
Thank you, that would simplify my duties a lot!

2021-09-12 16:44 UTC, tk0miya requested changes
Looks good. But we need to add an option to keep `__all__` list ignored.

2021-09-19 20:54 UTC, randolf-scholz commented
> Looks good. But we need to add an option to keep `__all__` list ignored.

Is this really necessary? I would be surprised if there is a single project that really wants this option.
The point is that if one adds something like the following `members` block to the [modules template](https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/ext/autosummary/templates/autosummary/module.rst)

```yaml
{% block members %}
{% if members %}
.. rubric:: {{ _('Module Members') }}
.. autosummary::
  :toctree: {{ objname }}
{% for item in members %}
  {{ item }}
{%- endfor %}
{% endif %}
{% endblock %}
```

Then all of the otherwise hidden module members get added as well:

![Screenshot from 2021-09-19 22-49-26](https://user-images.githubusercontent.com/39696536/133942642-521e31ec-ba46-47d1-a61f-8104ca80f15f.png)

Who would want to see all this nonsense for every module?

2021-09-23 09:01 UTC, marscher commented
I'd agree to that no one wants to have these kind of implementation details in the members list. However I think that since this is a change of behavior, people should be given the chance to still use the old behavior. Therefore we need a switch.

2021-09-25 05:14 UTC, tk0miya commented
>Is this really necessary? I would be surprised if there is a single project that really wants this option.

I can't say there are no projects that depend on the old behavior in the world. I agree they're very few. But this change will bring a breaking change for them. So I can't accept this change without an option.

2021-11-08 10:18 UTC, Yoshanuikabundi commented
@randolf-scholz Hi! I need this feature and don't want it to miss the next release. I'd be happy to extend this PR to take a configuration option, but don't want to step on your toes! Please let me know if you're committed to finishing things up here, or if you don't mind me taking over.

2021-11-08 11:12 UTC, randolf-scholz commented
@Yoshanuikabundi Hey, sorry I am super busy atm and don't really have time look into it currently. Personally, for several other reasons I also switched my projects to https://github.com/readthedocs/sphinx-autoapi.

2021-11-09 07:17 UTC, Yoshanuikabundi commented
@randolf-scholz No worries, thanks for the update!

2021-11-10 19:18 UTC, marscher commented
@Yoshanuikabundi I sent a PR to @randolf-scholz including the config interface already. I think it would serve as a base to make further progress. The only thing missing are proper tests for the new interface.

@randolf-scholz when you are so busy, would you like to delegate this to our hands? I dunno if or how we would be able to directly push to your forked branch, but this would simplify things a lot. Thank you!

2021-11-11 16:05 UTC, tk0miya commented
@marscher  I think #9831 is a successor of this PR. Could you check it please?

2021-11-12 01:17 UTC, marscher commented
sorry i'm out of time right now, but will do next week. The code looks good so far.

2021-11-25 17:16 UTC, tk0miya commented
Now I merged #9831 as a successor of this PR. Thank you for all your contributions :-)

2021-11-25 17:16 UTC, closed without merging