Updated EXAMPLES
sphinx-doc/sphinx pull request #9541
Opened 2021-08-11 15:14 UTC by vedranmiletic

- removed or replaced missing docs
- removed docs that switched to using other tools
- added some new docs

2021-08-11 15:18 UTC, tk0miya requested changes
Thank you for your work. LGTM!! But it seems CI gets errored. Could you check it, please?

2021-08-12 07:56 UTC, vedranmiletic commented
> 
> 
> Thank you for your work. LGTM!! But it seems CI gets errored. Could you check it, please?

Sorry, should have checked it better. Should be OK now.

2021-08-12 16:37 UTC, tk0miya approved these changes

2021-08-12 16:38 UTC, merged

2021-08-12 16:38 UTC, tk0miya commented
Merged. Thank you for your contribution!